"""cemit — the self-arming C shim (Stage 110).

The launcher arms a child and execs it; the shim is the other
half of the story: a standalone C translation unit that arms the
binary ITSELF, in a constructor that runs before main.

    cc -O2 -o prog prog.c hls_sandbox_<profile>.c

The constructor:
  1. prctl(PR_SET_NO_NEW_PRIVS, 1)  — the contract that makes the
     filter installable unprivileged and survivable across exec
  2. seccomp(SECCOMP_SET_MODE_FILTER, 0, &prog) — via the
     SYS_seccomp number for the target arch (the kernel headers'
     SYS_seccomp when present, the recorded number otherwise)

Constructor priority 101 puts the arm ahead of default-priority
constructors (the language runtime's own), and the arm is SILENT
on success — a constructor that prints would pollute every
program's stdout and break byte-parity with the interpreter. The
evidence the sandbox is armed is behavioral: the first denied
syscall surfaces as EPERM (or SIGSYS in kill mode), which is the
point.

Cross-arch is the reason `emit` exists separately from `run`:
`emit --arch riscv64` writes the NUMBERS for riscv64 — build the
shim on the target (or cross-compile it) and the artifact is
confined there without ever needing this tool on the machine. The
shim therefore refuses to compile for an arch whose AUDIT_ARCH
value or syscall numbers the toolchain does not record — the one
dishonest thing an emitter could do is guess a number.

The emitted file carries a comment header naming the profile that
produced it (effects, fs mode, default action, baseline) so the
artifact is auditable YEARS later without the tree it came from.
"""
from __future__ import annotations

import os
import sys

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(TOOL_DIR))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)
_SBX = os.path.dirname(TOOL_DIR)
if _SBX not in sys.path:
    sys.path.insert(0, _SBX)

from sandbox_parts import sbx_bpf as bpf                      # noqa: E402
from sandbox_parts.sbx_policy import Profile, _AUDIT_ARCH     # noqa: E402

# The recorded seccomp(2) syscall numbers per arch (used when
# SYS_seccomp is not provided by the target's headers). Same
# numbers the launcher's ctypes path uses — one table.
_SECCOMP_NR = {"x86_64": 317, "aarch64": 277, "riscv64": 277}

_SHIM_TEMPLATE = '''\
/* hls-sandbox shim — generated by tools/hls-sandbox.py (Stage 110).
 *
 * profile:   effects=%(effects)s fs=%(fs)s default=%(default)s
 *            baseline=%(baseline)s
 * arch:      %(arch)s (AUDIT_ARCH 0x%(audit_arch)x)
 * program:   %(instrs)d instructions, %(syscalls)d syscalls allowed
 *%(deny_note)s
 * Compile into the artifact:
 *     cc -O2 -o prog prog.c this_file.c
 *
 * Arms in a constructor (priority 101, ahead of the runtime's own
 * constructors): NO_NEW_PRIVS, then the filter. Silent on success —
 * the first denied syscall is the evidence (EPERM, or SIGSYS under
 * the kill default).
 */
#include <sys/prctl.h>
#include <linux/seccomp.h>
#include <linux/filter.h>
#include <linux/audit.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <stddef.h>

#ifndef SECCOMP_MODE_FILTER
#define SECCOMP_MODE_FILTER 2
#endif

%(filter_array)s

__attribute__((constructor(101)))
static void hl_sandbox_arm(void) {
    unsigned long nr_seccomp =
#ifdef SYS_seccomp
        (unsigned long)SYS_seccomp;
#else
        %(seccomp_nr)dUL;  /* recorded for %(arch)s by hls-sandbox */
#endif
    struct sock_fprog prog = {
        .len = (unsigned short)(sizeof(hl_sandbox_filter)
                                / sizeof(hl_sandbox_filter[0])),
        .filter = (struct sock_filter *)hl_sandbox_filter,
    };
    if (prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0)
        return;              /* refused: run unconfined, say nothing */
    (void)syscall(nr_seccomp, SECCOMP_SET_MODE_FILTER, 0, &prog);
}
'''


def emit_shim(profile, arch, path):
    """Write the self-arming shim for `arch` to `path`. Returns the
    path. The filter bytes come from the SAME assembler the launcher
    installs — one definition of the program, two delivery modes."""
    program = profile.program(arch)
    rules = profile.rules(arch)
    deny = list(profile.deny)
    deny_note = ("\n *            denied: %s" % ", ".join(deny)) if deny \
        else ""
    body = _SHIM_TEMPLATE % {
        "effects": (", ".join(profile.effects) or "(none)"),
        "fs": profile.fs_mode or "(none)",
        "default": profile.default_action,
        "baseline": profile.baseline,
        "arch": arch,
        "audit_arch": _AUDIT_ARCH[arch],
        "instrs": len(program),
        "syscalls": len(rules),
        "deny_note": deny_note,
        "seccomp_nr": _SECCOMP_NR[arch],
        "filter_array": program.c_array(),
    }
    with open(path, "w") as fh:
        fh.write(body)
    return path


__all__ = ["emit_shim"]
