"""hwp_types — TypeScript declaration emitter for Stage 76.

Maps Halis types to TypeScript types and renders the publish-ready
``<name>.d.ts`` for a packed ``pkg/`` dir.

Mapping (documented in the emitted header):

  int / float        -> number     (wasm i64/f64 surface as JS numbers;
                                    int64 values beyond 2^53 lose
                                    precision — the header says so)
  bool               -> boolean
  str                -> string
  list[T]            -> Array<T>
  map[str, T]        -> Record<string, T>
  tainted[T]         -> T          (taint is compile-time only)
  Option[T]          -> T | null
  Result[T, E]       -> T          (Err is a documented throw-site)
  void               -> void
  struct S           -> interface S (by scanned fields)
  enum E             -> string-literal union of variant names
  anything else      -> unknown    (never lie in a declaration file)

Every exported Halis function becomes an exported TS function; every
struct becomes an interface; every enum becomes a union type. The
loader API (``defaultInit`` / ``run`` / ``callHalis`` / struct
helpers) is appended from a fixed template per target.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List

_HEADER = """/* AUTO-GENERATED by hls-wasm-pack (Stage 76) — do not edit.
 *
 * Halis -> TypeScript mapping:
 *   int/float -> number (int64 beyond 2^53 loses precision)
 *   bool -> boolean, str -> string
 *   list[T] -> Array<T>, map[str, T] -> Record<string, T>
 *   tainted[T] -> T (taint is compile-time only)
 *   Option[T] -> T | null
 *   Result[T, E] -> T (an Err payload is a documented throw-site)
 *   struct -> interface, enum -> string-literal union
 *   anything else -> unknown (this file never lies)
 */
"""


def halis_to_ts(hls_type: str) -> str:
    """Map a Halis type string to a TypeScript type string."""
    t = (hls_type or "").strip()
    if t in ("int", "float"):
        return "number"
    if t == "bool":
        return "boolean"
    if t == "str":
        return "string"
    if t == "void":
        return "void"
    m = re.match(r"^tainted\[(.*)\]$", t, re.DOTALL)
    if m:
        return halis_to_ts(m.group(1))
    m = re.match(r"^list\[(.*)\]$", t, re.DOTALL)
    if m:
        return "Array<%s>" % halis_to_ts(m.group(1))
    m = re.match(r"^map\[\s*str\s*,(.*)\]$", t, re.DOTALL)
    if m:
        return "Record<string, %s>" % halis_to_ts(m.group(1))
    m = re.match(r"^Option\[(.*)\]$", t, re.DOTALL)
    if m:
        return "%s | null" % halis_to_ts(m.group(1))
    m = re.match(r"^Result\[(.*?),(.*)\]$", t, re.DOTALL)
    if m:
        return halis_to_ts(m.group(1))
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", t):
        # A nominal struct/enum reference — emitted as-is so it links
        # to the interface/union declared below when scanned, and
        # degrades to an opaque named type otherwise.
        return t
    return "unknown"


def _fn_decl(fn: Dict[str, Any]) -> str:
    params = ", ".join(
        "%s: %s" % (p["name"], halis_to_ts(p["type"]))
        for p in fn.get("params", []))
    ret = halis_to_ts(fn.get("returns", "void"))
    return "export function %s(%s): %s;" % (fn["name"], params, ret)


def _struct_decl(st: Dict[str, Any]) -> str:
    lines = ["export interface %s {" % st["name"]]
    for f in st.get("fields", []):
        lines.append("  %s: %s;" % (f["name"], halis_to_ts(f["type"])))
    lines.append("}")
    return "\n".join(lines)


def _enum_decl(en: Dict[str, Any]) -> str:
    variants = en.get("variants", [])
    if not variants:
        return "export type %s = never;" % en["name"]
    union = " | ".join('"%s"' % v["name"] for v in variants)
    return "export type %s = %s;" % (en["name"], union)


_LOADER_API = """
/* Loader API (provided by the generated .js glue). */
export interface HalisInstance {
  memory: WebAssembly.Memory;
  run(): Promise<bigint>;
  callHalis(cbId: number, json: string): Promise<string>;
  readStruct(name: string, ptr: number): Record<string, unknown>;
  writeStruct(name: string, value: Record<string, unknown>): number;
  registerStruct(desc: StructDescriptor): void;
}
export interface StructDescriptor {
  name: string;
  size: number;
  fields: Array<{ name: string; type: string; offset: number }>;
}
export declare const memory: WebAssembly.Memory;
export default function init(input?: string | URL | ArrayBuffer | WebAssembly.Module): Promise<HalisInstance>;
"""


def render_dts(surface: Dict[str, Any], package_name: str) -> str:
    """Render the full ``.d.ts`` source for ``surface``."""
    out: List[str] = [_HEADER.rstrip(), "",
                      "/* Package: %s */" % package_name, ""]
    for st in surface.get("structs", []):
        out.append(_struct_decl(st))
        out.append("")
    for en in surface.get("enums", []):
        out.append(_enum_decl(en))
        out.append("")
    from hwp_scan import exported_functions
    fns = exported_functions(surface)
    if fns:
        out.append("/* Exported Halis functions (sync wrappers over the wasm module). */")
        for fn in fns:
            out.append(_fn_decl(fn))
        out.append("")
    else:
        out.append("/* No exported Halis functions (only main). */")
        out.append("")
    out.append(_LOADER_API.strip())
    out.append("")
    return "\n".join(out)


__all__ = [
    "halis_to_ts",
    "render_dts",
]
