// =============================================================
// C code generated BY hlc — the Halis compiler (HLS)
// The HLS source is compiled by hlc itself (self-hosted).
// =============================================================

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <inttypes.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <dirent.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <unistd.h>
#ifdef HL_HAVE_LIBCURL
#include <curl/curl.h>
#endif
#include <pthread.h>
#include <sched.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>

typedef struct { int64_t refcnt; int64_t len; char* data; } hl_str;
typedef struct { int64_t refcnt; int64_t len; int64_t cap; void** items; void (*elem_free)(void*); } hl_list;
typedef struct { int64_t refcnt; int64_t len; int64_t cap; hl_str** slots; void** vals; hl_str** order; void (*val_free)(void*); } hl_map;

// ---- Stage 81 (v0.100.0-alpha): panic-handler hook ----
// A program that declares #[panic_handler] fn panic_handler(msg:
// str) -> void gets it wired here: the entry point (_start / main)
// sets hl_panic_hook to the compiled handler, and every panic
// path below invokes it once before the default action. Programs
// without a handler leave the hook NULL: behaviour is unchanged.
// hl_in_panic is the reentrancy guard — a nested panic inside the
// handler (e.g. OOM while wrapping the message) falls straight
// through to the default action instead of recursing.
static void (*hl_panic_hook)(hl_str*) = 0;
static int hl_in_panic = 0;
static hl_str* hl_str_from(const char* c, int64_t len);
// The guard is raised BEFORE the message is wrapped: wrapping
// allocates, and an OOM inside the wrap re-enters hl_die — with
// the guard already up it falls straight through to the default
// action instead of recursing.
// The hook always receives a COPY: the compiled handler takes
// ownership of its parameter (cleanup attribute releases it on
// return), so passing the caller's string would use-after-free
// the default report below. The copy is the handler's to keep
// or release; the original is untouched.
static void hl_call_panic_hook(hl_str* msg) {
    if (hl_panic_hook && !hl_in_panic) {
        hl_in_panic = 1;
        hl_panic_hook(hl_str_from(msg->data, msg->len));
        hl_in_panic = 0;
    }
}
static void hl_call_panic_hook_cstr(const char* msg) {
    if (hl_panic_hook && !hl_in_panic) {
        hl_in_panic = 1;
        hl_str* hm = hl_str_from(msg, (int64_t)strlen(msg));
        hl_panic_hook(hm);
        hl_in_panic = 0;
    }
}

// Checked byte string — used by the HLS runtime
static void hl_die(const char* msg) {
    hl_call_panic_hook_cstr(msg);
    fflush(stdout);
    fprintf(stderr, "panic: %s\n", msg);
    exit(101);
}

// The SOURCE-LOCATION die, in the interpreter's exact format: a
// native binary that reported a bare "integer overflow" while the
// interpreter reported which line overflowed disagreed with it on
// the very output the differential tests compare.
static bool hl_msg_has_loc(const char* s);
static void hl_die_line(const char* msg, int64_t line) {
    hl_call_panic_hook_cstr(msg);
    fflush(stdout);
    if (line > 0 && !hl_msg_has_loc(msg)) {
        fprintf(stderr, "panic: %s (at line %lld)\n", msg, (long long)line);
    } else {
        fprintf(stderr, "panic: %s\n", msg);
    }
    exit(101);
}

static void hl_die_at(const char* msg, const char* file, int64_t line) {
    hl_call_panic_hook_cstr(msg);
    fflush(stdout);
    if (file && line > 0) {
        fprintf(stderr, "panic: %s (at %s:%lld)\n", msg, file, (long long)line);
    } else {
        fprintf(stderr, "panic: %s\n", msg);
    }
    exit(101);
}

static char* hl_sandbox_root = NULL;
static bool hl_simd_cpu_supports(hl_str* s) {
    if (!s) return false;
#define HL_FEAT_EQ(lit) \
    (s->len == (int64_t)sizeof(lit) - 1 && memcmp(s->data, lit, sizeof(lit) - 1) == 0)
#if defined(__x86_64__) || defined(__i386__)
    if (HL_FEAT_EQ("avx")) return __builtin_cpu_supports("avx");
    if (HL_FEAT_EQ("avx2")) return __builtin_cpu_supports("avx2");
    if (HL_FEAT_EQ("sse3")) return __builtin_cpu_supports("sse3");
    if (HL_FEAT_EQ("sse4.2")) return __builtin_cpu_supports("sse4.2");
    return false;
#elif defined(__aarch64__)
    if (HL_FEAT_EQ("neon")) return true; /* NEON is baseline on aarch64 */
    return false;
#else
    return false;
#endif
#undef HL_FEAT_EQ
}

static void hl_set_sandbox_root(const char* dir) {
    if (hl_sandbox_root) { free(hl_sandbox_root); hl_sandbox_root = NULL; }
    if (dir) {
        // Canonicalise via realpath so symlink escapes are caught.
        char buf[4096];
        char* rp = realpath(dir, buf);
        // Deep-scan fix (CC14): check strdup's return. On OOM strdup
        // returns NULL, silently disabling the sandbox. Refuse to
        // proceed if we can't allocate the canonicalised path.
        if (rp) {
            char* dup = strdup(rp);
            if (!dup) hl_die("out of memory");
            hl_sandbox_root = dup;
        }
    }
}

static void hl_sandbox_check(const char* path) {
    if (!hl_sandbox_root) return;
    char buf[4096];
    char* rp = realpath(path, buf);
    // If realpath fails, the path doesn't exist yet (e.g. a write_file
    // target). Resolve the parent directory and check it.
    if (!rp) {
        // Find the last path separator and resolve the parent.
        char tmp[4096];
        strncpy(tmp, path, sizeof(tmp) - 1);
        tmp[sizeof(tmp) - 1] = 0;
        size_t L = strlen(tmp);
        while (L > 0 && tmp[L-1] != '/' && tmp[L-1] != '\\') {
            tmp[--L] = 0;
        }
        if (L == 0) { strcpy(tmp, "."); L = 1; }
        char pbuf[4096];
        char* pp = realpath(tmp, pbuf);
        if (!pp) hl_die("sandbox violation: cannot resolve path");
        // Re-append the basename.
        // Deep-scan-28 fix (off-by-one): when the path has NO
        // separator the strip loop empties tmp and re-appends
        // from path+1, silently DROPPING the first character
        // ("new.txt" became pp+"ew.txt" -> spurious sandbox
        // violation). The parent is "." in that case, so the
        // full path must be re-joined with an explicit '/'.
        if (L == 0 || (L == 1 && tmp[0] == '.')) {
            snprintf(buf, sizeof(buf), "%s/%s", pp, path);
        } else {
            snprintf(buf, sizeof(buf), "%s%s", pp, path + L);
        }
    }
    // Common-prefix check with a separator after the prefix.
    size_t sb_len = strlen(hl_sandbox_root);
    if (strncmp(buf, hl_sandbox_root, sb_len) != 0)
        hl_die("sandbox violation: path resolves outside the sandbox");
    char next = buf[sb_len];
    // Deep-scan fix (C9): accept both / and \\ as path separators
    // so the sandbox works on Windows. Previously only / was
    // accepted, causing every sandboxed file op to panic on Windows
    // (the parent-strip loop at line ~4207 accepts both, so the
    // inconsistency was a latent portability bug).
    if (next != 0 && next != '/' && next != '\\')
        hl_die("sandbox violation: path resolves outside the sandbox");
}

// ---- Stage 8-beta: reference-counting core ----
// refcnt is the first field of every heap object, so retain is
// generic; release is type-specific (it must release children).
static void* hl_retain(void* p) {
    if (p) ((int64_t*)p)[0] += 1;
    return p;
}

// ---- Stage 16: the concurrency runtime (tasks + channels) ----
typedef struct hl_msg {
    union { int64_t i; double f; void* p; } v;
    struct hl_msg* next;
} hl_msg;

typedef struct hl_chan {
    volatile int64_t refcnt;   // ATOMIC — channels are shared across threads
    hl_msg* head;              // FIFO queue (guarded by g_rt_mu)
    hl_msg* tail;
    int64_t cap;               // 0 = unbounded; >= 1 = bounded: send blocks while full
    int64_t count;             // pending messages (guarded by g_rt_mu; O(1) len)
    int64_t waiters;           // threads blocked in recv/select on THIS channel
    int64_t send_waiters;      // threads blocked sending to this full channel
    struct hl_chan *reg_next, *reg_prev;  // live-channel registry (deadlock scan)
    void (*elem_release)(void*);  // pointer-payload release (NULL for primitives)
} hl_chan;

typedef union { int64_t i; double f; void* p; } hl_task_res;

typedef struct hl_task {
    int64_t refcnt;            // guarded by g_rt_mu
    pthread_t th;
    bool done;
    bool joined;
    bool freed;
    hl_task_res res;
} hl_task;

typedef struct { void (*body)(void*, hl_task*); void* argbox; hl_task* task; } hl_spawn_ctx;

static pthread_mutex_t g_rt_mu = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t  g_rt_cv = PTHREAD_COND_INITIALIZER;
static int64_t g_rt_tasks   = 0;   // spawned tasks alive (main excluded)
static int64_t g_rt_blocked = 0;   // threads blocked in recv/select/join/send (main included)
static int64_t g_rt_msgs    = 0;   // pending messages across ALL channels
static int64_t g_rt_done_unjoined = 0;   // tasks done but not yet joined
static int64_t g_rt_join_waiters = 0;   // threads currently blocked in join (deep-scan-20)
static hl_chan* g_rt_chans  = NULL; // live-channel registry (guarded by g_rt_mu)

// Deadlock check — call with g_rt_mu HELD, before blocking.
// Fires when EVERY thread is blocked (recv/select/join/full-send)
// AND no channel has a progress opportunity: a pending message
// with a recv waiter, or free capacity with a send waiter. A
// woken-but-unscheduled thread is still counted in g_rt_blocked
// (its decrement happens only after cond_wait re-acquires the
// mutex), which is exactly why the waiter counters are needed:
// `blocked == alive` alone can fire while a consumer's message is
// already pending but the consumer has not been scheduled. (A
// thread between two operations holds the mutex and is never
// miscounted, so this cannot fire spuriously. Mirrors the Python
// ConcRuntime.deadlock_check exactly.)
static void hl_rt_deadlock_check(void) {
    int64_t alive = g_rt_tasks + 1;   // +1: the main thread
    if (g_rt_blocked != alive) return;
    // Stage 33: if any task is done but not yet joined, a join
    // waiter can proceed — not a deadlock. Deep-scan-20 fix:
    // only when a thread is ACTUALLY blocked in join(). The old
    // unconditional guard also excused real deadlocks where a
    // finished-but-never-joined task existed and every remaining
    // thread was blocked on an empty channel — the runtime then
    // hung forever instead of reporting the deadlock (boot/native
    // divergence: the interpreter panicked correctly).
    if (g_rt_done_unjoined > 0 && g_rt_join_waiters > 0) return;
    for (hl_chan* c = g_rt_chans; c; c = c->reg_next) {
        if (c->head && c->waiters > 0) return;       // a consumer can proceed
        if (c->send_waiters > 0 && c->count < c->cap) return;  // a woken sender can proceed
    }
    pthread_mutex_unlock(&g_rt_mu);
    hl_die("deadlock: all tasks are blocked on channel operations (no possible progress)");
}

static void hl_chan_register(hl_chan* c) {
    c->reg_next = g_rt_chans;
    c->reg_prev = NULL;
    if (g_rt_chans) g_rt_chans->reg_prev = c;
    g_rt_chans = c;
}
static void hl_chan_unregister(hl_chan* c) {  // g_rt_mu HELD
    if (c->reg_prev) c->reg_prev->reg_next = c->reg_next; else g_rt_chans = c->reg_next;
    if (c->reg_next) c->reg_next->reg_prev = c->reg_prev;
}

static hl_chan* hl_chan_new_cap(int64_t cap, void (*elem_release)(void*)) {
    hl_chan* c = (hl_chan*)malloc(sizeof(hl_chan));
    if (!c) hl_die("out of memory");
    c->refcnt = 1;
    c->head = NULL;
    c->tail = NULL;
    c->cap = cap;
    c->count = 0;
    c->waiters = 0;
    c->send_waiters = 0;
    c->elem_release = elem_release;
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_register(c);
    pthread_mutex_unlock(&g_rt_mu);
    return c;
}
static hl_chan* hl_chan_new(void (*elem_release)(void*)) {
    return hl_chan_new_cap(0, elem_release);
}
// chan_new_bounded(cap) — send blocks while `cap` messages are pending.
// The checker rejects literal capacities < 1; dynamic ones die here.
static hl_chan* hl_chan_new_bounded(int64_t cap, void (*elem_release)(void*)) {
    if (cap < 1) hl_die("chan_new_bounded() capacity must be >= 1");
    return hl_chan_new_cap(cap, elem_release);
}

// clone() of a channel SHARES it (atomic refcount + 1) — the whole
// point of a channel. This is the ONLY clone in the language that
// does not produce an independent copy.
static hl_chan* hl_chan_clone(hl_chan* c) {
    if (c) __atomic_fetch_add(&c->refcnt, 1, __ATOMIC_ACQ_REL);
    return c;
}

static void hl_chan_release(void* pv) {
    hl_chan* c = (hl_chan*)pv;
    if (!c) return;
    if (__atomic_fetch_sub(&c->refcnt, 1, __ATOMIC_ACQ_REL) == 1) {
        // Last reference. v0.29.0-alpha: first unlink the channel
        // from the live-channel registry (the deadlock scan must
        // not walk a freed node). No waiter can exist: refcnt==0
        // means no binding holds the channel, and every
        // send/recv requires a live reference — so send_waiters ==
        // waiters == 0 here. The drain then runs WITHOUT the lock;
        // releasing payload channels re-enters safely (no nesting).
        pthread_mutex_lock(&g_rt_mu);
        hl_chan_unregister(c);
        pthread_mutex_unlock(&g_rt_mu);
        hl_msg* m = c->head;
        while (m) {
            hl_msg* nx = m->next;
            if (c->elem_release && m->v.p) c->elem_release(m->v.p);
            free(m);
            m = nx;
        }
        free(c);
    }
}
static void hl_cleanup_chan(hl_chan** p) { hl_chan_release(*p); }

// Blocking enqueue — g_rt_mu HELD. On a bounded channel, waits
// while the queue holds `cap` messages (backpressure); a dequeue
// broadcasts, which is what wakes a sender blocked here. Unbounded
// channels (cap == 0) never block the sender.
static void hl_chan_enqueue(hl_chan* c, hl_msg* m) {  // g_rt_mu HELD
    while (c->cap > 0 && c->count >= c->cap) {
        c->send_waiters++;
        g_rt_blocked++;
        hl_rt_deadlock_check();
        pthread_cond_wait(&g_rt_cv, &g_rt_mu);
        g_rt_blocked--;
        c->send_waiters--;
    }
    if (c->tail) { c->tail->next = m; } else { c->head = m; }
    c->tail = m;
    m->next = NULL;
    c->count++;
    g_rt_msgs++;
    pthread_cond_broadcast(&g_rt_cv);
}

static hl_msg* hl_chan_dequeue(hl_chan* c) {  // g_rt_mu HELD
    hl_msg* m = c->head;
    c->head = m->next;
    if (!c->head) c->tail = NULL;
    c->count--;
    g_rt_msgs--;
    // Freeing capacity can unblock a bounded-channel sender.
    pthread_cond_broadcast(&g_rt_cv);
    return m;
}

static void hl_chan_send_ptr(hl_chan* c, void* v) {
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.p = v;
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_enqueue(c, m);
    pthread_mutex_unlock(&g_rt_mu);
}
static void hl_chan_send_i64(hl_chan* c, int64_t v) {
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.i = v;
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_enqueue(c, m);
    pthread_mutex_unlock(&g_rt_mu);
}
static void hl_chan_send_f64(hl_chan* c, double v) {
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.f = v;
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_enqueue(c, m);
    pthread_mutex_unlock(&g_rt_mu);
}

// try_send — non-blocking variants: false iff a bounded channel
// is full (the value is NOT enqueued). For pointer payloads the
// caller's defensive copy is RELEASED here when the send fails
// (elem_release owns exactly that payload type).
static bool hl_chan_try_send_ptr(hl_chan* c, void* v) {
    pthread_mutex_lock(&g_rt_mu);
    if (c->cap > 0 && c->count >= c->cap) {
        if (c->elem_release && v) c->elem_release(v);
        pthread_mutex_unlock(&g_rt_mu);
        return false;
    }
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.p = v;
    m->next = NULL;
    if (c->tail) { c->tail->next = m; } else { c->head = m; }
    c->tail = m;
    c->count++;
    g_rt_msgs++;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return true;
}
static bool hl_chan_try_send_i64(hl_chan* c, int64_t v) {
    pthread_mutex_lock(&g_rt_mu);
    if (c->cap > 0 && c->count >= c->cap) {
        pthread_mutex_unlock(&g_rt_mu);
        return false;
    }
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.i = v;
    m->next = NULL;
    if (c->tail) { c->tail->next = m; } else { c->head = m; }
    c->tail = m;
    c->count++;
    g_rt_msgs++;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return true;
}
static bool hl_chan_try_send_f64(hl_chan* c, double v) {
    pthread_mutex_lock(&g_rt_mu);
    if (c->cap > 0 && c->count >= c->cap) {
        pthread_mutex_unlock(&g_rt_mu);
        return false;
    }
    hl_msg* m = (hl_msg*)malloc(sizeof(hl_msg));
    if (!m) hl_die("out of memory");
    m->v.f = v;
    m->next = NULL;
    if (c->tail) { c->tail->next = m; } else { c->head = m; }
    c->tail = m;
    c->count++;
    g_rt_msgs++;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return true;
}

static void hl_chan_wait(hl_chan* c) {  // g_rt_mu HELD
    while (!c->head) {
        c->waiters++;
        g_rt_blocked++;
        hl_rt_deadlock_check();
        pthread_cond_wait(&g_rt_cv, &g_rt_mu);
        g_rt_blocked--;
        c->waiters--;
    }
}

static void* hl_chan_recv_ptr(hl_chan* c) {
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_wait(c);
    hl_msg* m = hl_chan_dequeue(c);
    void* v = m->v.p;
    free(m);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}
static int64_t hl_chan_recv_i64(hl_chan* c) {
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_wait(c);
    hl_msg* m = hl_chan_dequeue(c);
    int64_t v = m->v.i;
    free(m);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}
static double hl_chan_recv_f64(hl_chan* c) {
    pthread_mutex_lock(&g_rt_mu);
    hl_chan_wait(c);
    hl_msg* m = hl_chan_dequeue(c);
    double v = m->v.f;
    free(m);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}

// recv_or — non-blocking recv: the pending message if one exists,
// else the caller's default. For pointer payloads the default is
// an OWNED extra reference (the codegen own-wraps non-fresh
// expressions); when a message IS available the default must be
// released here via elem_release (it owns exactly that type).
static void* hl_chan_recv_or_ptr(hl_chan* c, void* def) {
    pthread_mutex_lock(&g_rt_mu);
    if (!c->head) {
        pthread_mutex_unlock(&g_rt_mu);
        return def;
    }
    hl_msg* m = hl_chan_dequeue(c);
    void* v = m->v.p;
    free(m);
    if (c->elem_release && def) c->elem_release(def);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}
static int64_t hl_chan_recv_or_i64(hl_chan* c, int64_t def) {
    pthread_mutex_lock(&g_rt_mu);
    if (!c->head) {
        pthread_mutex_unlock(&g_rt_mu);
        return def;
    }
    hl_msg* m = hl_chan_dequeue(c);
    int64_t v = m->v.i;
    free(m);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}
static double hl_chan_recv_or_f64(hl_chan* c, double def) {
    pthread_mutex_lock(&g_rt_mu);
    if (!c->head) {
        pthread_mutex_unlock(&g_rt_mu);
        return def;
    }
    hl_msg* m = hl_chan_dequeue(c);
    double v = m->v.f;
    free(m);
    pthread_mutex_unlock(&g_rt_mu);
    return v;
}

static int64_t hl_chan_len(hl_chan* c) {
    pthread_mutex_lock(&g_rt_mu);
    int64_t n = c->count;
    pthread_mutex_unlock(&g_rt_mu);
    return n;
}

// select(chs) — block until any channel has a pending message;
// return the index (list order) of the first ready one. The list
// holds raw hl_chan* items (pointer element lists are unboxed).
// v0.29.0-alpha: while waiting, the waiter count is bumped on ALL
// listed channels so the deadlock scan sees this thread as a
// potential consumer of any of them.
static int64_t hl_chan_select(hl_list* chs) {
    pthread_mutex_lock(&g_rt_mu);
    if (chs->len == 0) {
        pthread_mutex_unlock(&g_rt_mu);
        hl_die("select() on empty channel list");
    }
    while (1) {
        for (int64_t i = 0; i < chs->len; i++) {
            hl_chan* c = (hl_chan*)chs->items[i];
            if (c->head) {
                pthread_mutex_unlock(&g_rt_mu);
                return i;
            }
        }
        for (int64_t i = 0; i < chs->len; i++)
            ((hl_chan*)chs->items[i])->waiters++;
        g_rt_blocked++;
        hl_rt_deadlock_check();
        pthread_cond_wait(&g_rt_cv, &g_rt_mu);
        g_rt_blocked--;
        for (int64_t i = 0; i < chs->len; i++)
            ((hl_chan*)chs->items[i])->waiters--;
    }
}

// ---- tasks ----
static void hl_task_finish(hl_task* t, hl_task_res res) {
    pthread_mutex_lock(&g_rt_mu);
    t->res = res;
    t->done = true;
    g_rt_tasks--;
    g_rt_done_unjoined++;   // Stage 33: a join waiter can now proceed
    if (t->refcnt == 0 && !t->freed) { t->freed = true; free(t); }  // abandoned
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
}

// Typed finish wrappers (called by the generated trampolines).
static void hl_task_finish_i64(hl_task* t, int64_t v) {
    hl_task_res r; r.i = v; hl_task_finish(t, r);
}
static void hl_task_finish_f64(hl_task* t, double v) {
    hl_task_res r; r.f = v; hl_task_finish(t, r);
}
static void hl_task_finish_ptr(hl_task* t, void* v) {
    hl_task_res r; r.p = v; hl_task_finish(t, r);
}

static void* hl_spawn_entry(void* pv) {
    hl_spawn_ctx* c = (hl_spawn_ctx*)pv;
    void (*body)(void*, hl_task*) = c->body;
    void* argbox = c->argbox;
    hl_task* t = c->task;
    free(c);
    body(argbox, t);
    return NULL;
}

#define HL_TASK_STACK_BYTES  (1024 * 1024)   /* 1 MiB usable, deterministic */
#define HL_TASK_GUARD_BYTES  4096              /* one PROT_NONE guard page */

static int hl_thread_start(pthread_t* th, void* (*fn)(void*), void* arg) {
    pthread_attr_t at;
    if (pthread_attr_init(&at) != 0) {
        /* No attr support: fall back to the default stack. */
        return pthread_create(th, NULL, fn, arg);
    }
    pthread_attr_setstacksize(&at, HL_TASK_STACK_BYTES);
    pthread_attr_setguardsize(&at, HL_TASK_GUARD_BYTES);
    int rc = pthread_create(th, &at, fn, arg);
    pthread_attr_destroy(&at);
    return rc;
}

static hl_task* hl_spawn(void (*body)(void*, hl_task*), void* argbox) {
    hl_task* t = (hl_task*)malloc(sizeof(hl_task));
    if (!t) hl_die("out of memory");
    t->refcnt = 1;
    t->done = false;
    t->joined = false;
    t->freed = false;
    t->res.p = NULL;
    hl_spawn_ctx* c = (hl_spawn_ctx*)malloc(sizeof(hl_spawn_ctx));
    if (!c) hl_die("out of memory");
    c->body = body;
    c->argbox = argbox;
    c->task = t;
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks++;   // counted BEFORE the thread starts: no deadlock false-positive window
    pthread_mutex_unlock(&g_rt_mu);
    if (hl_thread_start(&t->th, hl_spawn_entry, c) != 0) {
        pthread_mutex_lock(&g_rt_mu);
        g_rt_tasks--;
        pthread_mutex_unlock(&g_rt_mu);
        free(c);
        free(t);
        hl_die("spawn: cannot create thread");
    }
    return t;
}

static void* hl_async_spawn_entry(void* pv) {
    void** box = (void**)pv;
    void (*body)(void*) = (void(*)(void*))box[0];
    void* argbox = box[1];
    free(box);
    body(argbox);
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks--;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return NULL;
}

static void hl_async_spawn(void (*body)(void*), void* argbox) {
    void** box = (void**)malloc(2 * sizeof(void*));
    if (!box) hl_die("out of memory");
    box[0] = (void*)body;
    box[1] = argbox;
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks++;
    pthread_mutex_unlock(&g_rt_mu);
    pthread_t th;
    if (hl_thread_start(&th, hl_async_spawn_entry, box) != 0) {
        pthread_mutex_lock(&g_rt_mu);
        g_rt_tasks--;
        pthread_mutex_unlock(&g_rt_mu);
        free(box);
        hl_die("async_spawn: cannot create thread");
    }
    pthread_detach(th);
}

typedef struct { void (*body)(hl_chan*, hl_chan*); hl_chan* in_s; hl_chan* out_s; } hl_stream_comb_ctx;
static void* hl_async_spawn_stream_entry(void* pv) {
    hl_stream_comb_ctx* c = (hl_stream_comb_ctx*)pv;
    void (*body)(hl_chan*, hl_chan*) = c->body;
    hl_chan* in_s = c->in_s;
    hl_chan* out_s = c->out_s;
    free(c);
    body(in_s, out_s);
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks--;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return NULL;
}

static void hl_async_spawn_stream(void (*body)(hl_chan*, hl_chan*), hl_chan* in_s, hl_chan* out_s) {
    hl_stream_comb_ctx* c = (hl_stream_comb_ctx*)malloc(sizeof(hl_stream_comb_ctx));
    if (!c) hl_die("out of memory");
    c->body = body; c->in_s = in_s; c->out_s = out_s;
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks++;
    pthread_mutex_unlock(&g_rt_mu);
    pthread_t th;
    if (hl_thread_start(&th, hl_async_spawn_stream_entry, c) != 0) {
        pthread_mutex_lock(&g_rt_mu);
        g_rt_tasks--;
        pthread_mutex_unlock(&g_rt_mu);
        free(c);
        hl_die("stream combinator: cannot create thread");
    }
    pthread_detach(th);
}

typedef struct { void (*body)(hl_chan*, hl_chan*, int64_t); hl_chan* in_s; hl_chan* out_s; int64_t n; } hl_stream_take_ctx;
static void* hl_async_spawn_take_entry(void* pv) {
    hl_stream_take_ctx* c = (hl_stream_take_ctx*)pv;
    void (*body)(hl_chan*, hl_chan*, int64_t) = c->body;
    hl_chan* in_s = c->in_s;
    hl_chan* out_s = c->out_s;
    int64_t n = c->n;
    free(c);
    body(in_s, out_s, n);
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks--;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return NULL;
}

static void hl_async_spawn_take(void (*body)(hl_chan*, hl_chan*, int64_t), hl_chan* in_s, hl_chan* out_s, int64_t n) {
    hl_stream_take_ctx* c = (hl_stream_take_ctx*)malloc(sizeof(hl_stream_take_ctx));
    if (!c) hl_die("out of memory");
    c->body = body; c->in_s = in_s; c->out_s = out_s; c->n = n;
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks++;
    pthread_mutex_unlock(&g_rt_mu);
    pthread_t th;
    if (hl_thread_start(&th, hl_async_spawn_take_entry, c) != 0) {
        pthread_mutex_lock(&g_rt_mu);
        g_rt_tasks--;
        pthread_mutex_unlock(&g_rt_mu);
        free(c);
        hl_die("stream_take: cannot create thread");
    }
    pthread_detach(th);
}

typedef struct { void (*body)(hl_chan*, hl_chan*, hl_chan*); hl_chan* a; hl_chan* b; hl_chan* out_s; } hl_stream_merge_ctx;
static void* hl_async_spawn_merge_entry(void* pv) {
    hl_stream_merge_ctx* c = (hl_stream_merge_ctx*)pv;
    void (*body)(hl_chan*, hl_chan*, hl_chan*) = c->body;
    hl_chan* a = c->a;
    hl_chan* b = c->b;
    hl_chan* out_s = c->out_s;
    free(c);
    body(a, b, out_s);
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks--;
    pthread_cond_broadcast(&g_rt_cv);
    pthread_mutex_unlock(&g_rt_mu);
    return NULL;
}

static void hl_async_spawn_merge(void (*body)(hl_chan*, hl_chan*, hl_chan*), hl_chan* a, hl_chan* b, hl_chan* out_s) {
    hl_stream_merge_ctx* c = (hl_stream_merge_ctx*)malloc(sizeof(hl_stream_merge_ctx));
    if (!c) hl_die("out of memory");
    c->body = body; c->a = a; c->b = b; c->out_s = out_s;
    pthread_mutex_lock(&g_rt_mu);
    g_rt_tasks++;
    pthread_mutex_unlock(&g_rt_mu);
    pthread_t th;
    if (hl_thread_start(&th, hl_async_spawn_merge_entry, c) != 0) {
        pthread_mutex_lock(&g_rt_mu);
        g_rt_tasks--;
        pthread_mutex_unlock(&g_rt_mu);
        free(c);
        hl_die("stream_merge: cannot create thread");
    }
    pthread_detach(th);
}

#ifndef INT64_MIN
#define INT64_MIN (-9223372036854775807LL - 1)
#endif

static void hl_task_join_wait(hl_task* t) {
    pthread_mutex_lock(&g_rt_mu);
    if (t->joined) {
        pthread_mutex_unlock(&g_rt_mu);
        hl_die("task already joined");
    }
    while (!t->done) {
        g_rt_blocked++;
        g_rt_join_waiters++;   // deep-scan-20: deadlock_check keys off this
        hl_rt_deadlock_check();
        pthread_cond_wait(&g_rt_cv, &g_rt_mu);
        g_rt_blocked--;
        g_rt_join_waiters--;
    }
    t->joined = true;
    g_rt_done_unjoined--;   // Stage 33: this task is now joined
    pthread_mutex_unlock(&g_rt_mu);
}

static int64_t hl_task_join_i64(hl_task* t) {
    hl_task_join_wait(t);
    return t->res.i;
}
static double hl_task_join_f64(hl_task* t) {
    hl_task_join_wait(t);
    return t->res.f;
}
static void* hl_task_join_ptr(hl_task* t) {
    hl_task_join_wait(t);
    return t->res.p;
}
static void hl_task_join_void(hl_task* t) {
    hl_task_join_wait(t);
}

// Task release — called by the spawner's binding cleanup. Under the
// global mutex, so task refcounts need no atomics. If the thread is
// still running when the last reference drops, the task is
// abandoned: hl_task_finish frees it.
static void hl_task_release(void* pv) {
    hl_task* t = (hl_task*)pv;
    if (!t) return;
    pthread_mutex_lock(&g_rt_mu);
    if (--t->refcnt == 0) {
        if (t->done && !t->freed) { t->freed = true; free(t); }
    }
    pthread_mutex_unlock(&g_rt_mu);
}
static void hl_cleanup_task(hl_task** p) { hl_task_release(*p); }

static hl_str* hl_str_alloc(int64_t len) {
    // Deep-scan fix (C11): reject negative len before the cast to
    // size_t. A negative len would wrap to ~2^64 via the cast,
    // causing malloc to fail (DoS) or — on systems with a
    // permissive overcommit — succeed with a huge buffer.
    if (len < 0) hl_die("hl_str_alloc: negative length");
    hl_str* s = (hl_str*)malloc(sizeof(hl_str));
    if (!s) hl_die("out of memory");
    s->refcnt = 1;
    s->len = len;
    s->data = (char*)malloc((size_t)len + 1);
    if (!s->data) hl_die("out of memory");
    s->data[len] = 0;
    return s;
}

static void hl_str_release(void* pv) {
    hl_str* s = (hl_str*)pv;
    if (!s) return;
    if (--s->refcnt == 0) { free(s->data); free(s); }
}
static void hl_cleanup_str(hl_str** p) { hl_str_release(*p); }

static hl_str* hl_str_from(const char* c, int64_t len) {
    hl_str* s = hl_str_alloc(len);
    if (len > 0) memcpy(s->data, c, (size_t)len);
    return s;
}

static hl_str* hl_str_concat(hl_str* a, hl_str* b) {
    hl_str* s = hl_str_alloc(a->len + b->len);
    if (a->len > 0) memcpy(s->data, a->data, (size_t)a->len);
    if (b->len > 0) memcpy(s->data + a->len, b->data, (size_t)b->len);
    return s;
}

static hl_str* hl_str_join(hl_list* parts, hl_str* sep) {
    int64_t n = parts->len;
    int64_t total = 0;
    for (int64_t i = 0; i < n; i++) {
        hl_str* p = (hl_str*)parts->items[i];
        total += p->len;
    }
    if (n > 1) total += (n - 1) * sep->len;
    hl_str* s = hl_str_alloc(total);
    int64_t off = 0;
    for (int64_t i = 0; i < n; i++) {
        if (i > 0 && sep->len > 0) {
            memcpy(s->data + off, sep->data, (size_t)sep->len);
            off += sep->len;
        }
        hl_str* p = (hl_str*)parts->items[i];
        if (p->len > 0) memcpy(s->data + off, p->data, (size_t)p->len);
        off += p->len;
    }
    return s;
}

static bool hl_str_eq(hl_str* a, hl_str* b) {
    return a->len == b->len && (a->len == 0 || memcmp(a->data, b->data, (size_t)a->len) == 0);
}

static int64_t hl_clz(uint64_t x) {
    return x == 0 ? 64 : (int64_t)__builtin_clzll(x);
}

static int64_t hl_ctz(uint64_t x) {
    return x == 0 ? 64 : (int64_t)__builtin_ctzll(x);
}

static int64_t hl_str_cmp(hl_str* a, hl_str* b) {
    int64_t n = a->len < b->len ? a->len : b->len;
    if (n > 0) {
        int r = memcmp(a->data, b->data, (size_t)n);
        if (r != 0) return r < 0 ? -1 : 1;
    }
    if (a->len == b->len) return 0;
    return a->len < b->len ? -1 : 1;
}

static int64_t hl_str_len(hl_str* s) { return s->len; }

static int64_t hl_str_byte_at(hl_str* s, int64_t i) {
    if (i < 0 || i >= s->len) hl_die("string access out of bounds");
    return (unsigned char)s->data[i];
}

static int64_t hl_str_byte_at_unchecked(hl_str* s, int64_t i) {
    return (unsigned char)s->data[i];
}

static hl_str* hl_str_slice(hl_str* s, int64_t a, int64_t b) {
    if (a < 0 || b < a || b > s->len) hl_die("invalid string slice");
    return hl_str_from(s->data + a, b - a);
}

static hl_str* hl_str_slice_unchecked(hl_str* s, int64_t a, int64_t b) {
    return hl_str_from(s->data + a, b - a);
}

static int64_t hl_str_find(hl_str* s, hl_str* sub) {
    if (sub->len == 0) return 0;
    if (sub->len > s->len) return -1;
    for (int64_t i = 0; i + sub->len <= s->len; i++) {
        if (memcmp(s->data + i, sub->data, (size_t)sub->len) == 0) return i;
    }
    return -1;
}

static bool hl_str_contains(hl_str* s, hl_str* sub) { return hl_str_find(s, sub) >= 0; }

static bool hl_str_starts_with(hl_str* s, hl_str* p) {
    return s->len >= p->len && (p->len == 0 || memcmp(s->data, p->data, (size_t)p->len) == 0);
}

static bool hl_str_ends_with(hl_str* s, hl_str* p) {
    return s->len >= p->len && (p->len == 0 || memcmp(s->data + s->len - p->len, p->data, (size_t)p->len) == 0);
}

static hl_str* hl_str_trim(hl_str* s) {
    int64_t a = 0, b = s->len;
    while (a < b && (unsigned char)s->data[a] <= 0x20) a++;
    while (b > a && (unsigned char)s->data[b - 1] <= 0x20) b--;
    return hl_str_from(s->data + a, b - a);
}

static int64_t hl_str_to_int(hl_str* s) {
    int64_t i = 0;
    uint64_t uv = 0;
    bool neg = false;
    if (s->len == 0) hl_die("cannot convert string to int");
    if (s->data[0] == '-') { neg = true; i = 1; }
    if (i >= s->len) hl_die("cannot convert string to int");
    for (; i < s->len; i++) {
        char c = s->data[i];
        if (c < '0' || c > '9') hl_die("cannot convert string to int");
        if (uv > (UINT64_C(9223372036854775808) - (uint64_t)(c - '0')) / 10) {
            hl_die("integer too large when converting string");
        }
        uv = uv * 10 + (uint64_t)(c - '0');
    }
    if (neg) {
        if (uv > UINT64_C(9223372036854775808)) hl_die("integer too large when converting string");
        return (int64_t)(-(int64_t)(uv - 1) - 1);
    }
    if (uv > (uint64_t)INT64_MAX) hl_die("integer too large when converting string");
    return (int64_t)uv;
}

static hl_str* hl_str_from_int64(int64_t v) {
    char buf[32];
    int n = snprintf(buf, sizeof buf, "%" PRId64, v);
    if (n < 0) { return hl_str_from("", 0); }
    if (n > (int)(sizeof buf) - 1) { n = (int)(sizeof buf) - 1; }
    return hl_str_from(buf, (int64_t)n);
}

static hl_str* hl_str_from_double(double v) {
    char buf[512];
    int n = snprintf(buf, sizeof buf, "%.6f", v);
    if (n < 0) { return hl_str_from("", 0); }
    if (n > (int)(sizeof buf) - 1) { n = (int)(sizeof buf) - 1; }
    return hl_str_from(buf, (int64_t)n);
}

static hl_str* hl_cstr(const char* c) { return hl_str_from(c, (int64_t)strlen(c)); }
static hl_str* hl_str_from_bool(bool v) {
    return v ? hl_str_from("true", 4) : hl_str_from("false", 5);
}

// Dynamic list (boxed values), insertion-ordered map[str,T] hash table,
// checked int64 arithmetic, and I/O
static void* hl_box_i64(int64_t v) {
    int64_t* p = (int64_t*)malloc(sizeof(int64_t));
    if (!p) hl_die("out of memory");
    *p = v;
    return p;
}
static int64_t hl_unbox_i64(void* p) { return *(int64_t*)p; }

static void* hl_box_f64(double v) {
    double* p = (double*)malloc(sizeof(double));
    if (!p) hl_die("out of memory");
    *p = v;
    return p;
}
static double hl_unbox_f64(void* p) { return *(double*)p; }

static void* hl_box_bool(bool v) {
    bool* p = (bool*)malloc(sizeof(bool));
    if (!p) hl_die("out of memory");
    *p = v;
    return p;
}
static bool hl_unbox_bool(void* p) { return *(bool*)p; }

static void* hl_box_ptr(void* p) { return p; }
static void* hl_unbox_ptr(void* p) { return p; }

// hl_list_new: elem_free describes how to release one element.
// free       -> primitive boxes;  hl_str_release -> str;
// hl_list_release / hl_map_release / hl_release_<T> -> containers/user types.
// NULL = arena mode (never release elements — LLVM backend).
static hl_list* hl_list_new(void (*elem_free)(void*)) {
    hl_list* l = (hl_list*)malloc(sizeof(hl_list));
    if (!l) hl_die("out of memory");
    l->refcnt = 1;
    l->len = 0;
    l->cap = 8;
    l->elem_free = elem_free;
    l->items = (void**)malloc((size_t)l->cap * sizeof(void*));
    if (!l->items) hl_die("out of memory");
    return l;
}

static void hl_list_release(void* pl) {
    hl_list* l = (hl_list*)pl;
    if (!l) return;
    if (--l->refcnt == 0) {
        if (l->elem_free) {
            for (int64_t i = 0; i < l->len; i++) l->elem_free(l->items[i]);
        }
        free(l->items);
        free(l);
    }
}
static void hl_cleanup_list(hl_list** p) { hl_list_release(*p); }

static void hl_list_push(hl_list* l, void* v) {
    if (l->len == l->cap) {
        size_t new_cap = l->cap * 2;
        // Deep-scan fix (CC7): realloc-on-failure leaks the original
        // buffer. Use a temp so the original is still freeable; the
        // old code reassigned l->items to NULL on failure, losing
        // the only reference to the original allocation (the leak
        // was process-terminal because hl_die exits, but ASan /
        // Valgrind would flag it; this fix is correctness hygiene).
        void** nb = (void**)realloc(l->items, new_cap * sizeof(void*));
        if (!nb) hl_die("out of memory");
        l->items = nb;
        l->cap = new_cap;
    }
    l->items[l->len] = v;
    l->len++;
}

static int64_t hl_list_len(hl_list* l) { return l->len; }

static void* hl_list_get(hl_list* l, int64_t i, int64_t line) {
    if (i < 0 || i >= l->len) hl_die_line("array access out of bounds", line);
    return l->items[i];
}

static void* hl_list_get_unchecked(hl_list* l, int64_t i) {
    return l->items[i];
}

// hl_list_set: v arrives OWNED (the caller transferred one retain).
// Store first, then release the old item so self-assignment is safe.
static void hl_list_set(hl_list* l, int64_t i, void* v, int64_t line) {
    if (i < 0 || i >= l->len) hl_die_line("array access out of bounds", line);
    void* old = l->items[i];
    l->items[i] = v;
    if (l->elem_free) l->elem_free(old);
}

// Deep-scan-20: forward declaration — hl_range (below) panics on
// oversized ranges but hl_panic is defined further down the runtime.
static void hl_panic(hl_str* msg);
static void hl_panic_at(hl_str* msg, int64_t line);
static hl_list* hl_range(int64_t a, int64_t b) {
    // Deep-scan-20 fix (boot/native parity): the interpreter caps
    // range() at 1,000,000 elements (deep-scan-7, clean panic)
    // but the native runtime happily built the full list —
    // range(0, 1500000) ran natively and exited 101 under boot.
    // Mirror the cap so both backends agree.
    int64_t count = b > a ? b - a : 0;
    if (count > 1000000) {
        char buf[192];
        snprintf(buf, sizeof(buf), "range(%lld, %lld) would produce %lld elements (limit 1000000) - use an explicit counter loop for large ranges",
                 (long long)a, (long long)b, (long long)count);
        hl_panic(hl_str_from(buf, (int64_t)strlen(buf)));
    }
    hl_list* l = hl_list_new(free);
    for (int64_t i = a; i < b; i++) hl_list_push(l, hl_box_i64(i));
    return l;
}

// ---- map[str, T]: linear-probing hash table + insertion-order array ----
static uint64_t hl_str_hash(hl_str* s) {
    uint64_t h = 1469598103934665603ULL;
    for (int64_t i = 0; i < s->len; i++) {
        h ^= (uint8_t)s->data[i];
        h *= 1099511628211ULL;
    }
    return h;
}

// hl_map_new: val_free describes how to release one value. The map
// owns one retain per key and one retain (or box) per value.
static hl_map* hl_map_new(void (*val_free)(void*)) {
    hl_map* m = (hl_map*)malloc(sizeof(hl_map));
    if (!m) hl_die("out of memory");
    m->refcnt = 1;
    m->len = 0;
    m->cap = 16;
    m->slots = (hl_str**)calloc((size_t)m->cap, sizeof(hl_str*));
    m->vals = (void**)malloc((size_t)m->cap * sizeof(void*));
    m->order = (hl_str**)malloc((size_t)m->cap * sizeof(hl_str*));
    m->val_free = val_free;
    if (!m->slots || !m->vals || !m->order) hl_die("out of memory");
    return m;
}

static void hl_map_release(void* pm) {
    hl_map* m = (hl_map*)pm;
    if (!m) return;
    if (--m->refcnt == 0) {
        for (int64_t i = 0; i < m->cap; i++) {
            if (m->slots[i] != NULL) {
                if (m->val_free) m->val_free(m->vals[i]);
                hl_str_release(m->slots[i]);
            }
        }
        free(m->slots);
        free(m->vals);
        free(m->order);
        free(m);
    }
}
static void hl_cleanup_map(hl_map** p) { hl_map_release(*p); }

static void hl_map_grow(hl_map* m, int64_t ncap) {
    hl_str** nslots = (hl_str**)calloc((size_t)ncap, sizeof(hl_str*));
    void** nvals = (void**)malloc((size_t)ncap * sizeof(void*));
    hl_str** norder = (hl_str**)malloc((size_t)ncap * sizeof(hl_str*));
    if (!nslots || !nvals || !norder) hl_die("out of memory");
    for (int64_t i = 0; i < m->cap; i++) {
        if (m->slots[i] != NULL) {
            uint64_t idx = hl_str_hash(m->slots[i]) & (uint64_t)(ncap - 1);
            while (nslots[idx] != NULL) idx = (idx + 1) & (uint64_t)(ncap - 1);
            nslots[idx] = m->slots[i];
            nvals[idx] = m->vals[i];
        }
    }
    for (int64_t j = 0; j < m->len; j++) norder[j] = m->order[j];
    free(m->slots);
    free(m->vals);
    free(m->order);
    m->slots = nslots;
    m->vals = nvals;
    m->order = norder;
    m->cap = ncap;
}

// hl_map_set: k and v arrive OWNED (the caller transferred one retain
// of each). On overwrite the incoming key is released and the old
// value is released. Store-then-release keeps self-assignment safe.
static void hl_map_set(hl_map* m, hl_str* k, void* v) {
    if ((m->len + 1) * 10 >= m->cap * 7) {
        hl_map_grow(m, m->cap * 2);
    }
    uint64_t idx = hl_str_hash(k) & (uint64_t)(m->cap - 1);
    while (m->slots[idx] != NULL) {
        if (hl_str_eq(m->slots[idx], k)) {
            void* oldv = m->vals[idx];
            m->vals[idx] = v;
            if (m->val_free) m->val_free(oldv);
            hl_str_release(k);
            return;
        }
        idx = (idx + 1) & (uint64_t)(m->cap - 1);
    }
    m->slots[idx] = k;
    m->vals[idx] = v;
    m->order[m->len] = k;
    m->len++;
}

// hl_map_borrow: raw lookup — returns the stored slot value (a box for
// primitive-valued maps, the value itself for pointer-valued maps) or
// NULL when the key is missing. The map keeps ownership.
static void* hl_map_borrow(hl_map* m, hl_str* k) {
    uint64_t idx = hl_str_hash(k) & (uint64_t)(m->cap - 1);
    while (m->slots[idx] != NULL) {
        if (hl_str_eq(m->slots[idx], k)) return m->vals[idx];
        idx = (idx + 1) & (uint64_t)(m->cap - 1);
    }
    return NULL;
}

// Typed getters for primitive-valued maps: the default arrives by
// value — no boxing, no allocation, no refcount traffic.
static int64_t hl_map_get_i64(hl_map* m, hl_str* k, int64_t dflt) {
    void* v = hl_map_borrow(m, k);
    if (v == NULL) return dflt;
    return hl_unbox_i64(v);
}
static double hl_map_get_f64(hl_map* m, hl_str* k, double dflt) {
    void* v = hl_map_borrow(m, k);
    if (v == NULL) return dflt;
    return hl_unbox_f64(v);
}
static bool hl_map_get_bool(hl_map* m, hl_str* k, bool dflt) {
    void* v = hl_map_borrow(m, k);
    if (v == NULL) return dflt;
    return hl_unbox_bool(v);
}

// hl_map_get_own: for pointer-valued maps. dflt arrives OWNED (+1)
// and the result is returned OWNED (+1).
static void* hl_map_get_own(hl_map* m, hl_str* k, void* dflt) {
    void* v = hl_map_borrow(m, k);
    if (v != NULL) {
        hl_retain(v);
        if (m->val_free) m->val_free(dflt);
        return v;
    }
    return dflt;
}

static bool hl_map_has(hl_map* m, hl_str* k) { return hl_map_borrow(m, k) != NULL; }

static int64_t hl_map_len(hl_map* m) { return m->len; }

// hl_map_keys: fresh list[str]; each key is retained for the new list.
static hl_list* hl_map_keys(hl_map* m) {
    hl_list* r = hl_list_new(hl_str_release);
    for (int64_t i = 0; i < m->len; i++) hl_list_push(r, hl_retain(m->order[i]));
    return r;
}

// ---- checked int64 arithmetic ----
static int64_t hl_add_i64(int64_t a, int64_t b, int64_t line) {
    int64_t r;
    if (__builtin_add_overflow(a, b, &r)) hl_die_line("integer overflow", line);
    return r;
}
static int64_t hl_sub_i64(int64_t a, int64_t b, int64_t line) {
    int64_t r;
    if (__builtin_sub_overflow(a, b, &r)) hl_die_line("integer overflow", line);
    return r;
}
static int64_t hl_mul_i64(int64_t a, int64_t b, int64_t line) {
    int64_t r;
    if (__builtin_mul_overflow(a, b, &r)) hl_die_line("integer overflow", line);
    return r;
}
static int64_t hl_neg_i64(int64_t a, int64_t line) {
    if (a == INT64_MIN) hl_die_line("integer overflow", line);
    return -a;
}
static int64_t hl_abs_i64(int64_t a, int64_t line) {
    if (a == INT64_MIN) hl_die_line("integer overflow", line);
    return a < 0 ? -a : a;
}
static int64_t hl_div_i64(int64_t a, int64_t b, int64_t line) {
    if (b == 0) hl_die_line("division by zero", line);
    if (a == INT64_MIN && b == -1) hl_die_line("integer overflow", line);
    return a / b;
}
static int64_t hl_mod_i64(int64_t a, int64_t b, int64_t line) {
    if (b == 0) hl_die_line("division by zero", line);
    if (a == INT64_MIN && b == -1) hl_die_line("integer overflow", line);
    return a % b;
}

// ---- I/O (print-family builtins CONSUME their str argument) ----
static hl_list* g_hl_args = NULL;

static void hl_init_args(int argc, char** argv) {
    g_hl_args = hl_list_new(hl_str_release);
    for (int i = 0; i < argc; i++) {
        hl_list_push(g_hl_args, hl_str_from(argv[i], (int64_t)strlen(argv[i])));
    }
}

static hl_list* hl_args(void) { return g_hl_args; }

static void hl_print(hl_str* s) {
    fwrite(s->data, 1, (size_t)s->len, stdout);
    hl_str_release(s);
}

static void hl_println(hl_str* s) {
    fwrite(s->data, 1, (size_t)s->len, stdout);
    fputc('\n', stdout);
    hl_str_release(s);
}

// Stage 56 (v0.75.0-alpha): hl_eprint / hl_eprintln — write to
// stderr, consuming the str argument (same convention as
// hl_print / hl_println). fflush(stdout) first so interleaved
// stdout/stderr output keeps the caller's logical order in a
// combined capture (stdout is block-buffered when redirected).
static void hl_eprint(hl_str* s) {
    fflush(stdout);
    fwrite(s->data, 1, (size_t)s->len, stderr);
    hl_str_release(s);
}

static void hl_eprintln(hl_str* s) {
    fflush(stdout);
    fwrite(s->data, 1, (size_t)s->len, stderr);
    fputc('\n', stderr);
    hl_str_release(s);
}

// Stage 56 (v0.75.0-alpha): hl_isatty — true when fd refers to a
// terminal. isatty() is declared in <unistd.h> (already included).
// Invalid / negative fds simply return false (isatty sets EBADF
// and returns 0 — no panic, no UB), matching os.isatty in the
// Stage-0 interpreter byte-for-byte.
static bool hl_isatty(int64_t fd) {
    return isatty((int)fd);
}

// Stage 57 (v0.76.0-alpha): hl_proc_pid — the OS process id
// (the syslog TAG[PID] field). getpid never fails on POSIX.
static int64_t hl_proc_pid(void) {
    return (int64_t)getpid();
}

// Stage 57 (v0.76.0-alpha): hl_sys_hostname — the host name (the
// syslog HOSTNAME field). Returns a fresh str; "localhost" on
// any gethostname failure (kept total — no panic path).
static hl_str* hl_sys_hostname(void) {
    char buf[256];
    if (gethostname(buf, sizeof(buf) - 1) != 0) {
        return hl_str_from("localhost", 9);
    }
    buf[sizeof(buf) - 1] = '\0';
    size_t n = strlen(buf);
    return hl_str_from(buf, (int64_t)n);
}

// hl_read_file: consumes the path, returns a fresh str. The temporary
// read buffer is freed before returning (it used to leak under the
// arena model).
static hl_str* hl_read_file(hl_str* path) {
    hl_sandbox_check(path->data);
    FILE* f = fopen(path->data, "rb");
    if (!f) hl_die("cannot open file");
    // Virtual files (/proc, /sys) report size 0 via fseek/ftell,
    // so read incrementally until EOF instead of trusting the
    // size (BUG: the interpreter read them fine while the native
    // binary got empty output — a differential divergence).
    size_t cap = 4096, len = 0;
    char* buf = (char*)malloc(cap);
    if (!buf) hl_die("out of memory");
    for (;;) {
        if (len == cap) {
            size_t new_cap = cap * 2;
            // Deep-scan fix (C10): realloc-on-failure leaks the
            // original buffer. Use a temp so the original is
            // still freeable on OOM.
            char* nb = (char*)realloc(buf, new_cap);
            if (!nb) { free(buf); hl_die("out of memory"); }
            buf = nb;
            cap = new_cap;
        }
        size_t n = fread(buf + len, 1, cap - len, f);
        len += n;
        if (n == 0) break;
    }
    fclose(f);
    hl_str* out = hl_str_from(buf, (int64_t)len);
    free(buf);
    hl_str_release(path);
    return out;
}

// Stage 10 release: hl_read_line() — read one line from stdin.
// Strips a trailing newline (and CRLF if present). Returns a fresh
// hl_str* (refcount 1) owned by the caller. At EOF, returns an
// empty string (mirrors fgets semantics). The Stage-0 interpreter
// strips CRLF the same way so differential testing stays green.
static hl_str* hl_read_line(void) {
    size_t cap = 128, len = 0;
    char* buf = (char*)malloc(cap);
    if (!buf) hl_die("out of memory");
    for (;;) {
        int c = getchar();
        if (c == EOF) break;
        if (len + 1 >= cap) {
            cap *= 2;
            char* nb = (char*)realloc(buf, cap);
            if (!nb) { free(buf); hl_die("out of memory"); }
            buf = nb;
        }
        buf[len++] = (char)c;
        if (c == '\n') break;
    }
    // Strip trailing \n and \r\n.
    if (len > 0 && buf[len - 1] == '\n') {
        len--;
        if (len > 0 && buf[len - 1] == '\r') len--;
    }
    hl_str* out = hl_str_from(buf, (int64_t)len);
    free(buf);
    return out;
}

// hl_write_file: consumes the path and the content.
static void hl_write_file(hl_str* path, hl_str* content) {
    hl_sandbox_check(path->data);
    FILE* f = fopen(path->data, "wb");
    if (!f) hl_die("cannot write file");
    if (content->len > 0 && fwrite(content->data, 1, (size_t)content->len, f) != (size_t)content->len) {
        hl_die("cannot write file");
    }
    if (fclose(f) != 0) hl_die("cannot write file");
    hl_str_release(content);
    hl_str_release(path);
}

static int64_t hl_clock_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000 + (int64_t)ts.tv_nsec / 1000000;
}

static void hl_thread_sleep_ms(int64_t ms) {
    if (ms < 0) hl_die("thread_sleep_ms: duration must be >= 0");
    if (ms == 0) {
        // Sleep(0) on POSIX: yield via sched_yield, not nanosleep(0).
        // nanosleep(0) is a no-op (returns immediately) which is
        // correct but less scheduler-friendly than sched_yield.
        sched_yield();
        return;
    }
    struct timespec req;
    req.tv_sec = ms / 1000;
    req.tv_nsec = (ms % 1000) * 1000000L;
    while (nanosleep(&req, &req) == -1 && errno == EINTR) {
        // Re-sleep the remainder after a signal interruption.
    }
}

static void hl_thread_yield(void) {
    sched_yield();
}

static int64_t hl_thread_current_id(void) {
    return (int64_t)pthread_self();
}

static void hl_panic(hl_str* msg) {
    hl_call_panic_hook(msg);
    fflush(stdout);
    fprintf(stderr, "panic: %s\n", msg->data);
    exit(101);
}


// The SOURCE-LOCATION panic. `hl_panic` reports the message
// alone, which is a real asymmetry: the interpreter knows the line
// a panic came from and prints `(at line N)`, so a native binary
// that dropped it disagreed with the interpreter on the very
// output the differential tests compare — and a panic without a
// line is much harder to act on. The format is byte-identical to
// the interpreter's, on purpose: parity is the invariant.
// hl_msg_has_loc: does the message already say WHERE it happened?
// The compiler's own diagnostics embed `(line N)` in the text, and
// the interpreter prints those bare. Annotating them again would
// print the line twice and break the byte-identical-diagnostic
// invariant the two front-ends are supposed to share.
static bool hl_msg_has_loc(const char* s) {
    size_t n = strlen(s);
    if (n == 0 || s[n - 1] != ')') return false;
    size_t i = n;
    while (i > 0 && s[i - 1] != '(') i--;
    if (i == 0) return false;
    i--; /* the loop stops with i one PAST the '(' */
    return (n - i) >= 7 && strncmp(s + i, "(line ", 6) == 0;
}

static void hl_panic_at(hl_str* msg, int64_t line) {
    hl_call_panic_hook(msg);
    fflush(stdout);
    if (line > 0 && !hl_msg_has_loc(msg->data)) {
        fprintf(stderr, "panic: %s (at line %lld)\n", msg->data, (long long)line);
    } else {
        fprintf(stderr, "panic: %s\n", msg->data);
    }
    exit(101);
}

static void hl_exit(int64_t code) {
    fflush(stdout);
    exit((int)code);
}

static uint64_t hl_rng_state = 1;  /* nonzero default */

static void hl_rand_seed(int64_t s) {
    hl_rng_state = (uint64_t)s;
    if (hl_rng_state == 0) hl_rng_state = 1;  /* avoid degenerate seq */
}

static uint64_t hl_rng_next(void) {
    hl_rng_state = hl_rng_state * 6364136223846793005ULL + 1442695040888963407ULL;
    return hl_rng_state;
}

static int64_t hl_rand_int(int64_t max) {
    if (max <= 0) hl_die("rand_int() requires a positive max");
    uint64_t r = hl_rng_next();
    return (int64_t)(r % (uint64_t)max);
}

static double hl_rand_float(void) {
    uint64_t r = hl_rng_next();
    return (double)(r >> 11) / (double)(1ULL << 53);
}

static hl_str* hl_net_lookup(hl_str* host) {
    struct addrinfo hints;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    struct addrinfo* res = NULL;
    int rc = getaddrinfo(host->data, NULL, &hints, &res);
    if (rc != 0 || res == NULL) {
        hl_str_release(host);
        hl_die("net_lookup: DNS resolution failed");
    }
    char addr_buf[INET_ADDRSTRLEN];
    const char* r = inet_ntop(AF_INET,
        &((struct sockaddr_in*)res->ai_addr)->sin_addr,
        addr_buf, sizeof(addr_buf));
    freeaddrinfo(res);
    if (!r) {
        hl_str_release(host);
        hl_die("net_lookup: inet_ntop failed");
    }
    hl_str* out = hl_str_from(addr_buf, (int64_t)strlen(addr_buf));
    hl_str_release(host);
    return out;
}

static int64_t hl_proc_exec(hl_str* cmd) {
    fflush(stdout);
    int rc = system(cmd->data);
    hl_str_release(cmd);
    if (rc == -1) {
        hl_die("proc_exec: system() failed");
    }
#ifdef WIFEXITED
    if (WIFEXITED(rc)) return (int64_t)WEXITSTATUS(rc);
    if (WIFSIGNALED(rc)) return (int64_t)(128 + WTERMSIG(rc));
#else
    return (int64_t)(rc & 0xFF);
#endif
    return (int64_t)(rc & 0xFF);
}

#define HL_PROC_MAX_CHILDREN 64
struct hl_proc_child {
    pid_t os_pid;          /* OS pid, 0 if slot free */
    int   stdin_fd;        /* parent write end; -1 if not piped */
    int   stdout_fd;       /* parent read end; -1 if not piped */
    int   stderr_fd;       /* parent read end; -1 if not piped */
    int   exited;          /* 1=exited (status valid), 0=alive */
    int   exit_status;     /* encoded: 0..255 / 128+signum */
};
static struct hl_proc_child hl_proc_children[HL_PROC_MAX_CHILDREN];

static int hl_proc_alloc_slot(void) {
    for (int i = 0; i < HL_PROC_MAX_CHILDREN; i++) {
        if (hl_proc_children[i].os_pid == 0) {
            return i + 1;  /* Halis pid = slot + 1 (>= 1) */
        }
    }
    return 0;  /* table full */
}

static int64_t hl_proc_spawn(hl_str* program, hl_list* args,
                            int64_t stdin_kind, int64_t stdout_kind,
                            int64_t stderr_kind) {
    if (stdin_kind < 0 || stdin_kind > 2 ||
        stdout_kind < 0 || stdout_kind > 2 ||
        stderr_kind < 0 || stderr_kind > 2) {
        hl_str_release(program);
        hl_list_release(args);
        hl_die("proc_spawn: stdio kind must be 0/1/2");
    }
    int slot = hl_proc_alloc_slot();
    if (slot == 0) {
        hl_str_release(program);
        hl_list_release(args);
        return -1;
    }
    int in_pipe[2] = {-1, -1};
    int out_pipe[2] = {-1, -1};
    int err_pipe[2] = {-1, -1};
    if (stdin_kind == 1 && pipe(in_pipe) < 0) {
        hl_str_release(program);
        hl_list_release(args);
        return -1;
    }
    if (stdout_kind == 1 && pipe(out_pipe) < 0) {
        if (in_pipe[0] != -1) close(in_pipe[0]);
        if (in_pipe[1] != -1) close(in_pipe[1]);
        hl_str_release(program);
        hl_list_release(args);
        return -1;
    }
    if (stderr_kind == 1 && pipe(err_pipe) < 0) {
        if (in_pipe[0] != -1) close(in_pipe[0]);
        if (in_pipe[1] != -1) close(in_pipe[1]);
        if (out_pipe[0] != -1) close(out_pipe[0]);
        if (out_pipe[1] != -1) close(out_pipe[1]);
        hl_str_release(program);
        hl_list_release(args);
        return -1;
    }
    fflush(stdout);
    pid_t pid = fork();
    if (pid < 0) {
        if (in_pipe[0] != -1) close(in_pipe[0]);
        if (in_pipe[1] != -1) close(in_pipe[1]);
        if (out_pipe[0] != -1) close(out_pipe[0]);
        if (out_pipe[1] != -1) close(out_pipe[1]);
        if (err_pipe[0] != -1) close(err_pipe[0]);
        if (err_pipe[1] != -1) close(err_pipe[1]);
        hl_str_release(program);
        hl_list_release(args);
        return -1;
    }
    if (pid == 0) {
        /* Child: dup2 the pipe ends onto the std fds, then exec. */
        if (stdin_kind == 1) {
            dup2(in_pipe[0], 0);
            close(in_pipe[1]);
        } else if (stdin_kind == 2) {
            int devnull = open("/dev/null", O_RDONLY);
            if (devnull >= 0) { dup2(devnull, 0); close(devnull); }
        }
        if (stdout_kind == 1) {
            dup2(out_pipe[1], 1);
            close(out_pipe[0]);
        } else if (stdout_kind == 2) {
            int devnull = open("/dev/null", O_WRONLY);
            if (devnull >= 0) { dup2(devnull, 1); close(devnull); }
        }
        if (stderr_kind == 1) {
            dup2(err_pipe[1], 2);
            close(err_pipe[0]);
        } else if (stderr_kind == 2) {
            int devnull = open("/dev/null", O_WRONLY);
            if (devnull >= 0) { dup2(devnull, 2); close(devnull); }
        }
        /* Close any other pipe fds the child shouldn't have. */
        if (stdin_kind == 1) close(in_pipe[0]);
        if (stdout_kind == 1) close(out_pipe[1]);
        if (stderr_kind == 1) close(err_pipe[1]);
        /* Build argv[] from program + args. */
        int64_t n = hl_list_len(args);
        char** argv = (char**)malloc(sizeof(char*) * (size_t)(n + 2));
        if (!argv) _exit(127);
        argv[0] = program->data;
        for (int64_t i = 0; i < n; i++) {
            hl_str* elem = (hl_str*)hl_list_get(args, i, 0);
            argv[i + 1] = elem ? elem->data : (char*)"";
        }
        argv[n + 1] = NULL;
        execvp(program->data, argv);
        /* execvp only returns on failure. */
        _exit(127);
    }
    /* Parent: close the child's ends of the pipes. */
    if (stdin_kind == 1) { close(in_pipe[0]); }
    if (stdout_kind == 1) { close(out_pipe[1]); }
    if (stderr_kind == 1) { close(err_pipe[1]); }
    struct hl_proc_child* c = &hl_proc_children[slot - 1];
    c->os_pid = pid;
    c->stdin_fd = (stdin_kind == 1) ? in_pipe[1] : -1;
    c->stdout_fd = (stdout_kind == 1) ? out_pipe[0] : -1;
    c->stderr_fd = (stderr_kind == 1) ? err_pipe[0] : -1;
    c->exited = 0;
    c->exit_status = 0;
    hl_str_release(program);
    hl_list_release(args);
    return (int64_t)slot;
}

static int64_t hl_proc_wait(int64_t hl_pid) {
    if (hl_pid < 1 || hl_pid > HL_PROC_MAX_CHILDREN) return -1;
    struct hl_proc_child* c = &hl_proc_children[hl_pid - 1];
    if (c->os_pid == 0) return -1;
    if (c->exited) return (int64_t)c->exit_status;
    /* Close any open write ends so the child sees EOF on stdin. */
    if (c->stdin_fd != -1) { close(c->stdin_fd); c->stdin_fd = -1; }
    int status = 0;
    if (waitpid(c->os_pid, &status, 0) < 0) {
        return -1;
    }
    int encoded;
#ifdef WIFEXITED
    if (WIFEXITED(status)) encoded = WEXITSTATUS(status);
    else if (WIFSIGNALED(status)) encoded = 128 + WTERMSIG(status);
    else encoded = -1;
#else
    encoded = status & 0xFF;
#endif
    c->exited = 1;
    c->exit_status = encoded;
    return (int64_t)encoded;
}

static int64_t hl_proc_kill(int64_t hl_pid) {
    if (hl_pid < 1 || hl_pid > HL_PROC_MAX_CHILDREN) return -1;
    struct hl_proc_child* c = &hl_proc_children[hl_pid - 1];
    if (c->os_pid == 0) return -1;
    if (c->exited) return 0;
    if (kill(c->os_pid, SIGTERM) < 0) {
        /* ESRCH = child already reaped. Treat as success. */
        if (errno == ESRCH) return 0;
        return -1;
    }
    return 0;
}

static int64_t hl_proc_child_write(int64_t hl_pid, hl_str* data) {
    if (hl_pid < 1 || hl_pid > HL_PROC_MAX_CHILDREN) {
        hl_str_release(data);
        return -1;
    }
    struct hl_proc_child* c = &hl_proc_children[hl_pid - 1];
    if (c->os_pid == 0 || c->stdin_fd == -1) {
        hl_str_release(data);
        return -1;
    }
    ssize_t n = write(c->stdin_fd, data->data, (size_t)data->len);
    hl_str_release(data);
    if (n < 0) return -1;
    return (int64_t)n;
}

static hl_str* hl_proc_child_read(int64_t hl_pid, int64_t fd_kind,
                                int64_t n) {
    if (hl_pid < 1 || hl_pid > HL_PROC_MAX_CHILDREN)
        return hl_str_from("", 0);
    struct hl_proc_child* c = &hl_proc_children[hl_pid - 1];
    if (c->os_pid == 0) return hl_str_from("", 0);
    int fd = -1;
    if (fd_kind == 1) fd = c->stdout_fd;
    else if (fd_kind == 2) fd = c->stderr_fd;
    else return hl_str_from("", 0);
    if (fd == -1) return hl_str_from("", 0);
    if (n < 0) n = 0;
    if (n > (64 * 1024 * 1024)) n = 64 * 1024 * 1024;  /* 64 MiB cap */
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf) return hl_str_from("", 0);
    ssize_t got = read(fd, buf, (size_t)n);
    if (got < 0) got = 0;
    hl_str* out = hl_str_from(buf, (int64_t)got);
    free(buf);
    return out;
}

static int64_t hl_proc_child_close(int64_t hl_pid, int64_t fd_kind) {
    if (hl_pid < 1 || hl_pid > HL_PROC_MAX_CHILDREN) return -1;
    struct hl_proc_child* c = &hl_proc_children[hl_pid - 1];
    if (c->os_pid == 0) return -1;
    if (fd_kind < 0 || fd_kind > 2) return -1;
    int* fd_ptr;
    if (fd_kind == 0) fd_ptr = &c->stdin_fd;
    else if (fd_kind == 1) fd_ptr = &c->stdout_fd;
    else fd_ptr = &c->stderr_fd;
    if (*fd_ptr == -1) return 0;  /* idempotent */
    if (close(*fd_ptr) < 0) {
        *fd_ptr = -1;
        return -1;
    }
    *fd_ptr = -1;
    return 0;
}

// hl_env_get(key) — read an env var. Returns a fresh str (the
// value, or "" if not found). Consumes the key.
static hl_str* hl_env_get(hl_str* key) {
    const char* v = getenv(key->data);
    hl_str* out;
    if (v == NULL) {
        out = hl_str_from("", 0);
    } else {
        size_t n = strlen(v);
        out = hl_str_from(v, (int64_t)n);
    }
    hl_str_release(key);
    return out;
}

// hl_env_has(key) — check if an env var exists. Consumes key.
static bool hl_env_has(hl_str* key) {
    bool found = (getenv(key->data) != NULL);
    hl_str_release(key);
    return found;
}

// hl_env_set(key, value) — set an env var. setenv copies the
// strings; we release the hl_str* args after the call.
static void hl_env_set(hl_str* key, hl_str* value) {
    setenv(key->data, value->data, 1);
    hl_str_release(key);
    hl_str_release(value);
}

// hl_env_unset(key) — unset an env var. unsetenv is a no-op if
// the var does not exist (no error).
static void hl_env_unset(hl_str* key) {
    unsetenv(key->data);
    hl_str_release(key);
}

// hl_cwd_get() — read the cwd. Returns a fresh str. The cwd is
// always available on POSIX (no failure case). The buffer
// grows as needed via getcwd(NULL, 0) — a glibc extension that
// allocates the right size automatically. Falls back to a
// fixed-size buffer on systems that don't support this.
static hl_str* hl_cwd_get(void) {
    char* buf = getcwd(NULL, 0);
    if (buf == NULL) {
        return hl_str_from("", 0);
    }
    size_t n = strlen(buf);
    hl_str* out = hl_str_from(buf, (int64_t)n);
    free(buf);
    return out;
}

// hl_cwd_set(path) — change the cwd. Returns 0 on success,
// -1 on error. Consumes the path.
static int64_t hl_cwd_set(hl_str* path) {
    int rc = chdir(path->data);
    hl_str_release(path);
    if (rc < 0) return -1;
    return 0;
}

// hl_instant_now_ns() — monotonic nanoseconds (high-resolution).
static int64_t hl_instant_now_ns(void) {
#if defined(CLOCK_MONOTONIC)
    struct timespec ts;
    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
        return 0;
    }
    return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec;
#else
    /* Fallback: clock_ms * 1000000 — ms resolution. */
    struct timeval tv;
    if (gettimeofday(&tv, NULL) != 0) {
        return 0;
    }
    return (int64_t)tv.tv_sec * 1000000000LL
         + (int64_t)tv.tv_usec * 1000LL;
#endif
}

// hl_system_time_now_ms() — wall-clock milliseconds since Unix epoch.
static int64_t hl_system_time_now_ms(void) {
#if defined(CLOCK_REALTIME)
    struct timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) {
        return 0;
    }
    return (int64_t)ts.tv_sec * 1000LL + (int64_t)ts.tv_nsec / 1000000LL;
#else
    struct timeval tv;
    if (gettimeofday(&tv, NULL) != 0) {
        return 0;
    }
    return (int64_t)tv.tv_sec * 1000LL + (int64_t)tv.tv_usec / 1000LL;
#endif
}

// Stage 50 math_* helpers — thin wrappers around libm.
static inline double hl_math_sin(double x)        { return sin(x); }
static inline double hl_math_cos(double x)        { return cos(x); }
static inline double hl_math_tan(double x)        { return tan(x); }
static inline double hl_math_asin(double x)      { return asin(x); }
static inline double hl_math_acos(double x)      { return acos(x); }
static inline double hl_math_atan(double x)      { return atan(x); }
static inline double hl_math_atan2(double y, double x) { return atan2(y, x); }
static inline double hl_math_sinh(double x)      { return sinh(x); }
static inline double hl_math_cosh(double x)      { return cosh(x); }
static inline double hl_math_tanh(double x)      { return tanh(x); }
static inline double hl_math_exp(double x)       { return exp(x); }
static inline double hl_math_log(double x)       { return log(x); }
static inline double hl_math_log10(double x)     { return log10(x); }
#if defined(HL_HAVE_LOG2)
static inline double hl_math_log2(double x)      { return log2(x); }
#else
static inline double hl_math_log2(double x)      { return log(x) / log(2.0); }
#endif
static inline double hl_math_pow(double b, double e)  { return pow(b, e); }
static inline double hl_math_sqrt(double x)      { return sqrt(x); }
static inline double hl_math_cbrt(double x)      { return cbrt(x); }
static inline double hl_math_hypot(double x, double y) { return hypot(x, y); }
static inline double hl_math_fmod(double x, double y) { return fmod(x, y); }
static inline double hl_math_erf(double x)      { return erf(x); }
static inline double hl_math_erfc(double x)     { return erfc(x); }
static inline double hl_math_tgamma(double x)   { return tgamma(x); }
static inline double hl_math_lgamma(double x)   { return lgamma(x); }
static inline bool   hl_math_isnan(double x)    { return isnan(x); }
static inline bool   hl_math_isinf(double x)    { return isinf(x); }
static inline bool   hl_math_isfinite(double x)  { return isfinite(x); }
static inline bool   hl_math_signbit(double x)  { return signbit(x); }
static inline double hl_math_copysign(double x, double y) { return copysign(x, y); }

// hl_net_tcp_connect(host, port) — TCP connect to host:port.
// Returns the socket fd (>= 0) or -1 on failure. Consumes host.
static int64_t hl_net_tcp_connect(hl_str* host, int64_t port) {
    struct addrinfo hints;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    struct addrinfo* res = NULL;
    char port_buf[16];
    snprintf(port_buf, sizeof(port_buf), "%lld", (long long)port);
    int rc = getaddrinfo(host->data, port_buf, &hints, &res);
    if (rc != 0 || res == NULL) {
        hl_str_release(host);
        return -1;
    }
    int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
    if (fd < 0) {
        freeaddrinfo(res);
        hl_str_release(host);
        return -1;
    }
    struct timeval tv;
    tv.tv_sec = 5; tv.tv_usec = 0;
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
    if (connect(fd, res->ai_addr, res->ai_addrlen) < 0) {
        close(fd);
        freeaddrinfo(res);
        hl_str_release(host);
        return -1;
    }
    freeaddrinfo(res);
    hl_str_release(host);
    return (int64_t)fd;
}

// hl_net_tcp_listen(host, port, backlog) — bind + listen. Returns
// the listen fd or -1. SO_REUSEADDR is set so a restart doesn't
// wait for TIME_WAIT. Consumes host.
static int64_t hl_net_tcp_listen(hl_str* host, int64_t port, int64_t backlog) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        hl_str_release(host);
        return -1;
    }
    int yes = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t)port);
    if (host->len == 0 || strcmp(host->data, "0.0.0.0") == 0) {
        addr.sin_addr.s_addr = htonl(INADDR_ANY);
    } else if (strcmp(host->data, "127.0.0.1") == 0 || strcmp(host->data, "localhost") == 0) {
        addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    } else if (inet_pton(AF_INET, host->data, &addr.sin_addr) != 1) {
        close(fd);
        hl_str_release(host);
        return -1;
    }
    if (bind(fd, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
        close(fd);
        hl_str_release(host);
        return -1;
    }
    if (listen(fd, (int)backlog) < 0) {
        close(fd);
        hl_str_release(host);
        return -1;
    }
    hl_str_release(host);
    return (int64_t)fd;
}

// hl_net_tcp_accept(fd) — accept a connection. Returns the client
// fd or -1 on error. Blocks until a peer connects (the listen
// fd's accept timeout is inherited from the listen socket).
static int64_t hl_net_tcp_accept(int64_t fd) {
    int cfd = accept((int)fd, NULL, NULL);
    if (cfd < 0) return -1;
    struct timeval tv;
    tv.tv_sec = 30; tv.tv_usec = 0;
    setsockopt(cfd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(cfd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
    return (int64_t)cfd;
}

// hl_net_read(fd, n) — read up to n bytes from the socket.
// Returns a fresh str (refcnt=1). Empty str at EOF or on error.
// n is clamped to a 64 KiB cap to avoid unbounded allocation.
static hl_str* hl_net_read(int64_t fd, int64_t n) {
    if (n <= 0) return hl_str_from("", 0);
    if (n > 65536) n = 65536;
    char buf[65536];
    ssize_t got = recv((int)fd, buf, (size_t)n, 0);
    if (got <= 0) return hl_str_from("", 0);
    return hl_str_from(buf, (int64_t)got);
}

// hl_net_write(fd, data) — write all bytes. Returns bytes written
// or -1 on error. Consumes data. Uses send() in a loop because
// a single send() may not write all bytes for large payloads.
static int64_t hl_net_write(int64_t fd, hl_str* data) {
    int64_t total = 0;
    while (total < data->len) {
        ssize_t w = send((int)fd, data->data + total,
                         (size_t)(data->len - total), 0);
        if (w <= 0) {
            hl_str_release(data);
            return -1;
        }
        total += w;
    }
    int64_t r = data->len;
    hl_str_release(data);
    return r;
}

// hl_net_close(fd) — close the socket. Idempotent (a double-close
// is a silent no-op, matching the interpreter).
static void hl_net_close(int64_t fd) {
    if (fd >= 0) close((int)fd);
}

// hl_net_udp_open() — create a UDP socket. Returns fd or -1.
// A 5-second recv timeout is set so recv_from doesn't hang
// forever on a dead peer (matches the interpreter).
static int64_t hl_net_udp_open() {
    int fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (fd < 0) return -1;
    struct timeval tv;
    tv.tv_sec = 5; tv.tv_usec = 0;
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    return (int64_t)fd;
}

// hl_net_udp_send_to(fd, host, port, data) — send a UDP datagram.
// Returns bytes sent or -1. Consumes host and data.
static int64_t hl_net_udp_send_to(int64_t fd, hl_str* host,
                                 int64_t port, hl_str* data) {
    struct addrinfo hints;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_DGRAM;
    struct addrinfo* res = NULL;
    char port_buf[16];
    snprintf(port_buf, sizeof(port_buf), "%lld", (long long)port);
    int rc = getaddrinfo(host->data, port_buf, &hints, &res);
    hl_str_release(host);
    if (rc != 0 || res == NULL) {
        hl_str_release(data);
        return -1;
    }
    ssize_t n = sendto((int)fd, data->data, (size_t)data->len, 0,
                       res->ai_addr, res->ai_addrlen);
    freeaddrinfo(res);
    int64_t r = (n >= 0) ? (int64_t)n : -1;
    hl_str_release(data);
    return r;
}

// hl_net_udp_recv_from(fd, n) — receive a UDP datagram. Returns a
// fresh str (refcnt=1). Empty str on error or timeout. The sender's
// address is discarded (callers who need it should use the raw C
// recvfrom directly via FFI — Stage 15).
static hl_str* hl_net_udp_recv_from(int64_t fd, int64_t n) {
    if (n <= 0) return hl_str_from("", 0);
    if (n > 65536) n = 65536;
    char buf[65536];
    ssize_t got = recvfrom((int)fd, buf, (size_t)n, 0, NULL, NULL);
    if (got <= 0) return hl_str_from("", 0);
    return hl_str_from(buf, (int64_t)got);
}

typedef struct { char* data; int64_t len; int64_t cap; } hl_curl_buf;
static size_t hl_curl_write_cb(char* ptr, size_t sz, size_t n, void* ud) {
    hl_curl_buf* b = (hl_curl_buf*)ud;
    size_t total = sz * n;
    if (b->len + (int64_t)total > b->cap) {
        int64_t newcap = b->cap * 2;
        if (newcap < b->len + (int64_t)total) newcap = b->len + (int64_t)total;
        char* nd = (char*)realloc(b->data, (size_t)newcap);
        if (!nd) return 0;
        b->data = nd; b->cap = newcap;
    }
    memcpy(b->data + b->len, ptr, total);
    b->len += (int64_t)total;
    return total;
}
static hl_str* hl_net_tls_get(hl_str* host, int64_t port, hl_str* path) {
    if (path->len == 0 || path->data[0] != '/') {
        char* nb = (char*)malloc((size_t)(path->len + 2));
        if (!nb) { hl_str_release(host); hl_str_release(path); hl_die("net_tls_get: oom"); }
        nb[0] = '/';
        memcpy(nb + 1, path->data, (size_t)path->len);
        nb[path->len + 1] = 0;
        hl_str* np = hl_str_from(nb, path->len + 1);
        free(nb);
        hl_str_release(path);
        path = np;
    }
    char url[4096];
    snprintf(url, sizeof(url), "https://%s:%lld%s",
             host->data, (long long)port, path->data);
    (void)url;
#ifdef HL_HAVE_LIBCURL
    CURL* c = curl_easy_init();
    if (!c) {
        hl_str_release(host); hl_str_release(path);
        hl_die("net_tls_get: curl_easy_init failed");
    }
    hl_curl_buf buf;
    buf.data = (char*)malloc(4096);
    buf.len = 0; buf.cap = 4096;
    if (!buf.data) {
        curl_easy_cleanup(c);
        hl_str_release(host); hl_str_release(path);
        hl_die("net_tls_get: oom");
    }
    curl_easy_setopt(c, CURLOPT_URL, url);
    curl_easy_setopt(c, CURLOPT_WRITEFUNCTION, hl_curl_write_cb);
    curl_easy_setopt(c, CURLOPT_WRITEDATA, &buf);
    curl_easy_setopt(c, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(c, CURLOPT_TIMEOUT, 30L);
    curl_easy_setopt(c, CURLOPT_FAILONERROR, 1L);
    CURLcode rc = curl_easy_perform(c);
    long http_code = 0;
    curl_easy_getinfo(c, CURLINFO_RESPONSE_CODE, &http_code);
    curl_easy_cleanup(c);
    hl_str_release(host); hl_str_release(path);
    if (rc != CURLE_OK) {
        free(buf.data);
        hl_die("net_tls_get: transport/TLS error");
    }
    if (http_code >= 400) {
        free(buf.data);
        hl_die("net_tls_get: HTTP error");
    }
    hl_str* out = hl_str_from(buf.data, buf.len);
    free(buf.data);
    return out;
#else
    hl_str_release(host); hl_str_release(path);
    hl_die("net_tls_get: built without libcurl (rebuild with -DHAVE_LIBCURL and link -lcurl)");
#endif
}

// ---- v0.2 additions: pop, float, chr, fmod ----
// String split helper (placed last because it depends on hl_list)
static hl_list* hl_str_split(hl_str* s, hl_str* sep) {
    if (sep->len == 0) hl_die("empty separator not allowed");
    hl_list* out = hl_list_new(hl_str_release);
    if (s->len == 0) {
        hl_list_push(out, hl_str_from("", 0));
        return out;
    }
    if (s->len < sep->len) {
        hl_list_push(out, hl_str_from(s->data, s->len));
        return out;
    }
    int64_t start = 0;
    int64_t i = 0;
    while (i <= s->len - sep->len) {
        if (memcmp(s->data + i, sep->data, (size_t)sep->len) == 0) {
            hl_list_push(out, hl_str_from(s->data + start, i - start));
            i += sep->len;
            start = i;
        } else {
            i++;
        }
    }
    hl_list_push(out, hl_str_from(s->data + start, s->len - start));
    return out;
}

// ---- v0.2 additions: pop, float, chr, fmod ----
// hl_list_pop: ownership of the removed item transfers to the caller.
static void* hl_list_pop(hl_list* l) {
    if (l->len == 0) hl_die("pop from empty list");
    l->len--;
    return l->items[l->len];
}

// Typed pops for primitive element lists: pop the box, unbox the
// value, free the box. (A plain pop + unbox would leak the box —
// the caller only wanted the primitive.)
static int64_t hl_list_pop_i64(hl_list* l) {
    void* b = hl_list_pop(l);
    int64_t v = hl_unbox_i64(b);
    free(b);
    return v;
}
static double hl_list_pop_f64(hl_list* l) {
    void* b = hl_list_pop(l);
    double v = hl_unbox_f64(b);
    free(b);
    return v;
}
static bool hl_list_pop_bool(hl_list* l) {
    void* b = hl_list_pop(l);
    bool v = hl_unbox_bool(b);
    free(b);
    return v;
}

static double hl_str_to_double(hl_str* s) {
    int64_t i = 0;
    int64_t dots = 0;
    int64_t digits = 0;
    int saw_exp = 0;
    int exp_digits = 0;
    if (s->len == 0) hl_die("cannot convert string to float");
    if (s->data[0] == '-' || s->data[0] == '+') i = 1;
    if (i >= s->len) hl_die("cannot convert string to float");
    for (; i < s->len; i++) {
        char c = s->data[i];
        if (c == '.') { if (saw_exp) hl_die("cannot convert string to float"); dots++; continue; }
        if (c == 'e' || c == 'E') {
            if (saw_exp || digits == 0) hl_die("cannot convert string to float");
            saw_exp = 1;
            if (i + 1 < s->len && (s->data[i+1] == '+' || s->data[i+1] == '-')) i++;
            exp_digits = 0;
            continue;
        }
        if (c < '0' || c > '9') hl_die("cannot convert string to float");
        if (saw_exp) exp_digits++;
        digits++;
    }
    if (dots > 1 || digits == 0) hl_die("cannot convert string to float");
    if (saw_exp && exp_digits == 0) hl_die("cannot convert string to float");
    return strtod(s->data, NULL);
}

static hl_str* hl_chr(int64_t c) {
    if (c < 0 || c > 255) hl_die("chr out of range 0..255");
    char b = (char)c;
    return hl_str_from(&b, 1);
}

static double hl_fmod(double a, double b) {
    return fmod(a, b);
}

// BUG-15 fix: range-checked float -> int64 conversion. C casts
// silently truncate out-of-range floats; we panic instead so the
// error points to the actual source of the bad value.
// Deep-scan-25 fix: the upper bound must be >= 2^63, not > 2^63.
// The old literal 9.2233720368547757e18 rounds to exactly 2^63 as
// a double, so v == 2^63 slipped past the check into (int64_t)v —
// undefined behaviour that produced a garbage value (observed as
// INT64_MAX on x86-64) while the boot interpreter panicked. There
// are no doubles strictly between INT64_MAX and 2^63, so >= 2^63
// rejects exactly the out-of-range positives.
static int64_t hl_float_to_int(double v) {
    // NaN fails BOTH comparisons, so an explicit isnan check is
    // required — otherwise the cast below is undefined behaviour.
    if (isnan(v) || v < -9.2233720368547758e18 || v >= 9.2233720368547758e18)
        hl_die("float.to_int out of int64 range");
    return (int64_t)v;
}

// hl_file_exists: consumes the path.
static bool hl_file_exists(hl_str* path) {
    hl_sandbox_check(path->data);
    struct stat st;
    bool ok = stat(path->data, &st) == 0 && S_ISREG(st.st_mode);
    hl_str_release(path);
    return ok;
}

// hl_fs_read_dir: consumes the path, returns a fresh list[str]
// of entry NAMES (not full paths). Sorted by byte-lexicographic
// order so the native binary and the interpreter (which uses
// sorted(os.listdir(...))) agree on iteration order. The list
// owns one retain per entry; each entry is a fresh hl_str*.
static hl_list* hl_fs_read_dir(hl_str* path) {
    hl_sandbox_check(path->data);
    DIR* d = opendir(path->data);
    if (!d) {
        hl_str_release(path);
        hl_die("fs_read_dir: cannot open directory");
    }
    hl_list* out = hl_list_new(hl_str_release);
    struct dirent* e;
    while ((e = readdir(d)) != NULL) {
        // Skip "." and ".." — they are always present and
        // never useful to callers (and they would create
        // infinite loops in path_walk if included).
        if (strcmp(e->d_name, ".") == 0) continue;
        if (strcmp(e->d_name, "..") == 0) continue;
        int64_t n = (int64_t)strlen(e->d_name);
        hl_list_push(out, hl_str_from(e->d_name, n));
    }
    closedir(d);
    hl_str_release(path);
    // Sort the entries by byte-lexicographic order. The list
    // owns one retain per entry; we use a simple insertion sort
    // to avoid pulling in qsort_r (which has portability
    // quirks across glibc / musl / BSD). n is typically small
    // (a single directory's entries), so O(n²) is fine here.
    for (int64_t i = 1; i < out->len; i++) {
        hl_str* v = (hl_str*)out->items[i];
        int64_t j = i;
        while (j > 0) {
            hl_str* prev = (hl_str*)out->items[j - 1];
            if (hl_str_cmp(prev, v) <= 0) break;
            out->items[j] = out->items[j - 1];
            j--;
        }
        out->items[j] = v;
    }
    return out;
}

// hl_fs_size: consumes the path, returns the file size in bytes.
// Panics on stat failure (matches the interpreter).
static int64_t hl_fs_size(hl_str* path) {
    hl_sandbox_check(path->data);
    struct stat st;
    if (stat(path->data, &st) != 0) {
        hl_str_release(path);
        hl_die("fs_size: cannot stat");
    }
    hl_str_release(path);
    return (int64_t)st.st_size;
}

// hl_fs_is_dir: consumes the path, returns true iff it is a
// directory. Returns false for non-existent paths (matches
// file_exists semantics for files).
static bool hl_fs_is_dir(hl_str* path) {
    hl_sandbox_check(path->data);
    struct stat st;
    bool ok = stat(path->data, &st) == 0 && S_ISDIR(st.st_mode);
    hl_str_release(path);
    return ok;
}

// hl_fs_set_perms: consumes the path. `mode` is the POSIX
// permission bits (e.g. 0644 = 420 decimal). Panics on chmod
// failure. The path argument is consumed (one retain) — the
// mode is a primitive int that needs no cleanup.
static void hl_fs_set_perms(hl_str* path, int64_t mode) {
    hl_sandbox_check(path->data);
    if (chmod(path->data, (mode_t)mode) != 0) {
        hl_str_release(path);
        hl_die("fs_set_perms: cannot chmod");
    }
    hl_str_release(path);
}

// clone(str) — strings are immutable, so a shallow copy is a deep copy.
static hl_str* hl_clone_str(hl_str* s) {
    return hl_str_from(s->data, s->len);
}



// ---- Stage 8-beta: ownership helper prototypes ----

hl_str* usf_greet(hl_str*);
int64_t usf_main(void);

hl_str* usf_greet(hl_str* u_name_p) {
    hl_str* u_name __attribute__((cleanup(hl_cleanup_str))) = u_name_p;
    return hl_str_concat(hl_str_concat(hl_cstr("Hello, "), u_name), hl_cstr("!"));
}

int64_t usf_main(void) {
    hl_println(usf_greet(hl_cstr("Halis")));
    hl_println(hl_cstr("A high-security programming language, compiled native."));
    hl_println(hl_cstr("Compiled by a compiler written in HLS itself."));
    return 0;
}

int main(int argc, char** argv) {
    hl_init_args(argc, argv);
    const char* hl_sb = getenv("HLS_SANDBOX_ROOT");
    if (hl_sb && hl_sb[0]) hl_set_sandbox_root(hl_sb);
    return (int)(usf_main());
}