"""LLVM IR emitter for Halis (Stage 12).

Emits LLVM IR text (.ll) from a checked HLS program (post-type-check AST).
The IR can be assembled by `llc` or `clang` into an object file.

Design:
  - The HLS C runtime (emitted inline by `src/hlc.hls` codegen) is treated
    as an opaque external library. The LLVM emitter declares each runtime
    function as `declare` and calls them via `call`. The symbol names and
    signatures mirror the ACTUAL runtime (hl_str_from_int64, hl_div_i64,
    hl_box_i64, ...) — not aspirational ones.
  - HLS types map to LLVM types as follows:
      int    -> i64
      float  -> double
      bool   -> i1   (COMPARISONS/`&&`/`||`/`!` all produce and consume i1;
                      there is no i64 widening of booleans anywhere)
      str    -> ptr (pointer to %hl_str)
      void   -> void
      tainted[T] -> LLVM type of T (taint is compile-time only, like the
                    C backend)
      list[T] / map[str,T] / struct / enum -> ptr (opaque)
  - Each HLS function becomes an LLVM `define` with the appropriate
      parameter types. Extern "C" declarations become `declare` (Stage 15).
  - Local variable slots are HOISTED to the function entry block: `alloca`
      inside a loop body would grow the stack on every iteration (LLVM
      allocas are not reclaimed until function return), so every `let` /
      `for`-loop variable gets its slot pre-allocated in `entry:`.
  - Basic blocks are emitted for `if`/`while`/`for` control flow. The
      emitter tracks the CURRENT open block label (self._cur_block) so that
      (a) no instruction is ever emitted after a terminator (dead code after
      `return`/`break`/`continue`/`panic`/`exit` is skipped), and (b) `&&` /
      `||` can be lowered to real short-circuit control flow with `phi`.
  - Integer `+`/`-`/`*` use llvm.sadd/ssub/smul.with.overflow.i64 with an
      overflow-path branch to `hl_die` (matching the C runtime's
      hl_add_i64/hl_sub_i64/hl_mul_i64). Integer `/`/`%`/unary `-` call the
      runtime's hl_div_i64/hl_mod_i64/hl_neg_i64 so the zero / INT64_MIN /
      -1 panics are byte-identical to the interpreter and the C backend.
  - Dynamic lists store BOXED elements (hl_box_i64/hl_box_f64/hl_box_bool/
      hl_box_ptr on push/set, load from the box pointer on get) — the same
      ABI as the C runtime.

Constructs that the alpha backend does not support yet — struct literals,
struct field access, enum literals, `match`, `?`, and calls to USER-DEFINED
struct methods — raise a clean HLError ("not yet supported by --emit llvm")
instead of silently emitting invalid IR. See ROADMAP.md "Remaining work for
Stage 12".

Multi-target support:
  - The default target is the host triple (queried from `llvm-config`).
  - `--target aarch64-linux` cross-compiles.
  - PGO (profile-guided optimisation) is deferred to a later stage.

The emitter is a *separate backend* from the C codegen. It is wired into
`boot.py` via the `--emit llvm` flag.
"""
from __future__ import annotations
from typing import Dict, List, Optional, Tuple

import os
import sys

# Resolve HLError whether we are imported as `llvm_emit` (sys.path contains
# the repo root, set up by boot.py) or run from anywhere.
try:
    from boot.lexer import HLError  # type: ignore
except ImportError:  # pragma: no cover
    _REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if _REPO_ROOT not in sys.path:
        sys.path.insert(0, _REPO_ROOT)
    from boot.lexer import HLError  # type: ignore


# Runtime function declarations — these mirror the C runtime emitted by
# src/hlc.hls EXACTLY (see the r.push("static ...") lines in the runtime
# section of hlc.hls). BUG-DS4-3 fix: the old table declared symbols that
# do not exist in the runtime (hl_int_to_str, hl_float_to_str,
# hl_str_to_float, hl_str_subst, hl_str_lower, hl_str_upper, hl_str_repeat,
# hl_str_reverse, hl_args_count, hl_args_get, hl_ord) and MISSED the ones
# that do (hl_str_from_int64, hl_str_from_double, hl_str_from_bool,
# hl_str_to_double, hl_range, hl_args, hl_panic, hl_chr, hl_box_*,
# hl_unbox helpers, hl_div_i64, hl_mod_i64, hl_neg_i64, hl_abs_i64,
# hl_clone_*). Assembling/linking the old output failed with undefined
# symbols; the new table matches the runtime 1:1.
RUNTIME_DECLS = """
; ===== Halis runtime declarations (opaque externals) =====
; Layout mirrors the C runtime generated by src/hlc.hls.
%hl_str  = type { i64, ptr }              ; { len, data }
%hl_list = type { i64, i64, ptr }         ; { len, cap, items }
%hl_map  = type { i64, i64, ptr, ptr, ptr }

declare void     @hl_die(ptr) #0                 ; const char* -> noreturn
declare void     @hl_panic(ptr) #0                 ; hl_str* -> noreturn (panic: msg, exit 101)
declare void     @hl_exit(i64) #0                  ; noreturn
declare i64      @hl_clock_ms()
declare ptr      @hl_args()                         ; -> hl_list* (list[str])
declare i1       @hl_file_exists(ptr)
declare ptr      @hl_read_file(ptr)
declare void     @hl_write_file(ptr, ptr)
declare void     @hl_print(ptr)                     ; hl_str*
declare void     @hl_println(ptr)                   ; hl_str*

; strings
declare ptr      @hl_str_alloc(i64)
declare ptr      @hl_str_from(ptr, i64)             ; (const char* data, i64 len) -> hl_str*
declare ptr      @hl_str_concat(ptr, ptr)
declare i1       @hl_str_eq(ptr, ptr)
declare i64      @hl_str_cmp(ptr, ptr)
declare i64      @hl_str_len(ptr)
declare i64      @hl_str_byte_at(ptr, i64)
declare ptr      @hl_str_slice(ptr, i64, i64)
declare i64      @hl_str_find(ptr, ptr)
declare i1       @hl_str_contains(ptr, ptr)
declare i1       @hl_str_starts_with(ptr, ptr)
declare i1       @hl_str_ends_with(ptr, ptr)
declare ptr      @hl_str_split(ptr, ptr)
declare ptr      @hl_str_trim(ptr)
declare ptr      @hl_str_from_int64(i64)
declare ptr      @hl_str_from_double(double)
declare ptr      @hl_str_from_bool(i1)
declare i64      @hl_str_to_int(ptr)
declare double   @hl_str_to_double(ptr)
declare ptr      @hl_chr(i64)                       ; -> hl_str*
declare ptr      @hl_clone_str(ptr)

; checked int64 arithmetic (identical panics to the interpreter)
declare i64      @hl_neg_i64(i64)
declare i64      @hl_abs_i64(i64)
declare i64      @hl_div_i64(i64, i64)
declare i64      @hl_mod_i64(i64, i64)
declare i64      @hl_float_to_int(double)           ; range-checked

; dynamic list (boxed elements)
declare ptr      @hl_list_new(ptr)               ; (elem_free) — arena mode passes null
declare void     @hl_list_push(ptr, ptr)
declare ptr      @hl_list_get(ptr, i64)
declare void     @hl_list_set(ptr, i64, ptr)
declare ptr      @hl_list_pop(ptr)
declare i64     @hl_list_pop_i64(ptr)              ; pop + unbox + free the box
declare double  @hl_list_pop_f64(ptr)
declare i1      @hl_list_pop_bool(ptr)
declare i64      @hl_list_len(ptr)
declare ptr      @hl_range(i64, i64)
declare ptr      @hl_str_join(ptr, ptr)         ; (list[str], sep) -> str — O(n) join (Stage 19)
declare i1      @hl_simd_cpu_supports(ptr)      ; (feature name) -> bool (Stage 21 runtime probe)

; boxed element constructors (get uses a plain load from the box pointer)
declare ptr      @hl_box_i64(i64)
declare ptr      @hl_box_f64(double)
declare ptr      @hl_box_bool(i1)
declare ptr      @hl_box_ptr(ptr)

; map[str, T]
declare ptr      @hl_map_new(ptr)                ; (val_free) — arena mode passes null
declare i64     @hl_map_get_i64(ptr, ptr, i64)    ; (m, k, default) -> value or default
declare double  @hl_map_get_f64(ptr, ptr, double)
declare i1      @hl_map_get_bool(ptr, ptr, i1)
declare ptr     @hl_map_borrow(ptr, ptr)           ; (m, k) -> stored value or null
declare void     @hl_map_set(ptr, ptr, ptr)
declare i1       @hl_map_has(ptr, ptr)
declare i64      @hl_map_len(ptr)
declare ptr      @hl_map_keys(ptr)

; per-instantiation clone helpers (Stage 8-alpha subset)
declare ptr      @hl_clone_list_int(ptr)
declare ptr      @hl_clone_list_float(ptr)
declare ptr      @hl_clone_list_bool(ptr)
declare ptr      @hl_clone_list_str(ptr)
declare ptr      @hl_clone_map_int(ptr)
declare ptr      @hl_clone_map_float(ptr)
declare ptr      @hl_clone_map_bool(ptr)
declare ptr      @hl_clone_map_str(ptr)

; Stage 12 release: struct/enum runtime constructors + field accessors.
; These symbols are emitted by the C backend's runtime codegen (see
; gen_struct_lit / gen_field in src/hlc.hls). The LLVM backend calls them
; via opaque ptr — the layout is owned by the C runtime.
declare ptr      @hl_struct_alloc(i64)              ; (size in bytes) -> opaque ptr
declare void     @hl_struct_set_i64(ptr, i64, i64)  ; (struct, field_idx, value)
declare void     @hl_struct_set_f64(ptr, i64, double)
declare void     @hl_struct_set_bool(ptr, i64, i1)
declare void     @hl_struct_set_ptr(ptr, i64, ptr)
declare i64      @hl_struct_get_i64(ptr, i64)
declare double   @hl_struct_get_f64(ptr, i64)
declare i1       @hl_struct_get_bool(ptr, i64)
declare ptr      @hl_struct_get_ptr(ptr, i64)

; Enum tag access (the runtime emits enums as a tagged-union struct).
declare i64      @hl_enum_tag(ptr)                  ; -> variant index
declare ptr      @hl_enum_new_variant(i64)          ; (variant_idx) -> new enum value
declare ptr      @hl_enum_payload(ptr)               ; -> payload ptr (variant data)

; Stage 12 release: stdin / read_line (Stage 10 release runtime helpers).
declare ptr      @hl_read_line()                   ; -> hl_str* (one line, CRLF stripped)

; Stage 12 release: net / rand / proc runtime helpers (Stage 9 release).
declare i1       @hl_net_lookup(ptr, ptr)           ; (host, out_ip) -> success
declare i64      @hl_rand_int(i64)                  ; (max_exclusive) -> [0, max)
declare double   @hl_rand_float()
declare void     @hl_rand_seed(i64)
declare i64      @hl_proc_exec(ptr)                 ; (cmd) -> exit code
"""

# Stage 12 release: attributes block. `#0` is the noreturn attribute set
# attached to hl_die / hl_panic / hl_exit above so the LLVM optimiser
# knows those calls don't return (otherwise it may DCE the trailing
# `unreachable` and move code across the call, breaking control flow).
ATTRIBUTES = """
attributes #0 = { noreturn }
"""

# Intrinsic declarations (LLVM recognises intrinsics without declares, but
# being explicit keeps the module self-documenting).
INTRINSIC_DECLS = """
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare double     @llvm.fabs.f64(double)
"""


# HLS -> LLVM type mapping.
def hls_type_to_llvm(t: str) -> str:
    if t == "int":
        return "i64"
    if t == "float":
        return "double"
    if t == "bool":
        return "i1"
    if t == "void":
        return "void"
    if t == "str":
        return "ptr"
    # Taint is compile-time only (same as the C backend): tainted[T]
    # values have the representation of T at runtime.
    if t.startswith("tainted["):
        return hls_type_to_llvm(_taint_inner(t))
    if t.startswith("list[") or t.startswith("map["):
        return "ptr"
    # User-defined struct / enum -> opaque pointer.
    return "ptr"


# Small local type-string helpers (mirror boot/checker.py's predicates).
def _is_list(t: str) -> bool:
    return t.startswith("list[")


def _list_elem(t: str) -> str:
    return t[5:-1]


def _is_map(t: str) -> bool:
    return t.startswith("map[str, ")


def _map_val(t: str) -> str:
    return t[9:-1]


def _taint_inner(t: str) -> str:
    if t.startswith("tainted["):
        return t[8:-1]
    return t


def _unsupported(what: str, node: Dict):
    """Raise a clean compile error for constructs the alpha LLVM backend
    does not support yet (ROADMAP Stage 12 'Remaining work'). Silently
    emitting invalid IR is worse than a clear error."""
    line = node.get("line", 0) if isinstance(node, dict) else 0
    raise HLError(
        "%s is not yet supported by --emit llvm (Stage 12-alpha subset; "
        "see ROADMAP.md 'Remaining work for Stage 12'). The C backend "
        "(-C / hlc.hls) supports it." % what, line, 0)


# ---------------------------------------------------------------------------
# Emitter
# ---------------------------------------------------------------------------

class LLVMEmitter:
    """Walks a checked HLS program AST and emits LLVM IR text."""

    def __init__(self, program, target_triple: Optional[str] = None):
        self.program = program
        self.target_triple = target_triple
        self.lines: List[str] = []
        self._tmp = 0
        self._label = 0
        self._ov_counter = 0
        self._str_counter = 0
        self._sc_counter = 0
        self._string_consts: List[Tuple[str, bytes, str]] = []
        # Stack of (continue_label, break_label) for loops.
        self._loop_stack: List[Tuple[str, str]] = []
        # Per-function local variable map: name -> (LLVM register, llvm_type).
        self._locals: Dict[str, Tuple[str, str]] = {}
        # The current function's return type (HLS type string).
        self._current_ret_type_value: str = "void"
        # The label of the currently open basic block, or None right after
        # a terminator was emitted. Used to (a) never emit instructions
        # after a terminator and (b) build phi nodes for && / ||.
        self._cur_block: Optional[str] = None
        # Deep-scan-12 fix (DSS-T-02): deferred allocas to be flushed into
        # the entry block when the function's body has been lowered. The
        # `match` result slot is added here when a match is encountered
        # mid-body; it is then emitted into the entry block at function-
        # close time. (The entry block was already opened at line 430 with
        # `entry:`; we append the deferred allocas right before `}`.)
        self._entry_allocas: List[Tuple[str, str]] = []

    def _fresh(self, prefix="t"):
        self._tmp += 1
        return "%%%s%d" % (prefix, self._tmp)

    def _fresh_label(self, prefix="bb"):
        self._label += 1
        return "%s%d" % (prefix, self._label)

    def _emit(self, line: str):
        """Emit one line and maintain current-block tracking.

        A line ending in ':' opens a new basic block. A `br`/`ret`/
        `unreachable` line closes the current block (no further
        instructions may be emitted until the next label).
        """
        self.lines.append(line)
        s = line.strip()
        if s.endswith(":") and not s.startswith(";"):
            self._cur_block = s[:-1]
        elif (s.startswith("br ") or s.startswith("ret ")
              or s == "unreachable" or s.startswith("switch ")):
            self._cur_block = None

    def _to_i1(self, val_ty: str, val: str) -> str:
        """Coerce a value to i1 for use as a branch condition."""
        if val_ty == "i1":
            return val
        if val_ty == "i64":
            tmp = self._fresh("b")
            self._emit("  %s = trunc i64 %s to i1" % (tmp, val))
            return tmp
        if val_ty == "ptr":
            tmp = self._fresh("b")
            self._emit("  %s = icmp ne ptr %s, null" % (tmp, val))
            return tmp
        # Fallback: treat any other type as truthy (non-zero).
        tmp = self._fresh("b")
        self._emit("  %s = or i1 1, 0" % tmp)
        return tmp

    # ---------- public API ----------
    def emit(self) -> str:
        """Emit the complete module (prelude + functions)."""
        # Reset ALL emitter state (idempotent — safe to call twice).
        self.lines = []
        self._string_consts = []
        self._tmp = 0
        self._label = 0
        self._ov_counter = 0
        self._sc_counter = 0
        self._str_counter = 0
        self._locals = {}
        self._loop_stack = []
        self._cur_block = None
        if self.target_triple:
            self._emit("target triple = \"%s\"" % self.target_triple)
            self._emit("")
        for line in RUNTIME_DECLS.strip().split("\n"):
            self._emit(line)
        self._emit("")
        for line in INTRINSIC_DECLS.strip().split("\n"):
            self._emit(line)
        self._emit("")
        # Emit panic message constants (used by the with.overflow paths).
        # "integer overflow" = 16 chars + 1 NUL = 17 bytes.
        self._emit('@.panic_overflow_msg = private unnamed_addr constant [17 x i8] c"integer overflow\\00"')
        self._emit("")
        # Extern "C" declarations become `declare` lines (BUG-DS4-6: they
        # used to be emitted as broken `define`s with `unreachable` bodies
        # that shadowed the real libc symbols).
        extern_decl_lines = []
        for fname, fn in self.program["fns"].items():
            if not fn.get("extern", False):
                continue
            ret_llvm = hls_type_to_llvm(fn["ret"])
            param_tys = [hls_type_to_llvm(p[1]) for p in fn["params"]]
            extern_decl_lines.append(
                "declare %s @%s(%s)" % (
                    ret_llvm, fname, ", ".join(param_tys)))
        for ln in extern_decl_lines:
            self._emit(ln)
        if extern_decl_lines:
            self._emit("")
        # Emit functions (extern decls are skipped — they have no body).
        for fname, fn in self.program["fns"].items():
            if fn.get("extern", False):
                continue
            self._emit_function(fname, fn)
        # Emit collected string constants just before the final join.
        # Insert them right after the panic constants (the second blank
        # line region) so they precede all functions.
        if self._string_consts:
            insert_at = None
            blank_count = 0
            for idx, ln in enumerate(self.lines):
                if ln == "":
                    blank_count += 1
                    if blank_count == 4:  # after decls + intrinsics + panic const
                        insert_at = idx + 1
                        break
            if insert_at is None:
                insert_at = len(self.lines)
            sc_lines = []
            for name, data, bytes_str in self._string_consts:
                sc_lines.append('@%s = private unnamed_addr constant [%d x i8] [%s]' % (
                    name, len(data) + 1, bytes_str))
            sc_lines.append("")
            self.lines[insert_at:insert_at] = sc_lines
        # Stage 12 release: emit the attributes block at the end of the
        # module (LLVM requires `attributes #N = { ... }` after the
        # declarations that reference it).
        for line in ATTRIBUTES.strip().split("\n"):
            self._emit(line)
        self._emit("")
        return "\n".join(self.lines) + "\n"

    # ---------- function emission ----------
    def _emit_function(self, fname: str, fn: Dict):
        ret_llvm = hls_type_to_llvm(fn["ret"])
        self._current_ret_type_value = fn["ret"]
        self._locals = {}
        self._cur_block = None
        # Deep-scan-12 fix (DSS-T-02): per-function reset of the deferred
        # alloca list. The list is appended to by `_lower_match_typed`
        # (and any other construct that needs an entry-block alloca
        # discovered after pre-collection).
        self._entry_allocas = []
        params = []
        for (pname, ptype, _) in fn["params"]:
            params.append("%s %%v_%s" % (hls_type_to_llvm(ptype), pname))
        param_str = ", ".join(params)
        self._emit("define %s @%s(%s) {" % (ret_llvm, fname, param_str))
        self._emit("entry:")
        # Allocate stack slots for parameters so we can re-assign them
        # (HLS allows `let mut` reassignment). Track the LLVM type per
        # slot so load/store use the right type.
        for (pname, ptype, _) in fn["params"]:
            slot = self._fresh("p")
            pty = hls_type_to_llvm(ptype)
            self._emit("  %s = alloca %s" % (slot, pty))
            self._emit("  store %s %%v_%s, ptr %s" % (pty, pname, slot))
            self._locals[pname] = (slot, pty)
        # BUG-DS4-7: pre-allocate slots for ALL `let` bindings and `for`
        # loop variables in the ENTRY block. Allocating inside loop bodies
        # grows the stack on every iteration (LLVM allocas are not released
        # until function return), so a `while` loop with a `let` inside
        # would eventually exhaust the stack. Slots are keyed by
        # (name, hls-type); the same name in disjoint sibling scopes reuses
        # the same slot safely (HLS forbids shadowing, and each `let`
        # stores before any load on every path that reaches a use).
        self._slot_pool: Dict[Tuple[str, str], Tuple[str, str]] = {}
        collected: List[Tuple[str, str]] = []
        self._collect_bindings(fn["body"], collected)
        for (bname, btype) in collected:
            key = (bname, btype)
            if key in self._slot_pool:
                continue
            slot = self._fresh("l")
            bty = hls_type_to_llvm(btype)
            self._emit("  %s = alloca %s" % (slot, bty))
            self._slot_pool[key] = (slot, bty)
        # Deep-scan-12 (DSS-T-02): placeholder for deferred allocas (those
        # discovered DURING body lowering — currently only the match
        # result slot, but extensible). We splice them in here at function
        # close so they live in the entry block (LLVM's mem2reg pass
        # hoists entry-block allocas, and a loop-body alloca would grow
        # the stack on every iteration).
        marker_idx = len(self.lines)
        self._emit("  ; __deferred_allocas_placeholder__")
        # Lower each statement.
        for stmt in fn["body"]:
            self._lower_stmt(stmt)
        # Implicit return void for void functions; unreachable for non-void
        # (the type checker already rejects missing returns).
        if self._cur_block is not None:
            if fn["ret"] == "void":
                self._emit("  ret void")
            else:
                # Defensive unreachable — the checker should have rejected
                # this function for not returning on all paths.
                self._emit("  unreachable")
        # Splice the deferred allocas into the placeholder line.
        if self._entry_allocas:
            new_lines = []
            for (slot_name, slot_ty) in self._entry_allocas:
                new_lines.append("  %s = alloca %s" % (slot_name, slot_ty))
            # Replace the placeholder line (at marker_idx) with the alloca
            # lines. self.lines is only ever appended to during body
            # lowering, so marker_idx remains valid.
            self.lines[marker_idx:marker_idx + 1] = new_lines
        else:
            # No deferred allocas — drop the placeholder comment line.
            del self.lines[marker_idx]
        self._emit("}")
        self._emit("")

    def _collect_bindings(self, stmts, acc: List[Tuple[str, str]]):
        """Collect every (name, type) bound by `let` / `for` anywhere in
        this statement list, including nested block scopes."""
        for s in stmts:
            k = s["k"]
            if k == "let":
                acc.append((s["name"], s["t"]))
            elif k == "if":
                self._collect_bindings(s["then"], acc)
                if s.get("els"):
                    self._collect_bindings(s["els"], acc)
            elif k == "while":
                self._collect_bindings(s["body"], acc)
            elif k == "for":
                acc.append((s["var"], s["vtype"]))
                # BUG (deep-scan-5): the loop-index slot was NOT collected
                # — a `for` nested in a loop re-executed its alloca every
                # outer iteration; allocas are reclaimed only at function
                # return, so the stack grew without bound. Pre-allocate it
                # in the entry block like every other binding. The '#idx'
                # suffix cannot collide with user identifiers.
                acc.append((s["var"] + "#idx", "int"))
                self._collect_bindings(s["body"], acc)

    def _get_slot(self, name: str, hls_ty: str) -> Tuple[str, str]:
        """Return (slot, llvm_type) for a binding, allocating lazily if the
        pre-collection pass missed it (defensive)."""
        key = (name, hls_ty)
        entry = self._slot_pool.get(key)
        if entry is None:
            slot = self._fresh("l")
            ty = hls_type_to_llvm(hls_ty)
            self._emit("  %s = alloca %s" % (slot, ty))
            entry = (slot, ty)
            self._slot_pool[key] = entry
        return entry

    # ---------- statement lowering ----------
    def _lower_stmt(self, stmt: Dict):
        # Guard: if the current block is already terminated (return /
        # break / continue / panic / exit happened), the rest of this block
        # is unreachable dead code — emitting instructions here would
        # produce invalid IR (BUG-DS4-5: e.g. the `for` increment used to
        # be emitted after a `continue`'s branch).
        if self._cur_block is None:
            return
        k = stmt["k"]
        if k == "let":
            val_ty, val = self._lower_expr_typed(stmt["value"])
            slot, ty = self._get_slot(stmt["name"], stmt["t"])
            self._locals[stmt["name"]] = (slot, ty)
            if self._cur_block is None:
                # RHS was `never` (panic/exit) — nothing left to store.
                return
            self._emit("  store %s %s, ptr %s" % (ty, self._coerce(val_ty, val, ty), slot))
        elif k == "assign":
            self._lower_assign(stmt)
        elif k == "return":
            if stmt.get("value") is None:
                self._emit("  ret void")
            else:
                val_ty, val = self._lower_expr_typed(stmt["value"])
                if self._cur_block is None:
                    # Value was `never` (panic(...)/exit(...)) — the call
                    # itself already diverged; do not emit a ret after the
                    # unreachable (mirrors the C backend's BUG-004 handling).
                    return
                fn_ret = self._current_ret_type_value
                ret_ty = hls_type_to_llvm(fn_ret)
                self._emit("  ret %s %s" % (ret_ty, self._coerce(val_ty, val, ret_ty)))
        elif k == "if":
            cond_ty, cond = self._lower_expr_typed(stmt["cond"])
            if self._cur_block is None:
                return  # cond was `never` — unreachable
            cond = self._to_i1(cond_ty, cond)
            then_lbl = self._fresh_label("then")
            else_lbl = self._fresh_label("else")
            end_lbl = self._fresh_label("endif")
            has_else = bool(stmt.get("els"))
            if has_else:
                self._emit("  br i1 %s, label %%%s, label %%%s" % (
                    cond, then_lbl, else_lbl))
            else:
                self._emit("  br i1 %s, label %%%s, label %%%s" % (
                    cond, then_lbl, end_lbl))
            self._emit("%s:" % then_lbl)
            for s in stmt["then"]:
                self._lower_stmt(s)
            if self._cur_block is not None:
                self._emit("  br label %%%s" % end_lbl)
            if has_else:
                self._emit("%s:" % else_lbl)
                for s in stmt["els"]:
                    self._lower_stmt(s)
                if self._cur_block is not None:
                    self._emit("  br label %%%s" % end_lbl)
            self._emit("%s:" % end_lbl)
        elif k == "while":
            cond_lbl = self._fresh_label("while_cond")
            body_lbl = self._fresh_label("while_body")
            end_lbl = self._fresh_label("while_end")
            self._emit("  br label %%%s" % cond_lbl)
            self._emit("%s:" % cond_lbl)
            cond_ty, cond = self._lower_expr_typed(stmt["cond"])
            if self._cur_block is None:
                return  # cond was `never`
            cond = self._to_i1(cond_ty, cond)
            self._emit("  br i1 %s, label %%%s, label %%%s" % (
                cond, body_lbl, end_lbl))
            self._emit("%s:" % body_lbl)
            self._loop_stack.append((cond_lbl, end_lbl))
            for s in stmt["body"]:
                self._lower_stmt(s)
            self._loop_stack.pop()
            if self._cur_block is not None:
                self._emit("  br label %%%s" % cond_lbl)
            self._emit("%s:" % end_lbl)
        elif k == "for":
            self._lower_for(stmt)
        elif k == "break":
            if self._loop_stack:
                self._emit("  br label %%%s" % self._loop_stack[-1][1])
        elif k == "continue":
            if self._loop_stack:
                self._emit("  br label %%%s" % self._loop_stack[-1][0])
        elif k == "expr":
            self._lower_expr_typed(stmt["e"])
        else:
            # Unknown statement kind — the checker rejects these; skip.
            return

    def _lower_for(self, stmt: Dict):
        """Lower `for v: T in iter { body }`.

        Mirrors the C backend exactly (BUG-SC-4 semantics):
          - the element count is snapshotted ONCE (appended elements are
            not visited);
          - each iteration re-checks the CURRENT list length and breaks
            when the list has shrunk below the index;
          - the loop variable slot is hoisted to the function entry;
          - the increment lives in its own block, so `continue` jumps to
            the increment (BUG-DS4-5: the increment used to be emitted
            after the continue branch, producing invalid IR).
        """
        iter_ty, iter_val = self._lower_expr_typed(stmt["iter"])
        if self._cur_block is None:
            return
        len_val = self._fresh("len")
        self._emit("  %s = call i64 @hl_list_len(ptr %s)" % (len_val, iter_val))
        i_slot, _ = self._get_slot(stmt["var"] + "#idx", "int")
        self._emit("  store i64 0, ptr %s" % i_slot)
        # Loop variable slot (hoisted; vtype is the element type).
        v_slot, v_ty = self._get_slot(stmt["var"], stmt["vtype"])
        self._locals[stmt["var"]] = (v_slot, v_ty)
        cond_lbl = self._fresh_label("for_cond")
        body_lbl = self._fresh_label("for_body")
        elem_lbl = self._fresh_label("for_elem")
        inc_lbl = self._fresh_label("for_inc")
        end_lbl = self._fresh_label("for_end")
        self._emit("  br label %%%s" % cond_lbl)
        self._emit("%s:" % cond_lbl)
        i_val = self._fresh("i")
        self._emit("  %s = load i64, ptr %s" % (i_val, i_slot))
        cond_tmp = self._fresh("cond")
        self._emit("  %s = icmp slt i64 %s, %s" % (cond_tmp, i_val, len_val))
        self._emit("  br i1 %s, label %%%s, label %%%s" % (
            cond_tmp, body_lbl, end_lbl))
        self._emit("%s:" % body_lbl)
        # Shrink re-check (BUG-SC-4 semantics, same as the C backend).
        cur_len = self._fresh("curlen")
        self._emit("  %s = call i64 @hl_list_len(ptr %s)" % (cur_len, iter_val))
        ok_tmp = self._fresh("ok")
        self._emit("  %s = icmp slt i64 %s, %s" % (ok_tmp, i_val, cur_len))
        self._emit("  br i1 %s, label %%%s, label %%%s" % (
            ok_tmp, elem_lbl, end_lbl))
        self._emit("%s:" % elem_lbl)
        # Fetch + unbox the element by the declared element type.
        elem = self._fresh("elem")
        self._emit("  %s = call ptr @hl_list_get(ptr %s, i64 %s)" % (
            elem, iter_val, i_val))
        unboxed = self._unbox_value(stmt["vtype"], elem)
        self._emit("  store %s %s, ptr %s" % (v_ty, self._coerce(
            hls_type_to_llvm(stmt["vtype"]), unboxed, v_ty), v_slot))
        self._loop_stack.append((inc_lbl, end_lbl))
        for s in stmt["body"]:
            self._lower_stmt(s)
        self._loop_stack.pop()
        if self._cur_block is not None:
            self._emit("  br label %%%s" % inc_lbl)
        # Increment block — also the `continue` target.
        self._emit("%s:" % inc_lbl)
        i_val2 = self._fresh("i")
        self._emit("  %s = load i64, ptr %s" % (i_val2, i_slot))
        inc = self._fresh("inc")
        self._emit("  %s = add i64 %s, 1" % (inc, i_val2))
        self._emit("  store i64 %s, ptr %s" % (inc, i_slot))
        self._emit("  br label %%%s" % cond_lbl)
        self._emit("%s:" % end_lbl)

    def _lower_assign(self, stmt: Dict):
        target = stmt["target"]
        val_ty, val = self._lower_expr_typed(stmt["value"])
        if self._cur_block is None:
            return  # RHS was `never`
        if target["k"] == "ident":
            entry = self._locals.get(target["name"])
            if entry is None:
                # The checker already rejects undefined vars; defensively skip.
                return
            slot, slot_ty = entry
            self._emit("  store %s %s, ptr %s" % (
                slot_ty, self._coerce(val_ty, val, slot_ty), slot))
        elif target["k"] == "field":
            self._lower_field_assign_typed(target, val_ty, val)
        elif target["k"] == "index":
            # Index assignment: box the value by the element type of the
            # target list (BUG-DS4-8: the runtime stores boxed elements).
            lst_ty, lst = self._lower_expr_typed(target["target"])
            idx_ty, idx = self._lower_expr_typed(target["idx"])
            list_t = target["target"].get("t", "list[int]")
            elem_t = _list_elem(list_t) if _is_list(list_t) else "int"
            boxed = self._box_value(elem_t, val_ty, val)
            self._emit("  call void @hl_list_set(ptr %s, i64 %s, ptr %s)" % (
                lst, idx, boxed))

    # ---------- expression lowering ----------
    def _lower_expr_typed(self, e: Dict) -> Tuple[str, str]:
        """Lower an expression; return (llvm_type, llvm_value)."""
        k = e["k"]
        if k == "int":
            return ("i64", str(e["v"]))
        if k == "float":
            return ("double", "%.17e" % e["v"])
        if k == "bool":
            return ("i1", "1" if e["v"] else "0")
        if k == "str":
            data = e["v"]
            if isinstance(data, str):
                data = data.encode("utf-8")
            const_name = self._emit_string_const(data)
            tmp = self._fresh("s")
            self._emit("  %s = call ptr @hl_str_from(ptr @%s, i64 %d)" % (
                tmp, const_name, len(data)))
            return ("ptr", tmp)
        if k == "ident":
            entry = self._locals.get(e["name"])
            if entry is None:
                # Should not happen post-check; defensively return 0.
                return ("i64", "0")
            slot, slot_ty = entry
            tmp = self._fresh("r")
            self._emit("  %s = load %s, ptr %s" % (tmp, slot_ty, slot))
            return (slot_ty, tmp)
        if k == "bin":
            return self._lower_binop_typed(e)
        if k == "un":
            return self._lower_unop_typed(e)
        if k == "call":
            return self._lower_call_typed(e)
        if k == "method" or k == "fieldcall":
            return self._lower_method_typed(e)
        if k == "field":
            return self._lower_field_access_typed(e)
        if k == "index":
            lst_ty, lst = self._lower_expr_typed(e["target"])
            idx_ty, idx = self._lower_expr_typed(e["idx"])
            if self._cur_block is None:
                return ("i64", "0")
            tmp = self._fresh("e")
            self._emit("  %s = call ptr @hl_list_get(ptr %s, i64 %s)" % (
                tmp, lst, idx))
            # Unbox the element according to the (checker-annotated) type.
            et = e.get("t", "int")
            unboxed = self._unbox_value(et, tmp)
            return (hls_type_to_llvm(et), unboxed)
        if k == "listlit":
            tmp = self._fresh("lst")
            # Arena-mode contract: elem_free = null (never release items).
            self._emit("  %s = call ptr @hl_list_new(ptr null)" % tmp)
            # Box each element by the (checker-annotated) element type.
            list_t = e.get("t", "list[int]")
            elem_t = _list_elem(list_t) if _is_list(list_t) else "int"
            for item in e["items"]:
                ity, iv = self._lower_expr_typed(item)
                if self._cur_block is None:
                    break
                boxed = self._box_value(elem_t, ity, iv)
                self._emit("  call void @hl_list_push(ptr %s, ptr %s)" % (tmp, boxed))
            return ("ptr", tmp)
        if k == "structlit":
            return self._lower_structlit_typed(e)
        if k == "match":
            return self._lower_match_typed(e)
        if k == "qmark":
            return self._lower_qmark_typed(e)
        if k == "enumlit":
            return self._lower_enumlit_typed(e)
        # Fallback for unsupported expression kinds.
        _unsupported("expression kind '%s'" % k, e)

    def _lower_structlit_typed(self, e: Dict) -> Tuple[str, str]:
        """Stage 12 release: lower a struct literal via the runtime
        constructor helpers.

        Allocates an opaque struct via `hl_struct_alloc(<size>)`, then
        stores each field via the typed `hl_struct_set_*` helper. The
        field index comes from the checker's `sfields` annotation (a
        list of (name, type) tuples in declaration order). If `sfields`
        is missing (older checker), we fall back to positional indexing.
        """
        name = e.get("name", "?")
        # The checker annotates the resolved struct's field list as `sfields`.
        sfields = e.get("sfields") or []
        if not sfields:
            # Without the field list, we can't dispatch to the right setter.
            _unsupported("struct literal %s (checker did not annotate sfields)" % name, e)
        # Estimate size: 16 bytes per field (covers i64/double/ptr alignment).
        size_bytes = max(16, 16 * len(sfields))
        tmp = self._fresh("st")
        self._emit("  %s = call ptr @hl_struct_alloc(i64 %d)" % (tmp, size_bytes))
        # Set each provided field by its declaration index.
        decl_names = [fname for fname, _ in sfields]
        for fname, fexpr in e.get("fields", []):
            if fname not in decl_names:
                _unsupported("struct literal %s: unknown field '%s'" % (name, fname), e)
            fidx = decl_names.index(fname)
            ftype = sfields[fidx][1]
            fty, fval = self._lower_expr_typed(fexpr)
            if self._cur_block is None:
                return ("ptr", tmp)
            if ftype == "int" or ftype.startswith("tainted[int]"):
                v = self._coerce(fty, fval, "i64")
                self._emit("  call void @hl_struct_set_i64(ptr %s, i64 %d, i64 %s)"
                           % (tmp, fidx, v))
            elif ftype == "float" or ftype.startswith("tainted[float]"):
                v = self._coerce(fty, fval, "double")
                self._emit("  call void @hl_struct_set_f64(ptr %s, i64 %d, double %s)"
                           % (tmp, fidx, v))
            elif ftype == "bool" or ftype.startswith("tainted[bool]"):
                v = self._coerce(fty, fval, "i1")
                self._emit("  call void @hl_struct_set_bool(ptr %s, i64 %d, i1 %s)"
                           % (tmp, fidx, v))
            else:
                v = self._coerce(fty, fval, "ptr")
                self._emit("  call void @hl_struct_set_ptr(ptr %s, i64 %d, ptr %s)"
                           % (tmp, fidx, v))
        return ("ptr", tmp)

    def _lower_enumlit_typed(self, e: Dict) -> Tuple[str, str]:
        """Stage 12 release: lower an enum literal `Variant(...)` via
        `hl_enum_new_variant(idx)`. The checker annotates the variant's
        declaration index as `variant_idx`."""
        idx = e.get("variant_idx")
        if idx is None:
            _unsupported("enum literal (checker did not annotate variant_idx)", e)
        tmp = self._fresh("en")
        self._emit("  %s = call ptr @hl_enum_new_variant(i64 %d)" % (tmp, idx))
        # If the variant has a payload, store it via hl_struct_set_* on the
        # payload pointer. The checker annotates the payload type as
        # `payload_type` (or None for unit variants).
        payload_type = e.get("payload_type")
        if payload_type and e.get("args"):
            payload_ptr = self._fresh("ep")
            self._emit("  %s = call ptr @hl_enum_payload(ptr %s)" % (payload_ptr, tmp))
            pty, pval = self._lower_expr_typed(e["args"][0])
            if self._cur_block is None:
                return ("ptr", tmp)
            if payload_type == "int" or payload_type.startswith("tainted[int]"):
                v = self._coerce(pty, pval, "i64")
                self._emit("  call void @hl_struct_set_i64(ptr %s, i64 0, i64 %s)"
                           % (payload_ptr, v))
            elif payload_type == "float" or payload_type.startswith("tainted[float]"):
                v = self._coerce(pty, pval, "double")
                self._emit("  call void @hl_struct_set_f64(ptr %s, i64 0, double %s)"
                           % (payload_ptr, v))
            elif payload_type == "bool" or payload_type.startswith("tainted[bool]"):
                v = self._coerce(pty, pval, "i1")
                self._emit("  call void @hl_struct_set_bool(ptr %s, i64 0, i1 %s)"
                           % (payload_ptr, v))
            else:
                v = self._coerce(pty, pval, "ptr")
                self._emit("  call void @hl_struct_set_ptr(ptr %s, i64 0, ptr %s)"
                           % (payload_ptr, v))
        return ("ptr", tmp)

    def _lower_match_typed(self, e: Dict) -> Tuple[str, str]:
        """Stage 12 release + deep-scan-7 fix: lower a match expression
        on an enum.

        Lowers to a `switch` on the enum's variant tag (loaded via
        `hl_enum_tag`). Each arm becomes a basic block. The arm body's
        result is stored to a per-match alloca; the result is loaded
        after the end label.

        Deep-scan-7 fix: the previous implementation always returned
        0/null for every match (the comment at the old line 965-968
        explicitly said "return 0/i64 — this matches the existing
        alpha fallback"). This was silent miscompilation — every
        `match` in --emit llvm mode produced 0 regardless of the arm
        body's actual value. The fix uses a per-match alloca: each
        arm stores its result value, and the end block loads it.

        Only matches on enums are supported today (matching on ints/
        strs with full literal patterns is future work).
        """
        scrut_ty, scrut = self._lower_expr_typed(e["scrut"])
        if self._cur_block is None:
            return ("i64", "0")
        # Load the variant tag.
        tag = self._fresh("tag")
        self._emit("  %s = call i64 @hl_enum_tag(ptr %s)" % (tag, scrut))
        # Build a switch over the arms.
        end_lbl = self._fresh_label("match_end")
        arms = e.get("arms", [])
        # Result type is the match expression's annotated type.
        result_t = e.get("t", "int")
        llvm_ret_ty = hls_type_to_llvm(result_t)
        # Deep-scan-7 fix: allocate a slot for the match result. Each
        # arm stores its body's result here; the end block loads it.
        # This is the simplest correct lowering — phi nodes would be
        # more efficient but require tracking every predecessor block.
        # Deep-scan-12 fix (DSS-T-02): emit the alloca in the ENTRY block
        # (the function header at line 430), not in the current basic
        # block. A `match` inside a `while` body would otherwise re-emit
        # the alloca on every iteration; LLVM allocas are not released
        # until function return, so the stack grew without bound. We
        # allocate a per-match slot ONCE in the entry block (keyed by the
        # match's source line so nested matches in the same function get
        # distinct slots), and use it from the current block.
        result_slot = self._fresh("match_result")
        llvm_ret_ty_full = llvm_ret_ty
        self._entry_allocas.append((result_slot, llvm_ret_ty_full))
        # The slot is allocated in the entry block — we just reference it
        # from here on out.
        # Pre-emit each arm as a basic block. Each arm records:
        #   (variant_idx_or_None_for_default, label, body_result_value, body_end_block)
        arm_records = []
        # First pass: emit labels + bodies.
        for arm in arms:
            arm_lbl = self._fresh_label("match_arm")
            var_idx = arm.get("variant_idx")
            arm_records.append([var_idx, arm_lbl, None, None])
        # Default arm (wildcard).
        default_lbl = None
        default_rec = None
        for r in arm_records:
            if r[0] is None:
                default_lbl = r[1]
                default_rec = r
                break
        if default_lbl is None:
            # No wildcard — emit a panic block as the default.
            default_lbl = self._fresh_label("match_panic")
        # Emit the switch.
        cases = [(r[0], r[1]) for r in arm_records if r[0] is not None]
        switch_cases = ", ".join("i64 %d label %%%s" % (idx, lbl)
                                 for idx, lbl in cases)
        if switch_cases:
            self._emit("  switch i64 %s, label %%%s [%s]" % (
                tag, default_lbl, switch_cases))
        else:
            self._emit("  br label %%%s" % default_lbl)
        # Emit the default (panic) block if no wildcard.
        if default_rec is None:
            self._emit("%s:" % default_lbl)
            self._emit('  call void @hl_die(ptr @.panic_overflow_msg)')
            self._emit("  unreachable")
        # Emit each arm body.
        for i, arm in enumerate(arms):
            lbl = arm_records[i][1]
            self._emit("%s:" % lbl)
            # Bind the payload (if any) — the checker annotates the
            # pattern's binding name and the variant's payload type.
            if arm.get("bind_name") and arm.get("payload_type"):
                payload_ptr = self._fresh("ap")
                self._emit("  %s = call ptr @hl_enum_payload(ptr %s)" % (payload_ptr, scrut))
                ptype = arm["payload_type"]
                slot, slot_ty = self._get_slot(arm["bind_name"], ptype)
                self._locals[arm["bind_name"]] = (slot, slot_ty)
                if ptype == "int" or ptype.startswith("tainted[int]"):
                    ptmp = self._fresh("pv")
                    self._emit("  %s = call i64 @hl_struct_get_i64(ptr %s, i64 0)"
                               % (ptmp, payload_ptr))
                    self._emit("  store i64 %s, ptr %s" % (ptmp, slot))
                elif ptype == "float" or ptype.startswith("tainted[float]"):
                    ptmp = self._fresh("pv")
                    self._emit("  %s = call double @hl_struct_get_f64(ptr %s, i64 0)"
                               % (ptmp, payload_ptr))
                    self._emit("  store double %s, ptr %s" % (ptmp, slot))
                elif ptype == "bool" or ptype.startswith("tainted[bool]"):
                    ptmp = self._fresh("pv")
                    self._emit("  %s = call i1 @hl_struct_get_bool(ptr %s, i64 0)"
                               % (ptmp, payload_ptr))
                    self._emit("  store i1 %s, ptr %s" % (ptmp, slot))
                else:
                    ptmp = self._fresh("pv")
                    self._emit("  %s = call ptr @hl_struct_get_ptr(ptr %s, i64 0)"
                               % (ptmp, payload_ptr))
                    self._emit("  store ptr %s, ptr %s" % (ptmp, slot))
            # Lower the arm body. The HLS match arm body is a single
            # EXPRESSION (the parser's `parse_expr`), not a list of
            # statements. Deep-scan-7 fix: the old code iterated
            # `arm["body"]` as if it were a list of statements — but
            # since it's actually a single expression node, the
            # iteration walked the dict's KEYS (strings), causing
            # `AttributeError: 'str' object has no attribute 'get'`.
            body = arm.get("body")
            if isinstance(body, dict):
                # Expression form (the only form parse_arm produces today).
                arm_result_ty, arm_result_val = self._lower_expr_typed(body)
            elif isinstance(body, list):
                # Statement-list form (future-proofing; matches the
                # statement-list lowering used elsewhere). The last
                # `expr` statement's value is the arm's result.
                arm_result_ty = llvm_ret_ty
                arm_result_val = "0" if llvm_ret_ty != "ptr" else "null"
                for s in body:
                    if isinstance(s, dict) and s.get("k") == "expr":
                        arm_result_ty, arm_result_val = self._lower_expr_typed(s["e"])
                    else:
                        self._lower_stmt(s)
            else:
                # No body? Use a zero default.
                arm_result_ty = llvm_ret_ty
                arm_result_val = "0" if llvm_ret_ty != "ptr" else "null"
            # Deep-scan-7 fix: store the arm result to the per-match slot.
            # Cast the value to the match's result type if needed.
            if arm_result_ty != llvm_ret_ty:
                # Coerce — same logic as the assignment path.
                arm_result_val = self._coerce(
                    arm_result_val, arm_result_ty, llvm_ret_ty)
            self._emit("  store %s %s, ptr %s"
                       % (llvm_ret_ty, arm_result_val, result_slot))
            if self._cur_block is not None:
                self._emit("  br label %%%s" % end_lbl)
            arm_records[i][2] = arm_result_ty
            arm_records[i][3] = self._cur_block  # may be None if arm diverged
        # End block — load the match result from the alloca.
        self._emit("%s:" % end_lbl)
        result_val = self._fresh("match_val")
        self._emit("  %s = load %s, ptr %s"
                   % (result_val, llvm_ret_ty, result_slot))
        return (llvm_ret_ty, result_val)

    def _lower_qmark_typed(self, e: Dict) -> Tuple[str, str]:
        """Stage 12 release: lower the `?` operator.

        `expr?` on a `Result[T, E]` enum:
          - if Ok, unwrap to T and continue.
          - if Err, propagate the error to the caller.

        Lowers to: extract the tag, branch on Ok-vs-Err, extract the
        payload, return on Err. The Ok payload is the unwrapped value.
        The checker annotates `qmark_ok_idx` (variant index for Ok) and
        `qmark_err_idx` (variant index for Err).
        """
        scrut_ty, scrut = self._lower_expr_typed(e["e"])
        if self._cur_block is None:
            return ("i64", "0")
        tag = self._fresh("qtag")
        self._emit("  %s = call i64 @hl_enum_tag(ptr %s)" % (tag, scrut))
        ok_idx = e.get("qmark_ok_idx", 0)
        err_idx = e.get("qmark_err_idx", 1)
        ok_lbl = self._fresh_label("qmark_ok")
        err_lbl = self._fresh_label("qmark_err")
        end_lbl = self._fresh_label("qmark_end")
        cond = self._fresh("qcond")
        self._emit("  %s = icmp eq i64 %s, %d" % (cond, tag, ok_idx))
        self._emit("  br i1 %s, label %%%s, label %%%s" % (cond, ok_lbl, err_lbl))
        # Err branch: extract the Err payload and return it from the
        # current function (propagation).
        self._emit("%s:" % err_lbl)
        # Deep-scan-12 fix (DSS-T-15): use the ENCLOSING function's actual
        # return type for the `ret` instruction, not a hardcoded `ret ptr`.
        # The hardcoded `ret ptr` produced invalid IR for any function
        # returning int / float / bool / void — LLVM rejects `ret ptr` in
        # an `i64`-returning function. The Err value is the scrut enum,
        # which is already a ptr; we return it as the function's actual
        # LLVM return type (the enum ptr matches a `ptr` return; for any
        # other return type the function was mis-declared, but that is a
        # checker concern, not a codegen concern — we emit the declared
        # type and let LLVM validate the call chain).
        fn_ret_llvm = hls_type_to_llvm(self._current_ret_type_value) \
            if self._current_ret_type_value else "ptr"
        if fn_ret_llvm == "void":
            # A void function with `?` should never exist (the checker
            # rejects it), but defensive: don't emit a value return.
            self._emit("  ret void")
        else:
            self._emit("  ret %s %s" % (fn_ret_llvm, scrut))
        # Ok branch: extract the Ok payload.
        self._emit("%s:" % ok_lbl)
        payload_ptr = self._fresh("qpayload")
        self._emit("  %s = call ptr @hl_enum_payload(ptr %s)" % (payload_ptr, scrut))
        ok_t = e.get("qmark_ok_type", "int")
        if ok_t == "int" or ok_t.startswith("tainted[int]"):
            tmp = self._fresh("qv")
            self._emit("  %s = call i64 @hl_struct_get_i64(ptr %s, i64 0)"
                       % (tmp, payload_ptr))
            self._emit("  br label %%%s" % end_lbl)
            self._emit("%s:" % end_lbl)
            return ("i64", tmp)
        if ok_t == "float" or ok_t.startswith("tainted[float]"):
            tmp = self._fresh("qv")
            self._emit("  %s = call double @hl_struct_get_f64(ptr %s, i64 0)"
                       % (tmp, payload_ptr))
            self._emit("  br label %%%s" % end_lbl)
            self._emit("%s:" % end_lbl)
            return ("double", tmp)
        if ok_t == "bool" or ok_t.startswith("tainted[bool]"):
            tmp = self._fresh("qv")
            self._emit("  %s = call i1 @hl_struct_get_bool(ptr %s, i64 0)"
                       % (tmp, payload_ptr))
            self._emit("  br label %%%s" % end_lbl)
            self._emit("%s:" % end_lbl)
            return ("i1", tmp)
        # ptr-valued payload.
        tmp = self._fresh("qv")
        self._emit("  %s = call ptr @hl_struct_get_ptr(ptr %s, i64 0)"
                   % (tmp, payload_ptr))
        self._emit("  br label %%%s" % end_lbl)
        self._emit("%s:" % end_lbl)
        return ("ptr", tmp)

    def _lower_unop_typed(self, e: Dict) -> Tuple[str, str]:
        a_ty, a = self._lower_expr_typed(e["e"])
        if self._cur_block is None:
            return ("i64", "0")
        if e["op"] == "-":
            if a_ty == "i64":
                # Checked negation via the runtime (identical panic to the
                # interpreter: -INT64_MIN overflows).
                tmp = self._fresh("u")
                self._emit("  %s = call i64 @hl_neg_i64(i64 %s)" % (tmp, a))
                return ("i64", tmp)
            # float negation
            tmp = self._fresh("u")
            self._emit("  %s = fneg double %s" % (tmp, a))
            return ("double", tmp)
        if e["op"] == "!":
            tmp = self._fresh("u")
            self._emit("  %s = xor i1 %s, 1" % (tmp, a))
            return ("i1", tmp)
        return ("i64", "0")

    # ---------- binary operators ----------
    def _lower_binop_typed(self, e: Dict) -> Tuple[str, str]:
        op = e["op"]
        lt = e["l"].get("t", "int")
        # BUG-DS4-9: && and || must SHORT-CIRCUIT (the interpreter does).
        # Lowering them as eager `and`/`or` evaluated the RHS even when the
        # LHS already decided the result — `x != 0 && 10 / x > 0` panicked
        # on division by zero under the LLVM backend but not in the
        # interpreter. Now lowered as control flow + phi.
        if op == "&&" or op == "||":
            return self._lower_shortcircuit_typed(e)
        a_ty, a = self._lower_expr_typed(e["l"])
        if self._cur_block is None:
            return ("i1", "0")
        b_ty, b = self._lower_expr_typed(e["r"])
        if self._cur_block is None:
            return ("i1", "0")
        # String operations.
        if lt == "str":
            return self._lower_str_binop(op, a, b)
        # Float operations (comparisons produce i1 — no widening).
        if lt == "float":
            return self._lower_float_binop(op, a, b)
        # Bool equality.
        if lt == "bool":
            if op == "==":
                tmp = self._fresh("r")
                self._emit("  %s = icmp eq i1 %s, %s" % (tmp, a, b))
                return ("i1", tmp)
            if op == "!=":
                tmp = self._fresh("r")
                self._emit("  %s = icmp ne i1 %s, %s" % (tmp, a, b))
                return ("i1", tmp)
            # Checker rejects ordering / arithmetic on bool.
            _unsupported("operator '%s' on bool" % op, e)
        # Integer arithmetic with overflow checks; division/modulo via the
        # runtime (zero + INT64_MIN/-1 panics identical to the interpreter
        # and the C backend).
        if op == "+":
            return ("i64", self._emit_overflow_op("llvm.sadd.with.overflow.i64", a, b))
        if op == "-":
            return ("i64", self._emit_overflow_op("llvm.ssub.with.overflow.i64", a, b))
        if op == "*":
            return ("i64", self._emit_overflow_op("llvm.smul.with.overflow.i64", a, b))
        if op == "/":
            tmp = self._fresh("r")
            self._emit("  %s = call i64 @hl_div_i64(i64 %s, i64 %s)" % (tmp, a, b))
            return ("i64", tmp)
        if op == "%":
            tmp = self._fresh("r")
            self._emit("  %s = call i64 @hl_mod_i64(i64 %s, i64 %s)" % (tmp, a, b))
            return ("i64", tmp)
        # Integer comparisons (i1 results — BUG-DS4-4: previously every
        # comparison was zext'ed to i64, so storing into a bool slot or
        # branching on it produced invalid IR).
        icmp_map = {"==": "eq", "!=": "ne",
                    "<": "slt", "<=": "sle", ">": "sgt", ">=": "sge"}
        if op in icmp_map:
            tmp = self._fresh("r")
            self._emit("  %s = icmp %s i64 %s, %s" % (tmp, icmp_map[op], a, b))
            return ("i1", tmp)
        _unsupported("operator '%s'" % op, e)

    def _lower_shortcircuit_typed(self, e: Dict) -> Tuple[str, str]:
        """Lower `a && b` / `a || b` with REAL short-circuit semantics:
        the RHS is only evaluated when the LHS leaves the result undecided.
        Uses two extra blocks and a phi node (no temp alloca, so loops
        don't grow the stack)."""
        op = e["op"]
        la_ty, la = self._lower_expr_typed(e["l"])
        if self._cur_block is None:
            return ("i1", "0")
        la = self._to_i1(la_ty, la)
        lhs_block = self._cur_block  # block the LHS ended in (open)
        n = self._sc_counter
        self._sc_counter += 1
        rhs_lbl = "sc_rhs_%d" % n
        end_lbl = "sc_end_%d" % n
        if op == "&&":
            # LHS false -> result is false; skip the RHS entirely.
            self._emit("  br i1 %s, label %%%s, label %%%s" % (la, rhs_lbl, end_lbl))
        else:  # "||"
            # LHS true -> result is true; skip the RHS entirely.
            self._emit("  br i1 %s, label %%%s, label %%%s" % (la, end_lbl, rhs_lbl))
        self._emit("%s:" % rhs_lbl)
        rb_ty, rb = self._lower_expr_typed(e["r"])
        if self._cur_block is None:
            # RHS was `never` (panic/exit): the block is closed. The value
            # along that edge is unreachable — use 0 as a placeholder.
            rhs_block = None
            rb_i1 = "0"
        else:
            rhs_block = self._cur_block
            rb_i1 = self._to_i1(rb_ty, rb)
            self._emit("  br label %%%s" % end_lbl)
        self._emit("%s:" % end_lbl)
        # phi: value along the short-circuit edge is 0 for && (false),
        # 1 for || (true); value along the RHS edge is the RHS result.
        short_val = "0" if op == "&&" else "1"
        tmp = self._fresh("sc")
        if rhs_block is not None:
            self._emit("  %s = phi i1 [ %s, %%%s ], [ %s, %%%s ]" % (
                tmp, short_val, lhs_block, rb_i1, rhs_block))
        else:
            # Degenerate case: RHS diverges — the phi has one real edge.
            self._emit("  %s = phi i1 [ %s, %%%s ]" % (tmp, short_val, lhs_block))
        return ("i1", tmp)

    def _lower_str_binop(self, op, a, b) -> Tuple[str, str]:
        if op == "+":
            tmp = self._fresh("cat")
            self._emit("  %s = call ptr @hl_str_concat(ptr %s, ptr %s)" % (tmp, a, b))
            return ("ptr", tmp)
        if op == "==":
            tmp = self._fresh("r")
            self._emit("  %s = call i1 @hl_str_eq(ptr %s, ptr %s)" % (tmp, a, b))
            return ("i1", tmp)
        if op == "!=":
            eq = self._fresh("eq")
            self._emit("  %s = call i1 @hl_str_eq(ptr %s, ptr %s)" % (eq, a, b))
            tmp = self._fresh("r")
            self._emit("  %s = xor i1 %s, 1" % (tmp, eq))
            return ("i1", tmp)
        # BUG-DS4-10: string relational comparisons used to fall into the
        # INTEGER path (icmp on pointers — invalid IR and wrong semantics).
        # Route them through hl_str_cmp like the C backend.
        cmp_map = {"<": "slt", "<=": "sle", ">": "sgt", ">=": "sge"}
        if op in cmp_map:
            c = self._fresh("c")
            self._emit("  %s = call i64 @hl_str_cmp(ptr %s, ptr %s)" % (c, a, b))
            tmp = self._fresh("r")
            self._emit("  %s = icmp %s i64 %s, 0" % (tmp, cmp_map[op], c))
            return ("i1", tmp)
        _unsupported("operator '%s' on str" % op, {"line": 0})

    def _lower_float_binop(self, op, a, b) -> Tuple[str, str]:
        tmp = self._fresh("r")
        if op == "+":
            self._emit("  %s = fadd double %s, %s" % (tmp, a, b))
            return ("double", tmp)
        if op == "-":
            self._emit("  %s = fsub double %s, %s" % (tmp, a, b))
            return ("double", tmp)
        if op == "*":
            self._emit("  %s = fmul double %s, %s" % (tmp, a, b))
            return ("double", tmp)
        if op == "/":
            self._emit("  %s = fdiv double %s, %s" % (tmp, a, b))
            return ("double", tmp)
        if op == "%":
            self._emit("  %s = frem double %s, %s" % (tmp, a, b))
            return ("double", tmp)
        fcmp_map = {"==": "oeq", "!=": "one",
                    "<": "olt", "<=": "ole", ">": "ogt", ">=": "oge"}
        if op in fcmp_map:
            self._emit("  %s = fcmp %s double %s, %s" % (tmp, fcmp_map[op], a, b))
            return ("i1", tmp)
        _unsupported("operator '%s' on float" % op, {"line": 0})

    def _emit_overflow_op(self, llvm_intrinsic: str, a: str, b: str) -> str:
        """Emit a checked overflow operation; return the result SSA name."""
        n = self._ov_counter
        self._ov_counter += 1
        res = self._fresh("ov_res")
        self._emit("  %s = call { i64, i1 } @%s(i64 %s, i64 %s)" % (
            res, llvm_intrinsic, a, b))
        out = self._fresh("r")
        self._emit("  %s = extractvalue { i64, i1 } %s, 0" % (out, res))
        ovf = self._fresh("ov")
        self._emit("  %s = extractvalue { i64, i1 } %s, 1" % (ovf, res))
        panic_lbl = "ov_panic_%d" % n
        ok_lbl = "ov_ok_%d" % n
        self._emit("  br i1 %s, label %%%s, label %%%s" % (ovf, panic_lbl, ok_lbl))
        self._emit("%s:" % panic_lbl)
        self._emit("  call void @hl_die(ptr @.panic_overflow_msg)")
        self._emit("  unreachable")
        self._emit("%s:" % ok_lbl)
        return out

    # ---------- boxing helpers (list/map element ABI) ----------
    def _box_value(self, hls_ty: str, val_ty: str, val: str) -> str:
        """Box a primitive value for storage in a dynamic list/map.
        Heap types (str, list, map, ...) are stored as raw pointers."""
        if hls_ty == "int" or hls_ty.startswith("tainted[int]"):
            v = self._coerce(val_ty, val, "i64")
            tmp = self._fresh("box")
            self._emit("  %s = call ptr @hl_box_i64(i64 %s)" % (tmp, v))
            return tmp
        if hls_ty == "float" or hls_ty.startswith("tainted[float]"):
            v = self._coerce(val_ty, val, "double")
            tmp = self._fresh("box")
            self._emit("  %s = call ptr @hl_box_f64(double %s)" % (tmp, v))
            return tmp
        if hls_ty == "bool" or hls_ty.startswith("tainted[bool]"):
            v = self._coerce(val_ty, val, "i1")
            tmp = self._fresh("box")
            self._emit("  %s = call ptr @hl_box_bool(i1 %s)" % (tmp, v))
            return tmp
        # ptr-valued: use as-is (matches the C backend's box_ptr).
        return val

    def _unbox_value(self, hls_ty: str, box: str) -> str:
        """Unbox a dynamic list/map element (a box pointer) to the element's
        LLVM value. Mirrors the C backend's gen_unbox: primitives load
        through the box pointer; heap types pass through unchanged."""
        if hls_ty == "int" or hls_ty.startswith("tainted[int]"):
            tmp = self._fresh("ub")
            self._emit("  %s = load i64, ptr %s" % (tmp, box))
            return tmp
        if hls_ty == "float" or hls_ty.startswith("tainted[float]"):
            tmp = self._fresh("ub")
            self._emit("  %s = load double, ptr %s" % (tmp, box))
            return tmp
        if hls_ty == "bool" or hls_ty.startswith("tainted[bool]"):
            tmp = self._fresh("ub")
            self._emit("  %s = load i1, ptr %s" % (tmp, box))
            return tmp
        return box

    def _coerce(self, val_ty: str, val: str, want_ty: str) -> str:
        """Coerce a value between compatible LLVM types (defensive).

        SCAN-A fix: added i1→double and ptr→double paths (used when a
        bool/str is passed to a float parameter — defensive coercion
        that the checker should reject, but the LLVM backend must not
        emit invalid IR for)."""
        if val_ty == want_ty:
            return val
        if val_ty == "i1" and want_ty == "i64":
            tmp = self._fresh("z")
            self._emit("  %s = zext i1 %s to i64" % (tmp, val))
            return tmp
        if val_ty == "i64" and want_ty == "i1":
            tmp = self._fresh("t")
            self._emit("  %s = trunc i64 %s to i1" % (tmp, val))
            return tmp
        if val_ty == "i64" and want_ty == "ptr":
            tmp = self._fresh("i2p")
            self._emit("  %s = inttoptr i64 %s to ptr" % (tmp, val))
            return tmp
        if val_ty == "ptr" and want_ty == "i64":
            tmp = self._fresh("p2i")
            self._emit("  %s = ptrtoint ptr %s to i64" % (tmp, val))
            return tmp
        if val_ty == "i64" and want_ty == "double":
            tmp = self._fresh("s2d")
            self._emit("  %s = sitofp i64 %s to double" % (tmp, val))
            return tmp
        # SCAN-A fix: i1 → double (via i64 widening, then signed-to-float).
        if val_ty == "i1" and want_ty == "double":
            tmp_i64 = self._fresh("z2d")
            self._emit("  %s = zext i1 %s to i64" % (tmp_i64, val))
            tmp = self._fresh("b2d")
            self._emit("  %s = sitofp i64 %s to double" % (tmp, tmp_i64))
            return tmp
        # SCAN-A fix: ptr → double (ptrtoint to i64, then sitofp).
        if val_ty == "ptr" and want_ty == "double":
            tmp_i64 = self._fresh("p2i_d")
            self._emit("  %s = ptrtoint ptr %s to i64" % (tmp_i64, val))
            tmp = self._fresh("p2d")
            self._emit("  %s = sitofp i64 %s to double" % (tmp, tmp_i64))
            return tmp
        # Deep-scan-7 fix: double -> i64. The C backend's
        # `hl_float_to_int` (declared at line 130) range-checks the
        # input and panics on NaN / out-of-range values (mirroring the
        # interpreter's behavior). The LLVM backend's previous direct
        # `fptosi` was a SILENT MISCOMPILATION: NaN produced 0 in LLVM
        # but panicked in C; values > INT64_MAX wrapped to INT64_MIN in
        # LLVM (UB) but panicked in C. The fix delegates to the same
        # range-checked runtime helper the C backend uses, restoring
        # differential parity.
        if val_ty == "double" and want_ty == "i64":
            tmp = self._fresh("d2s")
            self._emit("  %s = call i64 @hl_float_to_int(double %s)"
                       % (tmp, val))
            return tmp
        return val

    # ---------- calls ----------
    def _lower_call_typed(self, e: Dict) -> Tuple[str, str]:
        """Lower a function call. Builtin calls map to the REAL runtime
        functions (same dispatch as the C backend's gen_call)."""
        name = e["name"]
        rc = e.get("rc")  # ("builtin", name) or ("user", name) — set by the checker
        # BUG (deep-scan-5): a never-typed argument (e.g. panic()) in a
        # non-final position closed the block; the remaining args were
        # still lowered, emitting instructions AFTER the terminator.
        # Stop lowering as soon as the block closes.
        arg_pairs = []
        for a in e["args"]:
            if self._cur_block is None:
                break
            arg_pairs.append(self._lower_expr_typed(a))
        if self._cur_block is None:
            return ("void", "0")

        # ---- builtins ----
        if rc is None or rc[0] == "builtin":
            return self._lower_builtin_call(name, e, arg_pairs)

        # ---- user-defined function call ----
        fn = self.program["fns"].get(name)
        ret_ty = hls_type_to_llvm(fn["ret"]) if fn else "ptr"
        param_tys = [hls_type_to_llvm(p[1]) for p in fn["params"]] if fn else (
            ["i64"] * len(arg_pairs))
        arg_str = ", ".join(
            "%s %s" % (pt, self._coerce(aty, aval, pt))
            for (aty, aval), pt in zip(arg_pairs, param_tys))
        if ret_ty == "void":
            self._emit("  call void @%s(%s)" % (name, arg_str))
            return ("void", "0")
        tmp = self._fresh("call")
        self._emit("  %s = call %s @%s(%s)" % (tmp, ret_ty, name, arg_str))
        return (ret_ty, tmp)

    def _call1(self, ret_ty: str, sym: str, arg_tys: List[str],
               arg_pairs: List[Tuple[str, str]]) -> Tuple[str, str]:
        """Helper: emit `call ret_ty @sym(coerced args)` and return the
        (type, value) pair."""
        args = []
        for (aty, aval), want in zip(arg_pairs, arg_tys):
            args.append("%s %s" % (want, self._coerce(aty, aval, want)))
        arg_str = ", ".join(args)
        if ret_ty == "void":
            self._emit("  call void %s(%s)" % (sym, arg_str))
            return ("void", "0")
        tmp = self._fresh("call")
        self._emit("  %s = call %s %s(%s)" % (tmp, ret_ty, sym, arg_str))
        return (ret_ty, tmp)

    def _lower_builtin_call(self, name, e, arg_pairs) -> Tuple[str, str]:
        # Dispatch table mirroring the C backend's gen_call (hlc.hls).
        if name in ("print", "println"):
            return self._call1("void", "@hl_print" if name == "print" else "@hl_println",
                               ["ptr"], arg_pairs)
        if name == "panic":
            # hl_panic never returns: emit call + unreachable so no
            # instructions follow in this block.
            self._call1("void", "@hl_panic", ["ptr"], arg_pairs)
            self._emit("  unreachable")
            return ("void", "0")
        if name == "exit":
            self._call1("void", "@hl_exit", ["i64"], arg_pairs)
            self._emit("  unreachable")
            return ("void", "0")
        if name == "str":
            at = e["args"][0].get("t", "int") if e["args"] else "int"
            if at == "int":
                return self._call1("ptr", "@hl_str_from_int64", ["i64"], arg_pairs)
            if at == "float":
                return self._call1("ptr", "@hl_str_from_double", ["double"], arg_pairs)
            if at == "bool":
                return self._call1("ptr", "@hl_str_from_bool", ["i1"], arg_pairs)
            return arg_pairs[0] if arg_pairs else ("ptr", "null")
        if name == "int":
            return self._call1("i64", "@hl_str_to_int", ["ptr"], arg_pairs)
        if name == "len":
            at = e["args"][0].get("t", "str") if e["args"] else "str"
            if at == "str":
                return self._call1("i64", "@hl_str_len", ["ptr"], arg_pairs)
            if _is_list(at):
                return self._call1("i64", "@hl_list_len", ["ptr"], arg_pairs)
            return self._call1("i64", "@hl_map_len", ["ptr"], arg_pairs)
        if name == "range":
            return self._call1("ptr", "@hl_range", ["i64", "i64"], arg_pairs)
        # Stage 19 (v0.35.0-alpha): O(n) join(list[str], sep) -> str.
        if name == "join":
            return self._call1("ptr", "@hl_str_join", ["ptr", "ptr"], arg_pairs)
        # Stage 21 (v0.37.0-alpha): has_feature — const-folded from the
        # --target-feature flag (boot.py annotates the program dict).
        if name == "has_feature":
            lit = e["args"][0].get("v", "") if e["args"] else ""
            if isinstance(lit, bytes):
                lit = lit.decode("utf-8", "replace")
            feat = self.program.get("target_feature") or ""
            return ("i1", "1" if lit == feat else "0")
        # Stage 21: simd_cpu_supports — runtime CPU probe.
        if name == "simd_cpu_supports":
            return self._call1("i1", "@hl_simd_cpu_supports", ["ptr"], arg_pairs)
        if name == "map_new":
            tmp = self._fresh("map")
            # Arena-mode contract: val_free = null (never release values).
            self._emit("  %s = call ptr @hl_map_new(ptr null)" % tmp)
            return ("ptr", tmp)
        if name == "read_file":
            return self._call1("ptr", "@hl_read_file", ["ptr"], arg_pairs)
        if name == "read_file_tainted":
            # Taint is compile-time only (same as the C backend).
            return self._call1("ptr", "@hl_read_file", ["ptr"], arg_pairs)
        if name == "write_file":
            return self._call1("void", "@hl_write_file", ["ptr", "ptr"], arg_pairs)
        if name == "args":
            tmp = self._fresh("call")
            self._emit("  %s = call ptr @hl_args()" % tmp)
            return ("ptr", tmp)
        if name == "tainted_args":
            # Runtime: same as args() (taint is compile-time only).
            tmp = self._fresh("call")
            self._emit("  %s = call ptr @hl_args()" % tmp)
            return ("ptr", tmp)
        if name == "taint_mark":
            # Identity at runtime.
            return arg_pairs[0]
        if name == "taint_unwrap":
            # Identity at runtime.
            return arg_pairs[0]
        if name == "chr":
            return self._call1("ptr", "@hl_chr", ["i64"], arg_pairs)
        if name == "clock_ms":
            tmp = self._fresh("call")
            self._emit("  %s = call i64 @hl_clock_ms()" % tmp)
            return ("i64", tmp)
        if name == "file_exists":
            return self._call1("i1", "@hl_file_exists", ["ptr"], arg_pairs)
        if name == "drop":
            # Compile-time annotation only; runtime no-op.
            return ("void", "0")
        if name == "take":
            # Compile-time move; runtime returns the value itself.
            return arg_pairs[0]
        if name == "clone":
            at = e["args"][0].get("t", "str") if e["args"] else "str"
            if at == "str":
                return self._call1("ptr", "@hl_clone_str", ["ptr"], arg_pairs)
            if _is_list(at):
                elem = _list_elem(at)
                suffix = {"int": "int", "float": "float", "bool": "bool",
                          "str": "str"}.get(elem)
                if suffix:
                    return self._call1("ptr", "@hl_clone_list_%s" % suffix,
                                       ["ptr"], arg_pairs)
                _unsupported("clone() on list[%s]" % elem, e)
            if _is_map(at):
                vt = _map_val(at)
                suffix = {"int": "int", "float": "float", "bool": "bool",
                          "str": "str"}.get(vt)
                if suffix:
                    return self._call1("ptr", "@hl_clone_map_%s" % suffix,
                                       ["ptr"], arg_pairs)
                _unsupported("clone() on map[str, %s]" % vt, e)
            _unsupported("clone() on type %s" % at, e)
        _unsupported("builtin function '%s'" % name, e)

    # ---------- method calls ----------
    def _lower_method_typed(self, e: Dict) -> Tuple[str, str]:
        """Lower a method call using the checker's `rm` annotation
        (("builtin", op) or ("user", key)). BUILTIN methods map 1:1 to the
        runtime functions the C backend uses (gen_method in hlc.hls);
        USER-defined struct methods are not yet supported (clean error)."""
        rm = e.get("rm")
        if rm is None or rm[0] != "builtin":
            _unsupported("call to user-defined method '%s'" % e.get("name"), e)
        op = rm[1]
        recv_ty, recv = self._lower_expr_typed(e["target"])
        if self._cur_block is None:
            return ("i64", "0")
        # BUG (deep-scan-5): stop lowering args once a never-typed
        # argument closes the block (see _lower_call_typed).
        arg_pairs = []
        for a in e["args"]:
            if self._cur_block is None:
                break
            arg_pairs.append(self._lower_expr_typed(a))
        if self._cur_block is None:
            return ("i64", "0")
        recv_t = e["target"].get("t", "int")

        # ---- str.* ----
        if op.startswith("str."):
            table = {
                "str.len":         ("i64", "@hl_str_len", ["ptr"]),
                "str.byte_at":     ("i64", "@hl_str_byte_at", ["ptr", "i64"]),
                "str.slice":       ("ptr", "@hl_str_slice", ["ptr", "i64", "i64"]),
                "str.find":        ("i64", "@hl_str_find", ["ptr", "ptr"]),
                "str.contains":    ("i1", "@hl_str_contains", ["ptr", "ptr"]),
                "str.starts_with": ("i1", "@hl_str_starts_with", ["ptr", "ptr"]),
                "str.ends_with":   ("i1", "@hl_str_ends_with", ["ptr", "ptr"]),
                "str.split":       ("ptr", "@hl_str_split", ["ptr", "ptr"]),
                "str.trim":        ("ptr", "@hl_str_trim", ["ptr"]),
                "str.to_int":      ("i64", "@hl_str_to_int", ["ptr"]),
                "str.to_float":    ("double", "@hl_str_to_double", ["ptr"]),
                "str.to_str":      (None, None, ["ptr"]),
            }
            entry = table.get(op)
            if entry is None:
                _unsupported("method '%s'" % op, e)
            ret_ty, sym, arg_tys = entry
            if op == "str.to_str":
                return (recv_ty, recv)
            full = [("ptr", recv)] + list(arg_pairs)
            return self._call1(ret_ty, sym, arg_tys, full)

        # ---- int.* ----
        if op.startswith("int."):
            if op == "int.to_str":
                return self._call1("ptr", "@hl_str_from_int64", ["i64"],
                                   [("i64", recv)] + arg_pairs)
            if op == "int.to_float":
                tmp = self._fresh("s2d")
                self._emit("  %s = sitofp i64 %s to double" % (tmp, recv))
                return ("double", tmp)
            if op == "int.abs":
                return self._call1("i64", "@hl_abs_i64", ["i64"],
                                   [("i64", recv)] + arg_pairs)
            _unsupported("method '%s'" % op, e)

        # ---- float.* ----
        if op.startswith("float."):
            if op == "float.to_str":
                return self._call1("ptr", "@hl_str_from_double", ["double"],
                                   [("double", recv)] + arg_pairs)
            if op == "float.to_int":
                return self._call1("i64", "@hl_float_to_int", ["double"],
                                   [("double", recv)] + arg_pairs)
            if op == "float.abs":
                tmp = self._fresh("fa")
                self._emit("  %s = call double @llvm.fabs.f64(double %s)" % (tmp, recv))
                return ("double", tmp)
            _unsupported("method '%s'" % op, e)

        # ---- bool.* ----
        if op.startswith("bool."):
            if op == "bool.to_str":
                return self._call1("ptr", "@hl_str_from_bool", ["i1"],
                                   [("i1", recv)] + arg_pairs)
            _unsupported("method '%s'" % op, e)

        # ---- list.* (boxed element ABI) ----
        if op.startswith("list."):
            elem_t = _list_elem(recv_t) if _is_list(recv_t) else "int"
            if op == "list.len":
                return self._call1("i64", "@hl_list_len", ["ptr"], [("ptr", recv)])
            if op == "list.push":
                # Box the pushed value by the element type.
                vty, v = arg_pairs[0]
                boxed = self._box_value(elem_t, vty, v)
                self._emit("  call void @hl_list_push(ptr %s, ptr %s)" % (recv, boxed))
                return ("void", "0")
            if op == "list.get":
                tmp = self._fresh("e")
                self._emit("  %s = call ptr @hl_list_get(ptr %s, i64 %s)" % (
                    tmp, recv, self._coerce(arg_pairs[0][0], arg_pairs[0][1], "i64")))
                ret_t = e.get("t", elem_t)
                unboxed = self._unbox_value(ret_t, tmp)
                return (hls_type_to_llvm(ret_t), unboxed)
            if op == "list.set":
                idx = self._coerce(arg_pairs[0][0], arg_pairs[0][1], "i64")
                vty, v = arg_pairs[1]
                boxed = self._box_value(elem_t, vty, v)
                self._emit("  call void @hl_list_set(ptr %s, i64 %s, ptr %s)" % (
                    recv, idx, boxed))
                return ("void", "0")
            if op == "list.pop":
                # SCAN-A fix: strip `tainted[...]` from the element type
                # before dispatching — `list[tainted[int]].pop()` was
                # falling through to the generic `hl_list_pop` (returns
                # ptr) instead of `hl_list_pop_i64` (returns i64 + frees
                # the box), producing invalid IR.
                base_elem_t = _taint_inner(elem_t) if elem_t.startswith("tainted[") else elem_t
                if base_elem_t == "int":
                    tmp = self._fresh("pop")
                    self._emit("  %s = call i64 @hl_list_pop_i64(ptr %s)" % (tmp, recv))
                    return ("i64", tmp)
                if base_elem_t == "float":
                    tmp = self._fresh("pop")
                    self._emit("  %s = call double @hl_list_pop_f64(ptr %s)" % (tmp, recv))
                    return ("double", tmp)
                if base_elem_t == "bool":
                    tmp = self._fresh("pop")
                    self._emit("  %s = call i1 @hl_list_pop_bool(ptr %s)" % (tmp, recv))
                    return ("i1", tmp)
                tmp = self._fresh("e")
                self._emit("  %s = call ptr @hl_list_pop(ptr %s)" % (tmp, recv))
                ret_t = e.get("t", elem_t)
                return (hls_type_to_llvm(ret_t), tmp)
            _unsupported("method '%s'" % op, e)

        # ---- map.* (boxed value ABI) ----
        if op.startswith("map."):
            val_t = _map_val(recv_t) if _is_map(recv_t) else "int"
            if op == "map.len":
                return self._call1("i64", "@hl_map_len", ["ptr"], [("ptr", recv)])
            if op == "map.set":
                k = self._coerce(arg_pairs[0][0], arg_pairs[0][1], "ptr")
                vty, v = arg_pairs[1]
                boxed = self._box_value(val_t, vty, v)
                self._emit("  call void @hl_map_set(ptr %s, ptr %s, ptr %s)" % (
                    recv, k, boxed))
                return ("void", "0")
            if op == "map.get_or":
                # BUG (deep-scan-5): the old code called hl_map_get(m, k,
                # boxed-default) — a runtime symbol that no longer exists
                # (the C runtime now has typed getters with defaults passed
                # BY VALUE). Dispatch to the typed getter, mirroring the C
                # backend. (The LLVM backend is arena-mode, so pointer-
                # valued maps use the typed getters' borrow semantics —
                # hl_map_get_own is refcount-specific.)
                k = self._coerce(arg_pairs[0][0], arg_pairs[0][1], "ptr")
                vty, d = arg_pairs[1]
                if val_t == "int":
                    dv = self._coerce(vty, d, "i64")
                    tmp = self._fresh("gv")
                    self._emit("  %s = call i64 @hl_map_get_i64(ptr %s, ptr %s, i64 %s)" % (
                        tmp, recv, k, dv))
                    return ("i64", tmp)
                if val_t == "float":
                    dv = self._coerce(vty, d, "double")
                    tmp = self._fresh("gv")
                    self._emit("  %s = call double @hl_map_get_f64(ptr %s, ptr %s, double %s)" % (
                        tmp, recv, k, dv))
                    return ("double", tmp)
                if val_t == "bool":
                    dv = self._coerce(vty, d, "i1")
                    tmp = self._fresh("gv")
                    self._emit("  %s = call i1 @hl_map_get_bool(ptr %s, ptr %s, i1 %s)" % (
                        tmp, recv, k, dv))
                    return ("i1", tmp)
                # Pointer-valued map: use the generic borrow lookup via
                # hl_map_has + hl_map_get_own is refcount-specific; the
                # arena contract lets us reuse hl_map_borrow.
                tmp = self._fresh("gv")
                self._emit("  %s = call ptr @hl_map_borrow(ptr %s, ptr %s)" % (tmp, recv, k))
                ret_t = e.get("t", val_t)
                cmp_tmp = self._fresh("gvnull")
                self._emit("  %s = icmp ne ptr %s, null" % (cmp_tmp, tmp))
                d2 = self._coerce(vty, d, "ptr")
                sel = self._fresh("gvsel")
                self._emit("  %s = select i1 %s, ptr %s, ptr %s" % (sel, cmp_tmp, tmp, d2))
                return (hls_type_to_llvm(ret_t), sel)
            if op == "map.has":
                k = self._coerce(arg_pairs[0][0], arg_pairs[0][1], "ptr")
                tmp = self._fresh("has")
                self._emit("  %s = call i1 @hl_map_has(ptr %s, ptr %s)" % (tmp, recv, k))
                return ("i1", tmp)
            if op == "map.keys":
                return self._call1("ptr", "@hl_map_keys", ["ptr"], [("ptr", recv)])
            _unsupported("method '%s'" % op, e)

        _unsupported("method '%s'" % op, e)

    # ---------- struct field access ----------
    def _lower_field_access_typed(self, e: Dict) -> Tuple[str, str]:
        """Stage 12 release: lower `expr.field` via the typed
        `hl_struct_get_*` runtime helpers. The checker annotates the
        field's declaration index as `field_idx` and the field's HLS
        type as `t`."""
        target_ty, target_val = self._lower_expr_typed(e["target"])
        if self._cur_block is None:
            return ("i64", "0")
        fidx = e.get("field_idx")
        if fidx is None:
            _unsupported("struct field access (checker did not annotate field_idx)", e)
        ftype = e.get("t", "int")
        if ftype == "int" or ftype.startswith("tainted[int]"):
            tmp = self._fresh("fld")
            self._emit("  %s = call i64 @hl_struct_get_i64(ptr %s, i64 %d)"
                       % (tmp, target_val, fidx))
            return ("i64", tmp)
        if ftype == "float" or ftype.startswith("tainted[float]"):
            tmp = self._fresh("fld")
            self._emit("  %s = call double @hl_struct_get_f64(ptr %s, i64 %d)"
                       % (tmp, target_val, fidx))
            return ("double", tmp)
        if ftype == "bool" or ftype.startswith("tainted[bool]"):
            tmp = self._fresh("fld")
            self._emit("  %s = call i1 @hl_struct_get_bool(ptr %s, i64 %d)"
                       % (tmp, target_val, fidx))
            return ("i1", tmp)
        tmp = self._fresh("fld")
        self._emit("  %s = call ptr @hl_struct_get_ptr(ptr %s, i64 %d)"
                   % (tmp, target_val, fidx))
        return ("ptr", tmp)

    def _lower_field_assign_typed(self, target: Dict, val_ty: str, val: str):
        """Stage 12 release: lower `expr.field = value` via the typed
        `hl_struct_set_*` runtime helpers."""
        target_ty, target_val = self._lower_expr_typed(target["target"])
        if self._cur_block is None:
            return
        fidx = target.get("field_idx")
        if fidx is None:
            _unsupported("struct field assignment (no field_idx annotation)", target)
        ftype = target.get("t", "int")
        if ftype == "int" or ftype.startswith("tainted[int]"):
            v = self._coerce(val_ty, val, "i64")
            self._emit("  call void @hl_struct_set_i64(ptr %s, i64 %d, i64 %s)"
                       % (target_val, fidx, v))
        elif ftype == "float" or ftype.startswith("tainted[float]"):
            v = self._coerce(val_ty, val, "double")
            self._emit("  call void @hl_struct_set_f64(ptr %s, i64 %d, double %s)"
                       % (target_val, fidx, v))
        elif ftype == "bool" or ftype.startswith("tainted[bool]"):
            v = self._coerce(val_ty, val, "i1")
            self._emit("  call void @hl_struct_set_bool(ptr %s, i64 %d, i1 %s)"
                       % (target_val, fidx, v))
        else:
            v = self._coerce(val_ty, val, "ptr")
            self._emit("  call void @hl_struct_set_ptr(ptr %s, i64 %d, ptr %s)"
                       % (target_val, fidx, v))

    # ---------- string constant emission ----------
    def _emit_string_const(self, data: bytes) -> str:
        """Emit a global string constant. Returns the global name."""
        self._str_counter += 1
        name = ".str.%d" % self._str_counter
        if data:
            bytes_str = ", ".join("i8 %d" % b for b in data) + ", i8 0"
        else:
            bytes_str = "i8 0"
        self._string_consts.append((name, data, bytes_str))
        return name


def emit_module(program, target_triple: Optional[str] = None) -> str:
    """Convenience: emit LLVM IR for a checked program."""
    return LLVMEmitter(program, target_triple).emit()
