"""cmds - verbatim segment of the original tools/hls-pkg.py(split for maintainability; behavior unchanged)."""
from __future__ import annotations
import os as _os
import sys as _sys
_TOOLS_DIR = _os.path.dirname(_os.path.abspath(__file__))
if _TOOLS_DIR not in _sys.path:
    _sys.path.insert(0, _TOOLS_DIR)
from hpkg_common import (
    CACHE_DIR, Dict, Optional, REPO_ROOT, TRANSPARENCY_LOG, _re_mod, hashlib, json,
    os, subprocess, sys, time,
)
from hpkg_deps import (
    extract_effects, git_current_commit, resolve_dependency,
)
from hpkg_log import (
    transparency_log_append, transparency_log_lookup, transparency_log_verify_chain,
)
from hpkg_manifest import (
    parse_manifest, write_manifest,
)
from hpkg_util import (
    _validate_dep_name, _validate_git_arg, sha256_bytes, sha256_file,
)

def cmd_init(args):
    """Create a new package skeleton."""
    name = args.name
    # SCAN-B security fix: validate the package name so `hls-pkg init ../evil`
    # or `hls-pkg init /tmp/owned` can't create directories outside cwd.
    # Same rules as dependency names (letters/digits/._-; no leading . or -).
    try:
        _validate_dep_name(name)
    except ValueError as ex:
        print("error: invalid package name: %s" % ex, file=sys.stderr)
        return 1
    # Also reject path separators (the dep-name regex already does).
    pkg_dir = os.path.join(os.getcwd(), name)
    if os.path.exists(pkg_dir):
        print("error: directory %s already exists" % pkg_dir, file=sys.stderr)
        return 1
    os.makedirs(pkg_dir)
    # Manifest.
    manifest = {
        "package": {
            "name": name,
            "version": "0.1.0",
            "authors": [],
            "description": "A HLS package.",
        },
        "dependencies": {},
        "effects": {"allowed": []},
    }
    write_manifest(manifest, os.path.join(pkg_dir, "hls-pkg.toml"))
    # Entry source.
    src = '''# %s — generated by hls-pkg init.

fn main() -> int uses IO {
    println("Hello from %s!")
    return 0
}
''' % (name, name)
    with open(os.path.join(pkg_dir, "main.hls"), "w") as f:
        f.write(src)
    # README.
    with open(os.path.join(pkg_dir, "README.md"), "w") as f:
        f.write("# %s\n\nA Halis package.\n" % name)
    # .gitignore.
    with open(os.path.join(pkg_dir, ".gitignore"), "w") as f:
        f.write(".hls-pkg-cache/\nhls-pkg.lock\n")
    print("Created package skeleton in %s/" % name)
    print("  hls-pkg.toml   — manifest")
    print("  main.hls       — entry source")
    print("  README.md      — package README")
    print("  .gitignore     — ignores cache + lockfile")
    print("")
    print("Next steps:")
    print("  cd %s" % name)
    print("  hls-pkg add std.str https://github.com/mhieuhonda/halis-lang.git std/str.hls")
    print("  hls-pkg lock")
    print("  hls-pkg audit")
    print("  hls-pkg build")
    return 0


def cmd_add(args):
    """Add a git dependency to the manifest."""
    manifest_path = os.path.join(os.getcwd(), "hls-pkg.toml")
    if not os.path.isfile(manifest_path):
        print("error: no hls-pkg.toml in current directory", file=sys.stderr)
        return 1
    # SCAN-B fix: --tag and --branch are mutually exclusive — silently
    # dropping one was a source of confusing reproducibility bugs.
    if args.tag and args.branch:
        print("error: --tag and --branch are mutually exclusive", file=sys.stderr)
        return 1
    manifest = parse_manifest(manifest_path)
    deps = manifest.setdefault("dependencies", {})
    if not isinstance(deps, dict):
        print("error: [dependencies] section is corrupt (not a table)", file=sys.stderr)
        return 1
    # SCAN-B security fix: validate name + git args BEFORE writing.
    try:
        _validate_dep_name(args.name)
        _validate_git_arg(args.git, "dependency %s git URL" % args.name)
        if args.tag:
            _validate_git_arg(args.tag, "dependency %s tag" % args.name)
        if args.branch:
            _validate_git_arg(args.branch, "dependency %s branch" % args.name)
    except ValueError as ex:
        print("error: %s" % ex, file=sys.stderr)
        return 1
    source = {"git": args.git, "path": args.path}
    if args.tag:
        source["tag"] = args.tag
    if args.branch:
        source["branch"] = args.branch
    deps[args.name] = source
    write_manifest(manifest, manifest_path)
    print("Added dependency: %s" % args.name)
    print("  source: %s" % source)
    return 0


def cmd_lock(args):
    """Resolve dependencies and write hls-pkg.lock."""
    manifest_path = os.path.join(os.getcwd(), "hls-pkg.toml")
    if not os.path.isfile(manifest_path):
        print("error: no hls-pkg.toml in current directory", file=sys.stderr)
        return 1
    manifest = parse_manifest(manifest_path)
    deps = manifest.get("dependencies", {})
    # SCAN-B fix: validate the manifest shape before iterating.
    if deps is None:
        deps = {}
    if not isinstance(deps, dict):
        print("error: [dependencies] section is corrupt (not a table)",
              file=sys.stderr)
        return 1
    pkg_version = manifest.get("package", {}).get("version", "0.0.0")
    pkg_name = manifest.get("package", {}).get("name", "<unnamed>")
    # Stage 22 (v0.41.0-alpha): record the target triple in the lockfile.
    # When --target is given, the lockfile is stamped with the target;
    # `hls-pkg verify --target <triple>` checks that the lockfile's target
    # matches (a mismatch means the deps were resolved for a different
    # platform — re-lock for the current target).
    target_triple = getattr(args, "target", None)
    lockfile = {"version": 2, "target": target_triple, "packages": []}
    for name, source in deps.items():
        print("Resolving %s..." % name, end=" ", flush=True)
        try:
            resolved_path = resolve_dependency(name, source)
        except Exception as ex:
            print("FAILED: %s" % ex)
            return 1
        sha = _sha256_directory(resolved_path) if os.path.isdir(resolved_path) \
            else sha256_file(resolved_path)
        declared, computed = extract_effects(resolved_path)
        # Stage 13 release: record the resolved version + commit hash so
        # `verify` can detect a moved tag (TOCTOU on the git cache).
        resolved_version = source.get("tag") or source.get("branch") or "main"
        commit = None
        # If this is a git dep, find the clone_dir and resolve HEAD.
        if "git" in source:
            repo_hash = sha256_bytes(source["git"].encode("utf-8"))[:12]
            clone_dir = os.path.join(CACHE_DIR, name, repo_hash)
            if os.path.isdir(clone_dir):
                commit = git_current_commit(clone_dir)
        # Stage 13 release: write a transparency-log entry so the
        # dependency's content-addressed record is publicly auditable.
        try:
            log_rec = transparency_log_append({
                "name": name,
                "version": resolved_version,
                "sha256": sha,
                "commit": commit or "<path-dep>",
                "package": pkg_name,
                "package_version": pkg_version,
            })
            log_seq = log_rec["seq"]
        except OSError as ex:
            print("warning: transparency log write failed (%s)" % ex,
                  file=sys.stderr)
            log_seq = None
        print("OK (sha256: %s..)" % sha[:12])
        lockfile["packages"].append({
            "name": name,
            "source": source,
            "version": resolved_version,
            "commit": commit,
            "sha256": sha,
            "effects": declared,
            "transitive_effects": computed,
            "resolved_path": resolved_path,
            "log_seq": log_seq,
        })
    # Write lockfile.
    lockfile_path = os.path.join(os.getcwd(), "hls-pkg.lock")
    with open(lockfile_path, "w") as f:
        json.dump(lockfile, f, indent=2)
    print("")
    print("Wrote lockfile: %s (%d packages)" % (lockfile_path, len(lockfile["packages"])))
    # Effect enforcement: check that the package's declared `effects.allowed`
    # is a superset of every dependency's computed effects.
    effects_section = manifest.get("effects", {})
    if not isinstance(effects_section, dict):
        print("error: [effects] section is corrupt (not a table)", file=sys.stderr)
        return 1
    allowed_raw = effects_section.get("allowed", [])
    # SCAN-B fix: validate `allowed` is a list of strings. A string like
    # "IO" used to be silently expanded to {"I", "O"}, causing every
    # real effect to be flagged as a violation.
    if not isinstance(allowed_raw, list):
        print("error: [effects].allowed must be a list, got %s" %
              type(allowed_raw).__name__, file=sys.stderr)
        return 1
    allowed = set()
    for eff in allowed_raw:
        if not isinstance(eff, str):
            print("error: [effects].allowed entries must be strings, got %s" %
                  type(eff).__name__, file=sys.stderr)
            return 1
        allowed.add(eff)
    violations = []
    for pkg in lockfile["packages"]:
        for eff in pkg["transitive_effects"]:
            if eff not in allowed:
                violations.append((pkg["name"], eff))
    if violations:
        print("")
        print("EFFECT VIOLATIONS:")
        for pkg_name, eff in violations:
            print("  - %s uses %s (not in allowed set)" % (pkg_name, eff))
        print("")
        print("Allowed effects: %s" % (sorted(allowed) or "(none - pure)"))
        return 1
    print("All dependencies respect the package's effect surface.")
    return 0


def _load_lockfile(path: str) -> Optional[Dict]:
    """SCAN-B fix: load and validate the lockfile shape. Returns None on
    malformed JSON or missing required keys — callers print a clean error."""
    try:
        with open(path, "r") as f:
            lockfile = json.load(f)
    except (OSError, ValueError) as ex:
        print("error: cannot read lockfile %s: %s" % (path, ex), file=sys.stderr)
        return None
    if not isinstance(lockfile, dict):
        print("error: lockfile is not a JSON object", file=sys.stderr)
        return None
    pkgs = lockfile.get("packages")
    if not isinstance(pkgs, list):
        print("error: lockfile 'packages' is not a list", file=sys.stderr)
        return None
    return lockfile


def cmd_audit(args):
    """Print the total effect report of the dependency tree."""
    lockfile_path = os.path.join(os.getcwd(), "hls-pkg.lock")
    if not os.path.isfile(lockfile_path):
        print("error: no hls-pkg.lock — run `hls-pkg lock` first", file=sys.stderr)
        return 1
    lockfile = _load_lockfile(lockfile_path)
    if lockfile is None:
        return 1
    pkgs = lockfile["packages"]
    # SCAN-B fix: validate each entry's shape so a malformed lockfile
    # doesn't crash with KeyError/TypeError.
    valid_pkgs = []
    for p in pkgs:
        if not isinstance(p, dict):
            print("warning: skipping malformed package entry (not an object)",
                  file=sys.stderr)
            continue
        if not isinstance(p.get("name"), str):
            print("warning: skipping package entry with missing/non-string name",
                  file=sys.stderr)
            continue
        valid_pkgs.append(p)
    pkgs = valid_pkgs
    name_w = max((len(p["name"]) for p in pkgs), default=4)
    print("=" * (name_w + 60))
    print("  %-*s  %12s  %12s  %s" % (
        name_w, "package", "sha256[..12]", "declared", "transitive"))
    print("=" * (name_w + 60))
    all_effects = set()
    for pkg in pkgs:
        sha = str(pkg.get("sha256", ""))[:12]
        eff_list = pkg.get("effects", [])
        trans_list = pkg.get("transitive_effects", [])
        eff_list = eff_list if isinstance(eff_list, list) else []
        trans_list = trans_list if isinstance(trans_list, list) else []
        decl = ", ".join(str(e) for e in eff_list) or "(none)"
        trans = ", ".join(str(e) for e in trans_list) or "(none)"
        all_effects.update(str(e) for e in trans_list)
        print("  %-*s  %12s  %12s  %s" % (name_w, pkg["name"], sha, decl, trans))
    print("=" * (name_w + 60))
    print("  Total transitive effects of dependency tree: %s" % (
        ", ".join(sorted(all_effects)) or "(none — pure library)"))
    return 0


def cmd_verify(args):
    """Verify the lockfile's SHA-256 hashes still match (Stage 13 release:
    also verify the git HEAD commit matches the recorded one and the
    transparency-log entry exists)."""
    lockfile_path = os.path.join(os.getcwd(), "hls-pkg.lock")
    if not os.path.isfile(lockfile_path):
        print("error: no hls-pkg.lock — run `hls-pkg lock` first", file=sys.stderr)
        return 1
    lockfile = _load_lockfile(lockfile_path)
    if lockfile is None:
        return 1
    # Stage 22 (v0.41.0-alpha): verify the lockfile's target matches
    # the requested target (if --target was given). A mismatch means
    # the deps were resolved for a different platform — re-lock for
    # the current target.
    expected_target = getattr(args, "target", None)
    if expected_target is not None:
        actual_target = lockfile.get("target")
        if actual_target != expected_target:
            print("error: lockfile target mismatch (lockfile has '%s', "
                  "expected '%s') — run `hls-pkg lock --target %s` to "
                  "re-resolve for this target" % (
                      actual_target, expected_target, expected_target),
                  file=sys.stderr)
            return 1
        print("lockfile target: %s (matches --target)" % actual_target)
    else:
        actual_target = lockfile.get("target")
        if actual_target is not None:
            print("lockfile target: %s (use --target %s to verify a specific "
                  "target)" % (actual_target, actual_target))
    failures = 0
    warnings = 0
    for pkg in lockfile["packages"]:
        if not isinstance(pkg, dict):
            print("  [FAIL] <malformed entry>: not an object")
            failures += 1
            continue
        name = pkg.get("name", "?")
        path = pkg.get("resolved_path", "")
        if not isinstance(path, str) or not os.path.exists(path):
            print("  [FAIL] %s: file not found (%s)" % (name, path))
            failures += 1
            continue
        # SCAN-B fix: handle both file and directory (multi-file pkgs).
        if os.path.isdir(path):
            # Walk the directory and verify the per-file SHA chain.
            # The lockfile records the directory's content hash.
            actual_sha = _sha256_directory(path)
        else:
            actual_sha = sha256_file(path)
        expected_sha = str(pkg.get("sha256", ""))
        if actual_sha != expected_sha:
            print("  [FAIL] %s: hash mismatch (expected %s, got %s)" % (
                name, expected_sha[:12], actual_sha[:12]))
            failures += 1
            continue
        # Stage 13 release: verify the git commit (if recorded).
        recorded_commit = pkg.get("commit")
        if recorded_commit and isinstance(recorded_commit, str) and \
                _re_mod.fullmatch(r"[0-9a-f]{40}", recorded_commit):
            # Reconstruct the clone_dir for git deps.
            source = pkg.get("source", {})
            if isinstance(source, dict) and "git" in source:
                try:
                    _validate_dep_name(name)
                    repo_hash = sha256_bytes(source["git"].encode("utf-8"))[:12]
                    clone_dir = os.path.join(CACHE_DIR, name, repo_hash)
                    if os.path.isdir(clone_dir):
                        cur_commit = git_current_commit(clone_dir)
                        if cur_commit != recorded_commit:
                            print("  [FAIL] %s: commit moved (expected %s, "
                                  "got %s) — a moved tag detected" %
                                  (name, recorded_commit[:12],
                                   (cur_commit or "?")[:12]))
                            failures += 1
                            continue
                except (ValueError, OSError) as ex:
                    # Deep-scan-20 fix (MEDIUM, fail-open): the previous
                    # `pass` silently skipped commit verification on any
                    # error — including a missing clone_dir (which could
                    # indicate the cache was deleted to hide a moved
                    # tag). Surface as a warning so the user knows the
                    # supply-chain commit pin was not re-verified.
                    print("  [WARN] %s: commit verification skipped (%s) — "
                          "clone dir may be missing or stale" % (name, ex))
                    warnings += 1
                    continue
        # Stage 13 release: transparency-log lookup.
        log_seq = pkg.get("log_seq")
        if isinstance(log_seq, int):
            rec = transparency_log_lookup(name, pkg.get("version"))
            if rec is None:
                print("  [WARN] %s: no transparency log entry found" % name)
            elif rec.get("seq") != log_seq:
                print("  [WARN] %s: transparency log seq drifted (expected %d, "
                      "got %s)" % (name, log_seq, rec.get("seq")))
            elif rec.get("sha256") != expected_sha:
                print("  [WARN] %s: transparency log SHA-256 mismatch" % name)
        print("  [ OK ] %s: hash matches (%s)" % (name, actual_sha[:12]))
    if failures:
        print("")
        print("Verification FAILED: %d packages have hash mismatches." % failures)
        return 1
    print("")
    print("All %d packages verified." % len(lockfile["packages"]))
    return 0


def cmd_build(args):
    """Compile the package with resolved dependencies.

    Stage 13 release: when a dependency resolves to a directory (multi-file
    package), symlink the WHOLE directory into `.hls-pkg-deps/<name>/` so
    boot.py's import resolver can find sibling imports. The legacy single-
    file contract is preserved."""
    manifest_path = os.path.join(os.getcwd(), "hls-pkg.toml")
    if not os.path.isfile(manifest_path):
        print("error: no hls-pkg.toml in current directory", file=sys.stderr)
        return 1
    # Parse the manifest to validate it early.
    parse_manifest(manifest_path)
    entry = args.entry or "main.hls"
    if not os.path.isfile(entry):
        print("error: entry file not found: %s" % entry, file=sys.stderr)
        return 1
    boot_py = os.path.join(REPO_ROOT, "boot", "boot.py")
    print("Building %s..." % entry)
    lock_path = os.path.join(os.getcwd(), "hls-pkg.lock")
    env = os.environ.copy()
    deps_dir = None
    if os.path.isfile(lock_path):
        lockfile = _load_lockfile(lock_path)
        if lockfile is None:
            return 1
        deps_dir = os.path.join(os.getcwd(), ".hls-pkg-deps")
        os.makedirs(deps_dir, exist_ok=True)
        for pkg in lockfile.get("packages", []):
            if not isinstance(pkg, dict):
                continue
            rp = pkg.get("resolved_path", "")
            if not isinstance(rp, str) or not rp or not os.path.exists(rp):
                # SCAN-B fix: explicit error instead of silent skip.
                print("error: dependency %s: resolved path missing (%s) — "
                      "run `hls-pkg lock` again" % (pkg.get("name", "?"), rp),
                      file=sys.stderr)
                return 1
            # Validate the dep name before using it in any path join.
            try:
                _validate_dep_name(pkg["name"])
            except (ValueError, KeyError) as ex:
                print("error: lockfile contains %s" % ex, file=sys.stderr)
                return 1
            # Verify hash (BUG-DS4-24 — fail closed on TOCTOU).
            if os.path.isdir(rp):
                actual_sha = _sha256_directory(rp)
            else:
                actual_sha = sha256_file(rp)
            if actual_sha != pkg.get("sha256"):
                print("error: dependency %s hash mismatch (expected %s, "
                      "got %s) — run `hls-pkg lock` again, or investigate."
                      % (pkg.get("name"),
                         str(pkg.get("sha256"))[:12], actual_sha[:12]),
                      file=sys.stderr)
                return 1
            # Stage 13 release: multi-file package support. If the dep is
            # a directory, symlink the whole dir into .hls-pkg-deps/<name>/
            # so sibling imports resolve. Otherwise, link as <name>.hls.
            if os.path.isdir(rp):
                dst = os.path.join(deps_dir, pkg["name"])
                if os.path.islink(dst) or os.path.exists(dst):
                    if os.path.islink(dst) or os.path.isfile(dst):
                        os.remove(dst)
                    else:
                        import shutil as _shutil
                        _shutil.rmtree(dst)
                try:
                    os.symlink(os.path.abspath(rp), dst)
                except OSError:
                    import shutil as _shutil
                    _shutil.copytree(rp, dst)
            else:
                dst = os.path.join(deps_dir, pkg["name"] + ".hls")
                try:
                    if os.path.islink(dst) or os.path.exists(dst):
                        os.remove(dst)
                    os.symlink(os.path.abspath(rp), dst)
                except OSError:
                    import shutil as _shutil
                    _shutil.copy2(rp, dst)
        env["HLS_PKG_DEPS"] = deps_dir
    # Stage 20 (v0.36.0-alpha): --lto — compile the package NATIVELY
    # with the whole-program LTO pipeline (cross-crate inlining + DCE)
    # instead of interpreting: hlc --lto -> C -> cc -> run.
    if getattr(args, "lto", False):
        hlc_src = os.path.join(REPO_ROOT, "src", "hlc.hls")
        if not os.path.isfile(hlc_src):
            print("error: cannot find src/hlc.hls (repo layout changed?)",
                  file=sys.stderr)
            return 1
        out_dir = os.path.join(os.getcwd(), ".hls-pkg-build")
        os.makedirs(out_dir, exist_ok=True)
        out_c = os.path.join(out_dir, "pkg_lto.c")
        out_bin = os.path.join(out_dir, "pkg_lto_bin")
        cmd = [sys.executable, boot_py, hlc_src, "--lto", entry, out_c]
        print("  $ %s" % " ".join(cmd))
        r1 = subprocess.run(cmd, env=env)
        if r1.returncode != 0:
            return r1.returncode
        cc = os.environ.get("CC", "cc")
        cmd = [cc, "-O2", "-o", out_bin, out_c, "-lm", "-pthread"]
        print("  $ %s" % " ".join(cmd))
        r2 = subprocess.run(cmd, env=env)
        if r2.returncode != 0:
            return r2.returncode
        print("  $ %s" % out_bin)
        r3 = subprocess.run([out_bin], env=env)
        return r3.returncode
    # Stage 22 (v0.41.0-alpha): --target <triple> — cross-compile the
    # package's entry point to a foreign binary via hlcross. The
    # resolver still uses boot.py to load + check the program (the
    # cross-compilation only changes the FINAL hlc + linker step).
    target_triple = getattr(args, "target", None)
    # Stage 24 (v0.43.0-alpha): wasm32 targets go through hlwasm (with
    # wasm-opt) instead of hlcross. The roadmap's Stage 24 acceptance:
    # "hls-pkg build --target wasm32 runs wasm-opt -O3 on the output."
    if target_triple is not None and target_triple.startswith("wasm32"):
        hlwasm = os.path.join(REPO_ROOT, "tools", "hlwasm.py")
        if not os.path.isfile(hlwasm):
            print("error: cannot find tools/hlwasm.py (repo layout changed?)",
                  file=sys.stderr)
            return 1
        out_dir = os.path.join(os.getcwd(), ".hls-pkg-build")
        os.makedirs(out_dir, exist_ok=True)
        out_base = os.path.join(out_dir, "pkg_wasm")
        wasm_opt_mode = getattr(args, "wasm_opt", "auto") or "auto"
        opt_level = getattr(args, "opt_level", "O3") or "O3"
        glue = getattr(args, "glue", "compact") or "compact"
        cmd = [sys.executable, hlwasm, entry, out_base,
               "--target", target_triple,
               "--wasm-opt", wasm_opt_mode,
               "--opt-level", opt_level,
               "--glue", glue]
        print("  $ %s" % " ".join(cmd))
        result = subprocess.run(cmd, env=env)
        return result.returncode
    if target_triple is not None:
        hlcross = os.path.join(REPO_ROOT, "tools", "hlcross.py")
        if not os.path.isfile(hlcross):
            print("error: cannot find tools/hlcross.py (repo layout changed?)",
                  file=sys.stderr)
            return 1
        out_dir = os.path.join(os.getcwd(), ".hls-pkg-build")
        os.makedirs(out_dir, exist_ok=True)
        out_bin = os.path.join(out_dir, "pkg_cross_" +
                               target_triple.replace("-", "_"))
        cmd = [sys.executable, hlcross, entry, out_bin,
               "--target", target_triple]
        print("  $ %s" % " ".join(cmd))
        result = subprocess.run(cmd, env=env)
        return result.returncode
    cmd = [sys.executable, boot_py, entry]
    print("  $ %s" % " ".join(cmd))
    result = subprocess.run(cmd, env=env)
    return result.returncode


def _sha256_directory(path: str) -> str:
    """Stage 13 release: compute a deterministic content hash over a
    directory (sorted file list, each file's SHA-256 + relative path).
    Used by `cmd_lock`/`cmd_verify` for multi-file packages."""
    h = hashlib.sha256()
    for root, dirs, files in os.walk(path):
        dirs.sort()
        for fn in sorted(files):
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, path).replace(os.sep, "/")
            h.update(rel.encode("utf-8"))
            h.update(b"\x00")
            with open(full, "rb") as f:
                while True:
                    chunk = f.read(65536)
                    if not chunk:
                        break
                    h.update(chunk)
            h.update(b"\x00")
    return h.hexdigest()


def cmd_publish(args):
    """Stage 13 release: append the current package's content to the
    transparency log. Records the package name, version, content SHA-256,
    and (for git deps) the current commit. After publishing, the entry is
    publicly verifiable via `hls-pkg verify`."""
    manifest_path = os.path.join(os.getcwd(), "hls-pkg.toml")
    if not os.path.isfile(manifest_path):
        print("error: no hls-pkg.toml in current directory", file=sys.stderr)
        return 1
    manifest = parse_manifest(manifest_path)
    pkg_section = manifest.get("package", {})
    if not isinstance(pkg_section, dict):
        print("error: [package] section is corrupt", file=sys.stderr)
        return 1
    name = pkg_section.get("name", "<unnamed>")
    version = pkg_section.get("version", "0.0.0")
    # Compute the content SHA-256 over the package's HLS sources.
    cwd = os.getcwd()
    sources = []
    for root, dirs, files in os.walk(cwd):
        # Skip hidden dirs (.git, .hls-pkg-cache, .hls-pkg-deps).
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for fn in files:
            if fn.endswith(".hls"):
                sources.append(os.path.join(root, fn))
    sources.sort()
    h = hashlib.sha256()
    for s in sources:
        rel = os.path.relpath(s, cwd).replace(os.sep, "/")
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        # Deep-scan-20 fix (LOW, OOM): the previous `h.update(f.read())`
        # read the entire file into memory. A multi-GB .hls file (or a
        # maliciously crafted one) would crash with MemoryError. Use
        # the same chunked-read pattern as _sha256_directory.
        with open(s, "rb") as f:
            while True:
                chunk = f.read(65536)
                if not chunk:
                    break
                h.update(chunk)
        h.update(b"\x00")
    content_sha = h.hexdigest()
    # Append to the transparency log.
    rec = transparency_log_append({
        "name": name,
        "version": version,
        "sha256": content_sha,
        "kind": "publish",
        "files": len(sources),
    })
    print("Published %s@%s" % (name, version))
    print("  content sha256: %s" % content_sha)
    print("  transparency log seq: %d" % rec["seq"])
    print("  chain hash: %s" % rec["chain_hash"][:24] + "...")
    return 0


def cmd_log(args):
    """Stage 13 release: print the transparency log (or verify its chain)."""
    if args.verify:
        errors = transparency_log_verify_chain()
        if errors:
            print("Transparency log verification FAILED:")
            for e in errors:
                print("  - " + e)
            return 1
        print("Transparency log verification OK (chain is sound).")
        return 0
    # Print the log.
    try:
        with open(TRANSPARENCY_LOG, "rb") as f:
            lines = f.readlines()
    except (FileNotFoundError, OSError):
        print("(no transparency log; nothing to display)")
        return 0
    if not lines:
        print("(transparency log is empty)")
        return 0
    print("seq  timestamp            name                  version   sha256[..12]")
    print("-" * 80)
    for ln in lines:
        ln = ln.strip()
        if not ln:
            continue
        try:
            rec = json.loads(ln.decode("utf-8"))
        except ValueError:
            continue
        ts = time.strftime("%Y-%m-%d %H:%M:%S",
                           time.localtime(rec.get("timestamp", 0)))
        print("%-4d %-20s %-20s %-8s %s" % (
            rec.get("seq", 0), ts,
            str(rec.get("name", "?"))[:20],
            str(rec.get("version", "?"))[:8],
            str(rec.get("sha256", ""))[:12]))
    return 0


# ---------------------------------------------------------------------------
# CLI entry point.
# ---------------------------------------------------------------------------



__all__ = [
    "_load_lockfile",
    "_sha256_directory",
    "cmd_add",
    "cmd_audit",
    "cmd_build",
    "cmd_init",
    "cmd_lock",
    "cmd_log",
    "cmd_publish",
    "cmd_verify",
]
