"""LLVM IR emitter for Halis (Stage 12).

Emits LLVM IR text (.ll) from a checked HLS program (post-type-check AST).
The IR can be assembled by `llc` or `clang` into an object file.

Design:
  - The HLS C runtime (emitted inline by `src/hlc.hls` codegen) is treated
    as an opaque external library. The LLVM emitter declares each runtime
    function as `declare` and calls them via `call`. The symbol names and
    signatures mirror the ACTUAL runtime (hl_str_from_int64, hl_div_i64,
    hl_box_i64, ...) — not aspirational ones.
  - HLS types map to LLVM types as follows:
      int    -> i64
      float  -> double
      bool   -> i1   (COMPARISONS/`&&`/`||`/`!` all produce and consume i1;
                      there is no i64 widening of booleans anywhere)
      str    -> ptr (pointer to %hl_str)
      void   -> void
      tainted[T] -> LLVM type of T (taint is compile-time only, like the
                    C backend)
      list[T] / map[str,T] / struct / enum -> ptr (opaque)
  - Each HLS function becomes an LLVM `define` with the appropriate
      parameter types. Extern "C" declarations become `declare` (Stage 15).
  - Local variable slots are HOISTED to the function entry block: `alloca`
      inside a loop body would grow the stack on every iteration (LLVM
      allocas are not reclaimed until function return), so every `let` /
      `for`-loop variable gets its slot pre-allocated in `entry:`.
  - Basic blocks are emitted for `if`/`while`/`for` control flow. The
      emitter tracks the CURRENT open block label (self._cur_block) so that
      (a) no instruction is ever emitted after a terminator (dead code after
      `return`/`break`/`continue`/`panic`/`exit` is skipped), and (b) `&&` /
      `||` can be lowered to real short-circuit control flow with `phi`.
  - Integer `+`/`-`/`*` use llvm.sadd/ssub/smul.with.overflow.i64 with an
      overflow-path branch to `hl_die` (matching the C runtime's
      hl_add_i64/hl_sub_i64/hl_mul_i64). Integer `/`/`%`/unary `-` call the
      runtime's hl_div_i64/hl_mod_i64/hl_neg_i64 so the zero / INT64_MIN /
      -1 panics are byte-identical to the interpreter and the C backend.
  - Dynamic lists store BOXED elements (hl_box_i64/hl_box_f64/hl_box_bool/
      hl_box_ptr on push/set, load from the box pointer on get) — the same
      ABI as the C runtime.

Constructs that the alpha backend does not support yet — struct literals,
struct field access, enum literals, `match`, `?`, and calls to USER-DEFINED
struct methods — raise a clean HLError ("not yet supported by --emit llvm")
instead of silently emitting invalid IR. See ROADMAP.md "Remaining work for
Stage 12".

Multi-target support:
  - The default target is the host triple (queried from `llvm-config`).
  - `--target aarch64-linux` cross-compiles.
  - PGO (profile-guided optimisation) is deferred to a later stage.

The emitter is a *separate backend* from the C codegen. It is wired into
`boot.py` via the `--emit llvm` flag.
"""
from __future__ import annotations
from typing import Dict, List, Optional, Tuple

import os
import sys

# Resolve HLError whether we are imported as `llvm_emit` (sys.path contains
# the repo root, set up by boot.py) or run from anywhere.
try:
    from boot.lexer import HLError  # type: ignore
except ImportError:  # pragma: no cover
    _REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if _REPO_ROOT not in sys.path:
        sys.path.insert(0, _REPO_ROOT)
    from boot.lexer import HLError  # type: ignore


# Runtime function declarations — these mirror the C runtime emitted by
# src/hlc.hls EXACTLY (see the r.push("static ...") lines in the runtime
# section of hlc.hls). BUG-DS4-3 fix: the old table declared symbols that
# do not exist in the runtime (hl_int_to_str, hl_float_to_str,
# hl_str_to_float, hl_str_subst, hl_str_lower, hl_str_upper, hl_str_repeat,
# hl_str_reverse, hl_args_count, hl_args_get, hl_ord) and MISSED the ones
# that do (hl_str_from_int64, hl_str_from_double, hl_str_from_bool,
# hl_str_to_double, hl_range, hl_args, hl_panic, hl_chr, hl_box_*,
# hl_unbox helpers, hl_div_i64, hl_mod_i64, hl_neg_i64, hl_abs_i64,
# hl_clone_*). Assembling/linking the old output failed with undefined
# symbols; the new table matches the runtime 1:1.
RUNTIME_DECLS = """
; ===== Halis runtime declarations (opaque externals) =====
; Layout mirrors the C runtime generated by src/hlc.hls.
%hl_str  = type { i64, ptr }              ; { len, data }
%hl_list = type { i64, i64, ptr }         ; { len, cap, items }
%hl_map  = type { i64, i64, ptr, ptr, ptr }

declare void     @hl_die(ptr) #0                 ; const char* -> noreturn
declare void     @hl_panic(ptr) #0                 ; hl_str* -> noreturn (panic: msg, exit 101)
declare void     @hl_exit(i64) #0                  ; noreturn
declare i64      @hl_clock_ms()
declare ptr      @hl_args()                         ; -> hl_list* (list[str])
; Stage 46 (v0.65.0-alpha): thread / scheduling builtins.
; hl_thread_sleep_ms blocks the calling thread for N ms via nanosleep.
; hl_thread_yield hints the scheduler (sched_yield on POSIX).
; hl_thread_current_id returns a non-zero thread identifier
; (pthread_self cast to int64 — the actual value is implementation-
; defined and may differ from the interpreter; callers must only
; rely on "different threads get different IDs").
declare void     @hl_thread_sleep_ms(i64)           ; (ms) -> void
declare void     @hl_thread_yield()                 ; () -> void
declare i64      @hl_thread_current_id()            ; () -> int
declare i1       @hl_file_exists(ptr)
declare ptr      @hl_read_file(ptr)
declare void     @hl_write_file(ptr, ptr)
; Stage 36 (v0.55.0-alpha): filesystem metadata builtins.
declare ptr      @hl_fs_read_dir(ptr)               ; -> hl_list* (list[str])
declare i64      @hl_fs_size(ptr)
declare i1       @hl_fs_is_dir(ptr)
declare void     @hl_fs_set_perms(ptr, i64)
declare void     @hl_print(ptr)                     ; hl_str*
declare void     @hl_println(ptr)                   ; hl_str*
; Stage 56 (v0.75.0-alpha): stderr + TTY-detection builtins.
; hl_eprint / hl_eprintln write to stderr (consuming the str — the
; same ownership convention as hl_print / hl_println; they fflush
; stdout first in the C runtime). hl_isatty(fd) -> bool (i1).
declare void     @hl_eprint(ptr)                    ; hl_str* -> stderr
declare void     @hl_eprintln(ptr)                  ; hl_str* -> stderr + '\n'
declare i1       @hl_isatty(i64)                    ; (fd) -> bool
; Stage 57 (v0.76.0-alpha): process-identity runtime helpers (syslog
; TAG[PID] + HOSTNAME fields for std.log). Both take no arguments.
declare i64      @hl_proc_pid()                     ; -> OS process id
declare ptr      @hl_sys_hostname()                 ; -> fresh str host name

; strings
declare ptr      @hl_str_alloc(i64)
declare ptr      @hl_str_from(ptr, i64)             ; (const char* data, i64 len) -> hl_str*
declare ptr      @hl_str_concat(ptr, ptr)
declare i1       @hl_str_eq(ptr, ptr)
declare i64      @hl_str_cmp(ptr, ptr)
declare i64      @hl_str_len(ptr)
declare i64      @hl_str_byte_at(ptr, i64)
declare ptr      @hl_str_slice(ptr, i64, i64)
declare i64      @hl_str_find(ptr, ptr)
declare i1       @hl_str_contains(ptr, ptr)
declare i1       @hl_str_starts_with(ptr, ptr)
declare i1       @hl_str_ends_with(ptr, ptr)
declare ptr      @hl_str_split(ptr, ptr)
declare ptr      @hl_str_trim(ptr)
declare ptr      @hl_str_from_int64(i64)
declare ptr      @hl_str_from_double(double)
declare ptr      @hl_str_from_bool(i1)
declare i64      @hl_str_to_int(ptr)
declare double   @hl_str_to_double(ptr)
declare ptr      @hl_chr(i64)                       ; -> hl_str*
declare ptr      @hl_clone_str(ptr)

; checked int64 arithmetic (identical panics to the interpreter)
declare i64      @hl_neg_i64(i64)
declare i64      @hl_abs_i64(i64)
declare i64      @hl_div_i64(i64, i64)
declare i64      @hl_mod_i64(i64, i64)
declare i64      @hl_float_to_int(double)           ; range-checked

; dynamic list (boxed elements)
declare ptr      @hl_list_new(ptr)               ; (elem_free) — arena mode passes null
declare void     @hl_list_push(ptr, ptr)
declare ptr      @hl_list_get(ptr, i64)
declare void     @hl_list_set(ptr, i64, ptr)
declare ptr      @hl_list_pop(ptr)
declare i64     @hl_list_pop_i64(ptr)              ; pop + unbox + free the box
declare double  @hl_list_pop_f64(ptr)
declare i1      @hl_list_pop_bool(ptr)
declare i64      @hl_list_len(ptr)
declare ptr      @hl_range(i64, i64)
declare ptr      @hl_str_join(ptr, ptr)         ; (list[str], sep) -> str — O(n) join (Stage 19)
declare i1      @hl_simd_cpu_supports(ptr)      ; (feature name) -> bool (Stage 21 runtime probe)

; boxed element constructors (get uses a plain load from the box pointer)
declare ptr      @hl_box_i64(i64)
declare ptr      @hl_box_f64(double)
declare ptr      @hl_box_bool(i1)
declare ptr      @hl_box_ptr(ptr)

; map[str, T]
declare ptr      @hl_map_new(ptr)                ; (val_free) — arena mode passes null
declare i64     @hl_map_get_i64(ptr, ptr, i64)    ; (m, k, default) -> value or default
declare double  @hl_map_get_f64(ptr, ptr, double)
declare i1      @hl_map_get_bool(ptr, ptr, i1)
declare ptr     @hl_map_borrow(ptr, ptr)           ; (m, k) -> stored value or null
declare void     @hl_map_set(ptr, ptr, ptr)
declare i1       @hl_map_has(ptr, ptr)
declare i64      @hl_map_len(ptr)
declare ptr      @hl_map_keys(ptr)

; per-instantiation clone helpers (Stage 8-alpha subset)
declare ptr      @hl_clone_list_int(ptr)
declare ptr      @hl_clone_list_float(ptr)
declare ptr      @hl_clone_list_bool(ptr)
declare ptr      @hl_clone_list_str(ptr)
declare ptr      @hl_clone_map_int(ptr)
declare ptr      @hl_clone_map_float(ptr)
declare ptr      @hl_clone_map_bool(ptr)
declare ptr      @hl_clone_map_str(ptr)

; Stage 12 release: struct/enum runtime constructors + field accessors.
; These symbols are emitted by the C backend's runtime codegen (see
; gen_struct_lit / gen_field in src/hlc.hls). The LLVM backend calls them
; via opaque ptr — the layout is owned by the C runtime.
declare ptr      @hl_struct_alloc(i64)              ; (size in bytes) -> opaque ptr
declare void     @hl_struct_set_i64(ptr, i64, i64)  ; (struct, field_idx, value)
declare void     @hl_struct_set_f64(ptr, i64, double)
declare void     @hl_struct_set_bool(ptr, i64, i1)
declare void     @hl_struct_set_ptr(ptr, i64, ptr)
declare i64      @hl_struct_get_i64(ptr, i64)
declare double   @hl_struct_get_f64(ptr, i64)
declare i1       @hl_struct_get_bool(ptr, i64)
declare ptr      @hl_struct_get_ptr(ptr, i64)

; Enum tag access (the runtime emits enums as a tagged-union struct).
declare i64      @hl_enum_tag(ptr)                  ; -> variant index
declare ptr      @hl_enum_new_variant(i64)          ; (variant_idx) -> new enum value
declare ptr      @hl_enum_payload(ptr)               ; -> payload ptr (variant data)

; Stage 12 release: stdin / read_line (Stage 10 release runtime helpers).
declare ptr      @hl_read_line()                   ; -> hl_str* (one line, CRLF stripped)

; Stage 12 release: net / rand / proc runtime helpers (Stage 9 release).
declare i1       @hl_net_lookup(ptr, ptr)           ; (host, out_ip) -> success
; Stage 37 (v0.56.0-alpha): TCP / UDP / TLS runtime helpers. All
; socket helpers take / return primitive int64 fd values; the str
; arguments (host / path / data) are owned ptr (one retain released
; inside the helper). net_read / net_udp_recv_from / net_tls_get
; return a fresh hl_str* (refcnt=1, ownership transfers to the caller).
declare i64      @hl_net_tcp_connect(ptr, i64)       ; (host, port) -> fd
declare i64      @hl_net_tcp_listen(ptr, i64, i64)   ; (host, port, backlog) -> fd
declare i64      @hl_net_tcp_accept(i64)             ; (fd) -> client_fd
declare ptr      @hl_net_read(i64, i64)              ; (fd, n) -> fresh str
declare i64      @hl_net_write(i64, ptr)             ; (fd, data) -> bytes_written
declare void     @hl_net_close(i64)                  ; (fd)
declare i64      @hl_net_udp_open()                  ; -> fd
declare i64      @hl_net_udp_send_to(i64, ptr, i64, ptr) ; (fd, host, port, data)
declare ptr      @hl_net_udp_recv_from(i64, i64)     ; (fd, n) -> fresh str
declare ptr      @hl_net_tls_get(ptr, i64, ptr)      ; (host, port, path) -> fresh str
declare i64      @hl_rand_int(i64)                  ; (max_exclusive) -> [0, max)
declare double   @hl_rand_float()
declare void     @hl_rand_seed(i64)
declare i64      @hl_proc_exec(ptr)                 ; (cmd) -> exit code
; Stage 47 (v0.66.0-alpha): process management runtime helpers.
; hl_proc_spawn forks+execs a child; the program (arg 0) and args
; (arg 1) are owned ptr (one retain released inside the helper);
; the stdio kind ints are i64. Returns the Halis pid (>= 1) or -1.
; hl_proc_wait blocks until the child exits; returns the encoded
; exit status (0..255 normal, 128+signum signal, -1 on error).
; hl_proc_kill sends SIGTERM. hl_proc_child_write consumes the data
; str (arg 1). hl_proc_child_read returns a fresh str. hl_proc_child_close
; is idempotent (closing a closed pipe returns 0).
declare i64      @hl_proc_spawn(ptr, ptr, i64, i64, i64)  ; (program, args, stdin_kind, stdout_kind, stderr_kind) -> pid
declare i64      @hl_proc_wait(i64)                     ; (pid) -> exit_status
declare i64      @hl_proc_kill(i64)                     ; (pid) -> 0 / -1
declare i64      @hl_proc_child_write(i64, ptr)         ; (pid, data) -> bytes_written
declare ptr      @hl_proc_child_read(i64, i64, i64)     ; (pid, fd_kind, n) -> fresh str
declare i64      @hl_proc_child_close(i64, i64)         ; (pid, fd_kind) -> 0 / -1
; Stage 48 (v0.67.0-alpha): environment + cwd runtime helpers.
; hl_env_get returns a fresh str (the value, or "" if not found);
; consumes the key. hl_env_has returns a bool; consumes the key.
; hl_env_set consumes both key and value. hl_env_unset consumes the
; key. hl_cwd_get returns a fresh str (no args). hl_cwd_set consumes
; the path; returns 0 / -1. args_os uses hl_args() (no new symbol).
declare ptr      @hl_env_get(ptr)                     ; (key) -> fresh str
declare i1       @hl_env_has(ptr)                      ; (key) -> bool
declare void     @hl_env_set(ptr, ptr)                ; (key, value)
declare void     @hl_env_unset(ptr)                   ; (key)
declare ptr      @hl_cwd_get()                        ; -> fresh str
declare i64      @hl_cwd_set(ptr)                     ; (path) -> 0 / -1
; Stage 49 (v0.68.0-alpha): high-resolution time runtime helpers.
; hl_instant_now_ns returns monotonic nanoseconds (high-resolution,
; unaffected by wall-clock changes — used by Instant::now()).
; hl_system_time_now_ms returns wall-clock milliseconds since the
; Unix epoch (1970-01-01 UTC) — used by SystemTime::now(). The wall
; clock can jump on NTP adjustments — Instant should be used for
; duration measurements, SystemTime for timestamps.
declare i64      @hl_instant_now_ns()                  ; -> monotonic ns
declare i64      @hl_system_time_now_ms()              ; -> wall-clock ms
; Stage 50 (v0.69.0-alpha): libm-backed math runtime helpers.
; All math_* helpers take double and return double (or i1 for the
; predicates isnan / isinf / isfinite / signbit). math_atan2 / pow /
; hypot / fmod / copysign take 2 doubles. The helpers are thin
; wrappers around libm functions (declared here as opaque externals —
; the linker resolves them to libm via -lm).
declare double   @hl_math_sin(double)                  ; sin
declare double   @hl_math_cos(double)                  ; cos
declare double   @hl_math_tan(double)                  ; tan
declare double   @hl_math_asin(double)                 ; asin
declare double   @hl_math_acos(double)                 ; acos
declare double   @hl_math_atan(double)                 ; atan
declare double   @hl_math_atan2(double, double)        ; atan2(y, x)
declare double   @hl_math_sinh(double)                 ; sinh
declare double   @hl_math_cosh(double)                 ; cosh
declare double   @hl_math_tanh(double)                 ; tanh
declare double   @hl_math_exp(double)                  ; exp
declare double   @hl_math_log(double)                  ; natural log
declare double   @hl_math_log10(double)                ; log10
declare double   @hl_math_log2(double)                 ; log2
declare double   @hl_math_pow(double, double)          ; pow(base, exp)
declare double   @hl_math_sqrt(double)                 ; sqrt
declare double   @hl_math_cbrt(double)                 ; cube root
declare double   @hl_math_hypot(double, double)        ; sqrt(x*x+y*y)
declare double   @hl_math_fmod(double, double)         ; C fmod
declare double   @hl_math_erf(double)                  ; error function
declare double   @hl_math_erfc(double)                 ; complementary erf
declare double   @hl_math_tgamma(double)               ; gamma function
declare double   @hl_math_lgamma(double)               ; log|gamma(x)|
declare i1       @hl_math_isnan(double)                ; IEEE-754 isnan
declare i1       @hl_math_isinf(double)                ; IEEE-754 isinf
declare i1       @hl_math_isfinite(double)             ; IEEE-754 isfinite
declare i1       @hl_math_signbit(double)              ; IEEE-754 signbit
declare double   @hl_math_copysign(double, double)     ; copysign(x, y)
"""

# Stage 12 release: attributes block. `#0` is the noreturn attribute set
# attached to hl_die / hl_panic / hl_exit above so the LLVM optimiser
# knows those calls don't return (otherwise it may DCE the trailing
# `unreachable` and move code across the call, breaking control flow).
ATTRIBUTES = """
attributes #0 = { noreturn }
"""

# Intrinsic declarations (LLVM recognises intrinsics without declares, but
# being explicit keeps the module self-documenting).
INTRINSIC_DECLS = """
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare double     @llvm.fabs.f64(double)
"""


# HLS -> LLVM type mapping.
def hls_type_to_llvm(t: str) -> str:
    if t == "int":
        return "i64"
    if t == "float":
        return "double"
    if t == "bool":
        return "i1"
    if t == "void":
        return "void"
    if t == "str":
        return "ptr"
    # Taint is compile-time only (same as the C backend): tainted[T]
    # values have the representation of T at runtime.
    if t.startswith("tainted["):
        return hls_type_to_llvm(_taint_inner(t))
    if t.startswith("list[") or t.startswith("map["):
        return "ptr"
    # User-defined struct / enum -> opaque pointer.
    return "ptr"


# Small local type-string helpers (mirror boot/checker.py's predicates).
def _is_list(t: str) -> bool:
    return t.startswith("list[")


def _list_elem(t: str) -> str:
    return t[5:-1]


def _is_map(t: str) -> bool:
    return t.startswith("map[str, ")


def _map_val(t: str) -> str:
    return t[9:-1]


def _taint_inner(t: str) -> str:
    if t.startswith("tainted["):
        return t[8:-1]
    return t


def _unsupported(what: str, node: Dict):
    """Raise a clean compile error for constructs the alpha LLVM backend
    does not support yet (ROADMAP Stage 12 'Remaining work'). Silently
    emitting invalid IR is worse than a clear error."""
    line = node.get("line", 0) if isinstance(node, dict) else 0
    raise HLError(
        "%s is not yet supported by --emit llvm (Stage 12-alpha subset; "
        "see ROADMAP.md 'Remaining work for Stage 12'). The C backend "
        "(-C / hlc.hls) supports it." % what, line, 0)


# ---------------------------------------------------------------------------
# Emitter
# ---------------------------------------------------------------------------



__all__ = [
    "ATTRIBUTES",
    "Dict",
    "HLError",
    "INTRINSIC_DECLS",
    "List",
    "Optional",
    "RUNTIME_DECLS",
    "Tuple",
    "_is_list",
    "_is_map",
    "_list_elem",
    "_map_val",
    "_taint_inner",
    "_unsupported",
    "annotations",
    "hls_type_to_llvm",
    "os",
    "sys",
]
